import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from inline_grammar import parse_peg_grammar
from grammar_types import load_grammar_types, load_matcher_rule_overrides
from transformer_trampoline_config import load_transformer_trampoline_config
from generate_transformer import (
    ChoiceNode,
    LiteralNode,
    OptionalNode,
    ReferenceNode,
    RepeatNode,
    SequenceNode,
    tokens_to_ast,
)


scripts_dir = Path(__file__).resolve().parents[1]
src_dir = scripts_dir.parent / "src"
statements_dir = src_dir / "parser" / "peg" / "grammar" / "statements"
type_dir = scripts_dir / "parser"


def ops_name(rule_name):
    result = []
    for idx, char in enumerate(rule_name):
        if idx > 0 and char.isupper() and not rule_name[idx - 1].isupper():
            result.append("_")
        result.append(char.upper())
    return "".join(result) + "_OPS"


def init_name(rule_name):
    return f"Initialize{rule_name}Trampoline"


def finalize_name(rule_name):
    return f"Finalize{rule_name}Trampoline"


def load_grammar_rules(gram_files):
    rules = {}
    for gram_file in gram_files:
        gram_path = statements_dir / gram_file
        try:
            parsed_rules = parse_peg_grammar(gram_path.read_text())
        except Exception as e:
            raise Exception(f"{gram_file}: {e}") from None
        for rule_name, rule in parsed_rules.items():
            if rule_name in rules:
                raise Exception(f"duplicate grammar rule '{rule_name}' in {gram_file}")
            rules[rule_name] = rule
    return rules


def identifier_override_rules(grammar_types_file):
    result = set()
    for rule_name, override in load_matcher_rule_overrides(grammar_types_file).items():
        if override.get("matcher") in ("identifier", "reserved_identifier"):
            result.add(rule_name)
    return result


def typed_result_expr(cpp_type, expr, by_value):
    move_expr = expr if by_value else expr
    if by_value:
        move_expr = f"std::move({expr})"
    return f"make_uniq<TypedTransformResult<{cpp_type}>>({move_expr})"


class UseGramPreviewEmitter:
    def __init__(self, rules, rule_types, identifier_rules):
        self.rules = rules
        self.rule_types = rule_types
        self.identifier_rules = identifier_rules

    def cpp_type(self, rule_name):
        return self.rule_types[rule_name].cpp_type

    def by_value(self, rule_name):
        return self.rule_types[rule_name].by_value

    def entrypoint_rules(self):
        return [rule_name for rule_name in self.rules if self.cpp_type(rule_name) == "unique_ptr<SQLStatement>"]

    def emit(self):
        lines = []
        lines.append("// Trampoline transformer generation")
        lines.append("// AUTO-GENERATED by scripts/parser/generate_transformer_trampoline.py")
        lines.append("")
        lines.append("// Header declarations for PEGTransformerFactory:")
        for rule_name in self.entrypoint_rules():
            lines.append(
                f"static unique_ptr<TransformResultValue> Transform{rule_name}TrampolineInternal("
                f"PEGTransformer &transformer, ParseResult &parse_result);"
            )
        for rule_name in self.rules:
            lines.append(
                f"static void {init_name(rule_name)}(PEGTransformer &transformer, TransformStack &stack, "
                f"TransformStackFrame &frame);"
            )
            lines.append(
                f"static unique_ptr<TransformResultValue> {finalize_name(rule_name)}(PEGTransformer &transformer, "
                f"TransformStack &stack, TransformStackFrame &frame);"
            )
        lines.append("")
        lines.append("// Source definitions:")
        for rule_name in self.rules:
            lines.append(
                f"static const TransformFrameOps {ops_name(rule_name)} = "
                f"{{\"{rule_name}\", &PEGTransformerFactory::{init_name(rule_name)}, "
                f"&PEGTransformerFactory::{finalize_name(rule_name)}}};"
            )
        lines.append("")
        lines.extend(self.emit_ops_lookup())
        lines.append("")
        for rule_name, rule in self.rules.items():
            lines.extend(self.emit_rule(rule_name, tokens_to_ast(rule.tokens)))
            lines.append("")
        for rule_name in self.entrypoint_rules():
            lines.extend(self.emit_entrypoint(rule_name))
            lines.append("")
        lines.extend(self.emit_registration())
        return "\n".join(lines)

    def emit_ops_lookup(self):
        lines = []
        lines.append("static const case_insensitive_map_t<const TransformFrameOps *> &GeneratedTrampolineOps() {")
        lines.append("\tstatic const case_insensitive_map_t<const TransformFrameOps *> result = {")
        for rule_name in self.rules:
            lines.append(f"\t    {{\"{rule_name}\", &{ops_name(rule_name)}}},")
        lines.append("\t};")
        lines.append("\treturn result;")
        lines.append("}")
        return lines

    def emit_rule(self, rule_name, ast):
        if isinstance(ast, ChoiceNode):
            return self.emit_choice_rule(rule_name)
        if isinstance(ast, SequenceNode):
            return self.emit_sequence_rule(rule_name, ast)
        if isinstance(ast, ReferenceNode):
            return self.emit_sequence_rule(rule_name, SequenceNode([ast]))
        raise NotImplementedError(f"unsupported preview shape for {rule_name}: {type(ast).__name__}")

    def semantic_children(self, ast):
        result = []
        children = ast.children if isinstance(ast, SequenceNode) else [ast]
        for child_idx, child in enumerate(children):
            if isinstance(child, ReferenceNode) and child.name not in self.identifier_rules:
                result.append((child_idx, child.name, False))
            elif isinstance(child, OptionalNode) and isinstance(child.child, RepeatNode):
                repeat_child = child.child.child
                if isinstance(repeat_child, ReferenceNode) and repeat_child.name not in self.identifier_rules:
                    result.append((child_idx, repeat_child.name, True))
            elif isinstance(child, (LiteralNode, ReferenceNode)):
                continue
            else:
                raise NotImplementedError(f"unsupported semantic child shape: {type(child).__name__}")
        return result

    def direct_identifier_args(self, ast):
        result = []
        children = ast.children if isinstance(ast, SequenceNode) else [ast]
        for child_idx, child in enumerate(children):
            if isinstance(child, ReferenceNode) and child.name in self.identifier_rules:
                var_name = self.identifier_var_name(child.name)
                result.append((var_name, f"list_pr.GetChild({child_idx}).Cast<IdentifierParseResult>().identifier"))
        return result

    def identifier_var_name(self, rule_name):
        words = []
        start = 0
        for idx in range(1, len(rule_name)):
            if rule_name[idx].isupper() and not rule_name[idx - 1].isupper():
                words.append(rule_name[start:idx].lower())
                start = idx
        words.append(rule_name[start:].lower())
        return "_".join(words)

    def emit_choice_rule(self, rule_name):
        cpp_type = self.cpp_type(rule_name)
        by_value = self.by_value(rule_name)
        lines = []
        lines.append(
            f"void PEGTransformerFactory::{init_name(rule_name)}(PEGTransformer &transformer, TransformStack &stack, "
            f"TransformStackFrame &frame) {{"
        )
        lines.append("\tauto &list_pr = frame.parse_result.Cast<ListParseResult>();")
        lines.append("\tauto &choice_pr = list_pr.Child<ChoiceParseResult>(0);")
        lines.append("\tauto &choice_result = choice_pr.GetResult();")
        lines.append("\tframe.ReserveChildSlots(1);")
        lines.append("\tauto &ops_map = GeneratedTrampolineOps();")
        lines.append("\tauto ops_entry = ops_map.find(choice_result.name);")
        lines.append("\tif (ops_entry == ops_map.end()) {")
        lines.append('\t\tthrow InternalException("No trampoline ops registered for rule \'%s\'", choice_result.name);')
        lines.append("\t}")
        lines.append("\tstack.PushFrame(choice_result, *ops_entry->second, frame.frame_index, 0);")
        lines.append("}")
        lines.append("")
        lines.append(
            f"unique_ptr<TransformResultValue> PEGTransformerFactory::{finalize_name(rule_name)}(PEGTransformer &transformer, "
            f"TransformStack &stack, TransformStackFrame &frame) {{"
        )
        lines.append(f"\tauto result = frame.TakeResult<{cpp_type}>(0);")
        lines.append(f"\treturn {typed_result_expr(cpp_type, 'result', by_value)};")
        lines.append("}")
        return lines

    def emit_sequence_rule(self, rule_name, ast):
        semantic_children = self.semantic_children(ast)
        repeat_children = [child for child in semantic_children if child[2]]
        normal_children = [child for child in semantic_children if not child[2]]
        cpp_type = self.cpp_type(rule_name)
        by_value = self.by_value(rule_name)

        lines = []
        lines.append(
            f"void PEGTransformerFactory::{init_name(rule_name)}(PEGTransformer &transformer, TransformStack &stack, "
            f"TransformStackFrame &frame) {{"
        )
        if normal_children or repeat_children:
            lines.append("\tauto &list_pr = frame.parse_result.Cast<ListParseResult>();")
        if repeat_children:
            child_idx, child_rule, _ = repeat_children[0]
            lines.append(f"\tauto &repeat_opt = list_pr.GetChild({child_idx}).Cast<OptionalParseResult>();")
            lines.append("\tif (repeat_opt.HasResult()) {")
            lines.append("\t\tauto &repeat_pr = repeat_opt.GetResult().Cast<RepeatParseResult>();")
            lines.append("\t\tauto &repeat_children = repeat_pr.GetChildren();")
            lines.append(f"\t\tframe.ReserveChildSlots({len(normal_children)} + repeat_children.size());")
            lines.append("\t\tfor (idx_t i = repeat_children.size(); i > 0; i--) {")
            lines.append("\t\t\tauto child_idx = i - 1;")
            lines.append(
                f"\t\t\tstack.PushFrame(repeat_children[child_idx].get(), {ops_name(child_rule)}, "
                f"frame.frame_index, {len(normal_children)} + child_idx);"
            )
            lines.append("\t\t}")
            lines.append("\t} else {")
            lines.append(f"\t\tframe.ReserveChildSlots({len(normal_children)});")
            lines.append("\t}")
        else:
            lines.append(f"\tframe.ReserveChildSlots({len(normal_children)});")
        for slot_idx, (child_idx, child_rule, _) in enumerate(reversed(normal_children)):
            original_slot = len(normal_children) - slot_idx - 1
            lines.append(
                f"\tstack.PushFrame(list_pr.GetChild({child_idx}), {ops_name(child_rule)}, "
                f"frame.frame_index, {original_slot});"
            )
        lines.append("}")
        lines.append("")
        lines.append(
            f"unique_ptr<TransformResultValue> PEGTransformerFactory::{finalize_name(rule_name)}(PEGTransformer &transformer, "
            f"TransformStack &stack, TransformStackFrame &frame) {{"
        )
        direct_identifier_args = self.direct_identifier_args(ast)
        if direct_identifier_args:
            lines.append("\tauto &list_pr = frame.parse_result.Cast<ListParseResult>();")
        for var_name, expr in direct_identifier_args:
            lines.append(f"\tauto {var_name} = {expr};")
        for slot_idx, (_, child_rule, _) in enumerate(normal_children):
            var_name = self.identifier_var_name(child_rule)
            lines.append(f"\tauto {var_name} = frame.TakeResult<{self.cpp_type(child_rule)}>({slot_idx});")
        if repeat_children:
            _, child_rule, _ = repeat_children[0]
            var_name = self.identifier_var_name(child_rule)
            lines.append(f"\toptional<vector<{self.cpp_type(child_rule)}>> {var_name} {{}};")
            lines.append(f"\tif (frame.child_results.size() > {len(normal_children)}) {{")
            lines.append(f"\t\tvector<{self.cpp_type(child_rule)}> {var_name}_value;")
            lines.append(f"\t\tfor (idx_t i = {len(normal_children)}; i < frame.child_results.size(); i++) {{")
            lines.append(f"\t\t\t{var_name}_value.push_back(frame.TakeResult<{self.cpp_type(child_rule)}>(i));")
            lines.append("\t\t}")
            lines.append(f"\t\t{var_name} = std::move({var_name}_value);")
            lines.append("\t}")
        arg_names = [name for name, _ in direct_identifier_args]
        arg_names.extend(self.identifier_var_name(child_rule) for _, child_rule, _ in normal_children)
        arg_names.extend(self.identifier_var_name(child_rule) for _, child_rule, _ in repeat_children)
        lines.append(f"\tauto result = PEGTransformerFactory::Transform{rule_name}(transformer, {', '.join(arg_names)});")
        lines.append(f"\treturn {typed_result_expr(cpp_type, 'result', by_value)};")
        lines.append("}")
        return lines

    def emit_entrypoint(self, rule_name):
        cpp_type = self.cpp_type(rule_name)
        lines = []
        lines.append(
            f"unique_ptr<TransformResultValue> PEGTransformerFactory::Transform{rule_name}TrampolineInternal("
            f"PEGTransformer &transformer, ParseResult &parse_result) {{"
        )
        lines.append("\tTransformStack stack(transformer);")
        lines.append(f"\tauto result = stack.Execute<{cpp_type}>(parse_result, {ops_name(rule_name)});")
        lines.append(f"\treturn {typed_result_expr(cpp_type, 'result', self.by_value(rule_name))};")
        lines.append("}")
        return lines

    def emit_registration(self):
        lines = []
        lines.append("void PEGTransformerFactory::RegisterGeneratedTrampoline() {")
        for rule_name in self.entrypoint_rules():
            lines.append(
                f"\ttrampoline_transform_functions[\"{rule_name}\"] = "
                f"&PEGTransformerFactory::Transform{rule_name}TrampolineInternal;"
            )
        lines.append("}")
        return lines


def main():
    arg_parser = argparse.ArgumentParser(description="Generate trampoline-style transformer wrappers.")
    arg_parser.add_argument("--write", action="store_true", help="Write generated files to disk.")
    arg_parser.add_argument(
        "--grammar",
        action="append",
        default=["use.gram"],
        help="Grammar file to process. Defaults to use.gram. Can be specified multiple times.",
    )
    args = arg_parser.parse_args()

    if args.write:
        raise NotImplementedError("Writing trampoline transformer output is not implemented yet")

    grammar_files = sorted(set(args.grammar))
    rules = load_grammar_rules(grammar_files)
    all_grammar_files = sorted(path.name for path in statements_dir.glob("*.gram"))
    all_rules = load_grammar_rules(all_grammar_files)
    config_file = type_dir / "transformer_trampoline.yml"
    rule_config = load_transformer_trampoline_config(config_file, all_rules.keys())
    grammar_types_file = type_dir / "grammar_types.yml"
    rule_types, _ = load_grammar_types(grammar_types_file)
    identifier_rules = identifier_override_rules(grammar_types_file)

    print(f"// grammar files: {', '.join(grammar_files)}")
    print(f"// rules: {len(rules)}")
    emitter = UseGramPreviewEmitter(rules, rule_types, identifier_rules)
    print(emitter.emit())


if __name__ == "__main__":
    main()
