comment: false
coverage:
  precision: 2
  round: down
  range: "94...100"
  status:
    project:
      default:
        # basic
        # for now
        target: number
        threshold: 0%
         # advanced settings
        if_not_found: failure
        if_ci_failed: failure
        informational: true
        only_pulls: false
    patch:
      default:
        # basic
        target: number
        threshold: 100%
        base: auto
        # advanced
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: true
        paths:
          - "src"