comment: false
coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
         # advanced settings
        if_not_found: success
        if_ci_failed: failure
        informational: true
        only_pulls: false
    patch:
      default:
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: true
        paths:
          - "src"