//===----------------------------------------------------------------------===//
//                         DuckDB
//
// core_functions/aggregate/variant_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct VariantGroupObjectFun {
	static constexpr const char *Name = "variant_group_object";
	static constexpr const char *Parameters = "key,value";
	static constexpr const char *Description = "Returns a VARIANT object containing all key, value pairs in the aggregation.";
	static constexpr const char *Example = "variant_group_object(key, value)";
	static constexpr const char *Categories = "variant";

	static AggregateFunction GetFunction();
};

} // namespace duckdb
