name: 'Set Swap Space'
description: 'Add moar swap'
inputs:
  swap-size-gb:
    description: 'Swap space to create, in Gigabytes.'
    required: false
    default: '8'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "$RUNNER_OS" != "Linux" ]]; then
          echo "Skipping swap setup: not a Linux runner ($RUNNER_OS)"
          exit 0
        fi

    - uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: ${{ inputs.swap-size-gb }}
