if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "IN_TREE")
    duckdb_extension_load(json)
    duckdb_extension_statically_link(json)
    duckdb_extension_load(parquet)
    duckdb_extension_statically_link(parquet)
endif()

if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "OUT_OF_TREE")
    include("${EXTENSION_CONFIG_BASE_DIR}/aws.cmake")
    duckdb_extension_statically_link(aws)
    include("${EXTENSION_CONFIG_BASE_DIR}/azure.cmake")
    duckdb_extension_statically_link(azure)
    include("${EXTENSION_CONFIG_BASE_DIR}/ducklake.cmake")
    duckdb_extension_statically_link(ducklake)
    include("${EXTENSION_CONFIG_BASE_DIR}/httpfs.cmake")
    duckdb_extension_statically_link(httpfs)
    include("${EXTENSION_CONFIG_BASE_DIR}/iceberg.cmake")
    duckdb_extension_statically_link(iceberg)
endif()
