if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "IN_TREE")
    duckdb_extension_load(json)
    duckdb_extension_load(parquet)
endif()

if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "OUT_OF_TREE")
    include("${EXTENSION_CONFIG_BASE_DIR}/aws.cmake")
    include("${EXTENSION_CONFIG_BASE_DIR}/azure.cmake")
    include("${EXTENSION_CONFIG_BASE_DIR}/ducklake.cmake")
    include("${EXTENSION_CONFIG_BASE_DIR}/httpfs.cmake")
    include("${EXTENSION_CONFIG_BASE_DIR}/iceberg.cmake")
endif()
