if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "IN_TREE")
    duckdb_extension_load(autocomplete)
    duckdb_extension_statically_link(autocomplete)
    duckdb_extension_load(core_functions)
    duckdb_extension_statically_link(core_functions)
    duckdb_extension_load(icu)
    duckdb_extension_statically_link(icu)
    duckdb_extension_load(tpcds)
    duckdb_extension_statically_link(tpcds)
    duckdb_extension_load(tpch)
    duckdb_extension_statically_link(tpch)

    # Test extension for the upcoming C CAPI extensions
    duckdb_extension_load(demo_capi)
endif()

if (NOT DEFINED DUCKDB_MAIN_EXTENSION_CONFIG_TYPE OR DUCKDB_MAIN_EXTENSION_CONFIG_TYPE STREQUAL "OUT_OF_TREE")
    include("${EXTENSION_CONFIG_BASE_DIR}/avro.cmake")
    duckdb_extension_statically_link(avro)
    include("${EXTENSION_CONFIG_BASE_DIR}/excel.cmake")
    duckdb_extension_statically_link(excel)
    include("${EXTENSION_CONFIG_BASE_DIR}/inet.cmake")
    duckdb_extension_statically_link(inet)
    include("${EXTENSION_CONFIG_BASE_DIR}/quack.cmake")
    duckdb_extension_statically_link(quack)
    include("${EXTENSION_CONFIG_BASE_DIR}/sqlsmith.cmake")
endif()
