blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/duckdb/duckdb/discussions/new?category=ideas
    about: Submit feature requests here
  - name: Discussions
    url: https://github.com/duckdb/duckdb/discussions
    about: Please ask and answer general questions here.
