# Generated by cpp11: do not edit by hand

rapi_connect <- function(db) {
  .Call(`_duckdb_rapi_connect`, db)
}

rapi_disconnect <- function(conn) {
  invisible(.Call(`_duckdb_rapi_disconnect`, conn))
}

rapi_startup <- function(dbdir, readonly, configsexp) {
  .Call(`_duckdb_rapi_startup`, dbdir, readonly, configsexp)
}

rapi_shutdown <- function(dbsexp) {
  invisible(.Call(`_duckdb_rapi_shutdown`, dbsexp))
}

rapi_register_df <- function(conn, name, value) {
  invisible(.Call(`_duckdb_rapi_register_df`, conn, name, value))
}

rapi_unregister_df <- function(conn, name) {
  invisible(.Call(`_duckdb_rapi_unregister_df`, conn, name))
}

rapi_register_arrow <- function(conn, name, export_funs, valuesexp) {
  invisible(.Call(`_duckdb_rapi_register_arrow`, conn, name, export_funs, valuesexp))
}

rapi_unregister_arrow <- function(conn, name) {
  invisible(.Call(`_duckdb_rapi_unregister_arrow`, conn, name))
}

expr_reference_cpp <- function(ref) {
  .Call(`_duckdb_expr_reference_cpp`, ref)
}

expr_constant_cpp <- function(val) {
  .Call(`_duckdb_expr_constant_cpp`, val)
}

expr_function_cpp <- function(name, args) {
  .Call(`_duckdb_expr_function_cpp`, name, args)
}

expr_tostring_cpp <- function(expr) {
  .Call(`_duckdb_expr_tostring_cpp`, expr)
}

rel_from_df_cpp <- function(con, df) {
  .Call(`_duckdb_rel_from_df_cpp`, con, df)
}

rel_filter_cpp <- function(rel, exprs) {
  .Call(`_duckdb_rel_filter_cpp`, rel, exprs)
}

rel_project_cpp <- function(rel, exprs) {
  .Call(`_duckdb_rel_project_cpp`, rel, exprs)
}

rel_aggregate_cpp <- function(rel, groups, aggregates) {
  .Call(`_duckdb_rel_aggregate_cpp`, rel, groups, aggregates)
}

rel_order_cpp <- function(rel, orders) {
  .Call(`_duckdb_rel_order_cpp`, rel, orders)
}

rel_to_df_cpp <- function(rel) {
  .Call(`_duckdb_rel_to_df_cpp`, rel)
}

rel_tostring_cpp <- function(rel) {
  .Call(`_duckdb_rel_tostring_cpp`, rel)
}

rel_explain_cpp <- function(rel) {
  .Call(`_duckdb_rel_explain_cpp`, rel)
}

rel_sql_cpp <- function(rel, sql) {
  .Call(`_duckdb_rel_sql_cpp`, rel, sql)
}

rel_names_cpp <- function(rel) {
  .Call(`_duckdb_rel_names_cpp`, rel)
}

rapi_release <- function(stmt) {
  invisible(.Call(`_duckdb_rapi_release`, stmt))
}

rapi_prepare <- function(conn, query) {
  .Call(`_duckdb_rapi_prepare`, conn, query)
}

rapi_bind <- function(stmt, params, arrow) {
  .Call(`_duckdb_rapi_bind`, stmt, params, arrow)
}

rapi_execute_arrow <- function(qry_res, stream, vec_per_chunk, return_table) {
  .Call(`_duckdb_rapi_execute_arrow`, qry_res, stream, vec_per_chunk, return_table)
}

rapi_record_batch <- function(qry_res, approx_batch_size) {
  .Call(`_duckdb_rapi_record_batch`, qry_res, approx_batch_size)
}

rapi_execute <- function(stmt, arrow) {
  .Call(`_duckdb_rapi_execute`, stmt, arrow)
}

rapi_ptr_to_str <- function(extptr) {
  .Call(`_duckdb_rapi_ptr_to_str`, extptr)
}
