# Generated by cpp11: do not edit by hand

rapi_connect <- function(db) {
  .Call(`_duckdb_rapi_connect`, db)
}

rapi_disconnect <- function(conn) {
  invisible(.Call(`_duckdb_rapi_disconnect`, conn))
}

rapi_startup <- function(dbdir, readonly, configsexp) {
  .Call(`_duckdb_rapi_startup`, dbdir, readonly, configsexp)
}

rapi_shutdown <- function(dbsexp) {
  invisible(.Call(`_duckdb_rapi_shutdown`, dbsexp))
}

bind_R <- function(stmtsexp, paramsexp, arrowsexp) {
  .Call(`_duckdb_bind_R`, stmtsexp, paramsexp, arrowsexp)
}

execute_R <- function(stmtsexp, arrowsexp) {
  .Call(`_duckdb_execute_R`, stmtsexp, arrowsexp)
}

fetch_arrow_R <- function(query_resultsexp, streamsexp, vector_per_chunksexp, return_tablesexp) {
  .Call(`_duckdb_fetch_arrow_R`, query_resultsexp, streamsexp, vector_per_chunksexp, return_tablesexp)
}

fetch_record_batch_R <- function(query_resultsexp, approx_batch_sizeexp) {
  .Call(`_duckdb_fetch_record_batch_R`, query_resultsexp, approx_batch_sizeexp)
}

register_arrow_R <- function(connsexp, namesexp, export_funsexp, valuesexp) {
  invisible(.Call(`_duckdb_register_arrow_R`, connsexp, namesexp, export_funsexp, valuesexp))
}

unregister_arrow_R <- function(connsexp, namesexp) {
  invisible(.Call(`_duckdb_unregister_arrow_R`, connsexp, namesexp))
}

ptr_to_str <- function(extptr) {
  .Call(`_duckdb_ptr_to_str`, extptr)
}

rapi_register_df <- function(conn, name, value) {
  invisible(.Call(`_duckdb_rapi_register_df`, conn, name, value))
}

rapi_unregister_df <- function(conn, name) {
  invisible(.Call(`_duckdb_rapi_unregister_df`, conn, name))
}

rapi_release <- function(stmt) {
  invisible(.Call(`_duckdb_rapi_release`, stmt))
}

rapi_prepare <- function(conn, query) {
  .Call(`_duckdb_rapi_prepare`, conn, query)
}
