INSERT INTO main.lineitem
    VALUES (64, 15, 44, 89, 64, CAST(NULL AS DECIMAL), CAST(NULL AS DECIMAL), DEFAULT, CAST(coalesce(CAST(NULL AS VARCHAR), CAST(nullif (CAST(NULL AS VARCHAR), CAST(NULL AS VARCHAR)) AS VARCHAR)) AS VARCHAR), DEFAULT, CAST(NULL AS DATE), DEFAULT, CAST(NULL AS DATE), CASE WHEN 45 IS NULL THEN
            CAST(NULL AS VARCHAR)
        ELSE
            CAST(NULL AS VARCHAR)
        END, CAST(NULL AS VARCHAR), DEFAULT)
