INSERT INTO main.customer
    VALUES (38, DEFAULT, CAST(nullif (CAST(NULL AS VARCHAR), CAST(NULL AS VARCHAR)) AS VARCHAR), CAST(nullif (58, 26) AS INTEGER), DEFAULT, DEFAULT, CAST(NULL AS VARCHAR), DEFAULT)
