INSERT INTO main.orders
    VALUES (10, CAST(nullif (73, 20) AS INTEGER), DEFAULT, DEFAULT, CAST(NULL AS DATE), CAST(coalesce(CAST(NULL AS VARCHAR), CAST(NULL AS VARCHAR)) AS VARCHAR), CAST(NULL AS VARCHAR), 27, CAST(NULL AS VARCHAR))
