name: "Setup manylinux2014 image"
description: "Installs/configures additional CI dependencies"
inputs:
  aws-cli:
    description: 'Setup aws-cli'
    default: 0
  ninja-build:
    description: 'Setup ninja-build'
    default: 0
  vcpkg:
    description: 'Setup vcpkg (installs to $GITHUB_WORKSPACE/vcpkg)'
    default: 0
  openssl:
    description: 'Setup OpenSSL (requires vcpkg to also be installed)'
    default: 0
  ccache:
    description: 'Setup Ccache'
    default: 0
  jdk:
    description: 'Setup JDK'
    default: 0
  odbc:
    description: 'Setup ODBC'
    default: 0
  ssh:
    description: 'Setup SSH'
    default: 0
  glibc32:
    description: 'Setup 32bit glibc'
    default: 0
  nodejs:
    description: 'Setup NodeJS'
    default: 0
  gcc_4_8:
    description: 'Setup GCC 4.8 (installs to /usr/bin/g++, default will still be GCC 10)'
    default: 0
  python_alias:
    description: 'Create an alias for python3 to python3.9'
    default: 0

runs:
  using: "composite"
  steps:
    - name: Setup general dependencies
      shell: bash
      run: scripts/setup_manylinux2014.sh general

    - name: Install AWS CLI
      if: ${{ inputs.aws-cli == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh aws-cli

    - name: Setup dependencies for ODBC
      if: ${{ inputs.odbc == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh odbc

    - name: Setup dependencies for ccache
      if: ${{ inputs.ccache == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh ccache

    - name: Setup JDK
      if: ${{ inputs.jdk == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh jdk

    - name: Setup SSH
      if: ${{ inputs.ssh == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh ssh

    - name: Setup NodeJS
      if: ${{ inputs.nodejs == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh nodejs

    - name: Setup 32bit compiler
      if: ${{ inputs.glibc32 == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh glibc32

    - name: Setup python3 as python3.9
      if: ${{ inputs.python_alias == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh python_alias

    - name: Setup old (GCC 4.8) compiler
      if: ${{ inputs.gcc_4_8 == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh gcc_4_8

    # Note instead of using scripts/setup_manylinux2014.sh vcpkg, we prefer to use
    # lukka/run-vcpkg@v11.1 here as it configures vcpkg to cache to GH actions.
    - name: Setup vcpkg
      if: ${{ inputs.vcpkg == 1 }}
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1

    - name: Install OpenSSL
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: scripts/setup_manylinux2014.sh openssl

    - name: Setup Ccache
      if: ${{ inputs.ccache == 1 }}
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}