
#include "planner/operator/logical_aggregate.hpp"
#include "planner/operator/logical_copy.hpp"
#include "planner/operator/logical_cross_product.hpp"
#include "planner/operator/logical_explain.hpp"
#include "planner/operator/logical_filter.hpp"
#include "planner/operator/logical_get.hpp"
#include "planner/operator/logical_insert.hpp"
#include "planner/operator/logical_join.hpp"
#include "planner/operator/logical_limit.hpp"
#include "planner/operator/logical_order.hpp"
#include "planner/operator/logical_projection.hpp"
