name: "Setup Ubuntu 18"
description: "Setup an Ubuntu 18 docker container with the required libraries"
inputs:
  openssl:
    description: 'OpenSSL'
    default: 0
  python:
    description: 'Python'
    default: 1
  aarch64_cross_compile:
    description: 'Install dependencies for aarch64 cross-compiling'
    default: 0
  vcpkg:
    description: 'Install vcpkg'
    default: 0
  ccache:
    description: 'Install ccache'
    default: 0

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        apt-get update -y -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update -y -qq
        apt-get install -y -qq ninja-build make gcc-multilib g++-multilib libssl-dev wget openjdk-8-jdk zip maven unixodbc-dev libc6-dev-i386 lib32readline6-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip build-essential checkinstall libffi-dev curl libz-dev openssh-client pkg-config

    - name: Install
      shell: bash
      if: ${{ inputs.aarch64_cross_compile == 1 }}
      run: |
        apt-get install -y -qq gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Install Git 2.18.5
      shell: bash
      run: |
        wget https://github.com/git/git/archive/refs/tags/v2.18.5.tar.gz
        tar xvf v2.18.5.tar.gz
        cd git-2.18.5
        make
        make prefix=/usr install
        git --version

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake 3.21
      shell: bash
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.sh
        chmod +x cmake-3.21.3-linux-x86_64.sh
        ./cmake-3.21.3-linux-x86_64.sh --skip-license --prefix=/usr/local
        cmake --version

    - name: Install Python 3.8
      if: ${{ inputs.python }} == 1
      shell: bash
      run: |
        wget https://www.python.org/ftp/python/3.8.17/Python-3.8.17.tgz
        tar xvf Python-3.8.17.tgz
        cd Python-3.8.17
        mkdir -p pythonbin
        ./configure --with-ensurepip=install
        make -j
        make install
        python3.8 --version
        python3.8 -m pip install pip
        python3.8 -m pip install requests awscli

    - name: Version Check
      shell: bash
      run: |
        ldd --version ldd
        python3 --version
        git --version
        git log -1 --format=%h

    - name: Setup vcpkg
      if: ${{ inputs.vcpkg == 1 }}
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1

    - name: Setup Ccache
      if: ${{ inputs.ccache == 1 }}
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

    - name: Instal OpenSSL through vcpkg
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: |
        cd $VCPKG_ROOT && ./vcpkg install openssl --triplet=${{ inputs.aarch64_cross_compile == 1 && 'arm64-linux' || 'x64-linux' }}