#!/usr/bin/env python3
"""
Generate metrics.hpp (struct definitions) and metrics_manager.cpp (static array +
MetricsManager method implementations) from src/common/metrics.json.

The "optimizer.*" metrics are NOT in the JSON — they are generated at runtime from
the OptimizerType enum and the corresponding code is emitted into metrics_manager.cpp.
"""

import json
import os

METRICS_JSON = "src/common/metrics.json"
OUTPUT_HEADER = "src/include/duckdb/main/metrics.hpp"
OUTPUT_SOURCE = "src/main/metrics_manager.cpp"

CPP_TYPE_MAP = {
    "double": "double",
    "uint64": "uint64_t",
    "string": "string",
    "map": "Value",
}

# Preserve JSON insertion order so the generated files are deterministic.
GROUP_ORDER = [
    "query",
    "system",
    "io",
    "storage",
    "operator",
    "optimizers",
    "parsers",
    "planner",
    "physical_planner",
]


def to_pascal_case(s: str) -> str:
    """'physical_planner.total_time' -> 'PhysicalPlannerTotalTime'"""
    return "".join(p.capitalize() for p in s.replace(".", "_").split("_"))


def iter_metrics(data: dict):
    """Yield (group, metric_name, metric_info) in a stable order."""
    for group in GROUP_ORDER:
        if group not in data:
            continue
        for metric_name in sorted(data[group].keys()):
            yield group, metric_name, data[group][metric_name]
    # Any groups not explicitly listed — emit them sorted for stability.
    for group in sorted(data.keys()):
        if group in GROUP_ORDER:
            continue
        for metric_name in sorted(data[group].keys()):
            yield group, metric_name, data[group][metric_name]


def generate_header(data: dict) -> str:
    lines = []
    lines += [
        "//===----------------------------------------------------------------------===//",
        "//",
        "//                         DuckDB",
        "//",
        "// duckdb/main/metrics.hpp",
        "//",
        "// This file is automatically generated by scripts/generate_metrics.py",
        "// Do not edit this file manually, your changes will be overwritten",
        "//===----------------------------------------------------------------------===//",
        "",
        "#pragma once",
        "",
        '#include "duckdb/common/types/value.hpp"',
        "",
        "namespace duckdb {",
        "",
    ]

    current_group = None
    for group, metric_name, info in iter_metrics(data):
        full_name = f"{group}.{metric_name}"
        struct_name = to_pascal_case(full_name)
        cpp_type = CPP_TYPE_MAP[info["metric_type"]]
        description = info["description"].replace('"', '\\"')
        unit = info.get("unit", "").replace('"', '\\"')

        if group != current_group:
            if current_group is not None:
                lines.append("")
            lines.append(f"// {group.replace('_', ' ').title()} metrics")
            current_group = group

        lines += [
            f"struct {struct_name} {{",
            f"\tusing METRIC_TYPE = {cpp_type};",
            f'\tstatic constexpr const char *Name = "{full_name}";',
            f'\tstatic constexpr const char *Description = "{description}";',
            f'\tstatic constexpr const char *Unit = "{unit}";',
            f'\tstatic constexpr const char *TypeStr = "{info["metric_type"]}";',
            "};",
        ]

    lines += [
        "",
        "} // namespace duckdb",
        "",
    ]
    return "\n".join(lines)


def generate_source(data: dict) -> str:
    lines = []
    lines += [
        "// This file is automatically generated by scripts/generate_metrics.py",
        "// Do not edit this file manually, your changes will be overwritten",
        "",
        '#include "duckdb/main/metrics_manager.hpp"',
        '#include "duckdb/main/metrics.hpp"',
        '#include "duckdb/main/database.hpp"',
        '#include "duckdb/main/client_context.hpp"',
        '#include "duckdb/common/enums/optimizer_type.hpp"',
        '#include "duckdb/common/string_util.hpp"',
        '#include "duckdb/common/enum_util.hpp"',
        "",
        "namespace duckdb {",
        "",
        "namespace {",
        "",
        "struct MetricDescriptor {",
        "\tconst char *name;",
        "\tconst char *metric_type;",
        "\tconst char *description;",
        "\tconst char *unit;",
        "};",
        "",
        "} // namespace",
        "",
        "// clang-format off",
        "#define DUCKDB_METRIC(METRIC) \\",
        "\t{METRIC::Name, METRIC::TypeStr, METRIC::Description, METRIC::Unit}",
        "#define FINAL_METRIC \\",
        "\t{nullptr, nullptr, nullptr, nullptr}",
        "",
        "static const MetricDescriptor internal_metrics[] = {",
    ]

    for group, metric_name, _ in iter_metrics(data):
        struct_name = to_pascal_case(f"{group}.{metric_name}")
        lines.append(f"\tDUCKDB_METRIC({struct_name}),")

    lines += [
        "\tFINAL_METRIC,",
        "};",
        "// clang-format on",
        "",
        "#undef DUCKDB_METRIC",
        "#undef FINAL_METRIC",
        "",
    ]

    # MetricsManager method implementations
    lines += [
        "MetricsManager &MetricsManager::Get(ClientContext &context) {",
        "\treturn DatabaseInstance::GetDatabase(context).GetMetricsManager();",
        "}",
        "",
        "MetricsManager &MetricsManager::Get(DatabaseInstance &db) {",
        "\treturn db.GetMetricsManager();",
        "}",
        "",
        "idx_t MetricsManager::GetMetricCount() const {",
        "\tidx_t count = sizeof(internal_metrics) / sizeof(MetricDescriptor) - 1;",
        "\tcount += static_cast<idx_t>(OptimizerType::PARTIAL_AGGREGATE_PUSHDOWN) -",
        "\t         static_cast<idx_t>(OptimizerType::EXPRESSION_REWRITER) + 1;",
        "\treturn count;",
        "}",
        "",
        "vector<MetricsManager::MetricInfo> MetricsManager::GetAllMetrics() const {",
        "\tvector<MetricInfo> result;",
        "\tresult.reserve(GetMetricCount());",
        "\tfor (idx_t i = 0; internal_metrics[i].name; i++) {",
        "\t\tMetricInfo info;",
        "\t\tinfo.name = internal_metrics[i].name;",
        "\t\tinfo.metric_type = internal_metrics[i].metric_type;",
        "\t\tinfo.description = internal_metrics[i].description;",
        "\t\tinfo.unit = internal_metrics[i].unit;",
        "\t\tresult.push_back(std::move(info));",
        "\t}",
        "\t// Optimizer metrics are generated at runtime from the OptimizerType enum.",
        "\tfor (auto opt = static_cast<uint32_t>(OptimizerType::EXPRESSION_REWRITER);",
        "\t     opt <= static_cast<uint32_t>(OptimizerType::PARTIAL_AGGREGATE_PUSHDOWN); opt++) {",
        "\t\tauto opt_type = static_cast<OptimizerType>(opt);",
        "\t\tstring opt_name = StringUtil::Lower(EnumUtil::ToString(opt_type));",
        "\t\tMetricInfo info;",
        '\t\tinfo.name = "optimizer." + opt_name;',
        '\t\tinfo.metric_type = "double";',
        '\t\tinfo.description = "Time spent in the " + opt_name + " optimizer";',
        '\t\tinfo.unit = "seconds";',
        "\t\tresult.push_back(std::move(info));",
        "\t}",
        "\treturn result;",
        "}",
        "",
        "} // namespace duckdb",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)

    with open(os.path.join(repo_root, METRICS_JSON), "r") as fh:
        data = json.load(fh)

    header = generate_header(data)
    source = generate_source(data)

    with open(os.path.join(repo_root, OUTPUT_HEADER), "w") as fh:
        fh.write(header)

    with open(os.path.join(repo_root, OUTPUT_SOURCE), "w") as fh:
        fh.write(source)

    total = sum(len(v) for v in data.values())
    print(f"- Generated {total} static metric(s) into {OUTPUT_HEADER} and {OUTPUT_SOURCE}")
    print("  (optimizer.* metrics are emitted as runtime-generated entries)")


if __name__ == "__main__":
    main()
