#!/usr/bin/env python3
# Writes a C++ source that registers the named statically built extensions. Each extension archive carries a root,
# duckdb_extension_<name>_root, describing the extension; the generated source calls every root through
# duckdb_register_static_extension before main, which also pulls the extensions out of their archives. A named
# extension whose archive is missing fails the link.
#
#   LINK_EXTENSIONS="parquet;json" make static_extension_loader     (or: python3 scripts/generate_static_extension_loader.py -o static_extension_loader.cpp parquet json)
#   c++ -I duckdb/include main.cpp static_extension_loader.cpp libparquet_extension.a libjson_extension.a libduckdb_static.a
import argparse
import os
import re
import sys


def parse_names(values):
    names = []
    for value in values:
        for name in re.split(r'[;\s]+', value):
            if not name:
                continue
            if not re.fullmatch(r'[a-z0-9_]+', name):
                sys.exit(f'invalid extension name: {name!r}')
            if name not in names:
                names.append(name)
    return names


TEMPLATE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..', 'extension', 'loader', 'static_extension_loader.cpp.in'
)


def generate(names):
    # mirrors duckdb_write_static_extension_loader in extension/extension_build_tools.cmake, which renders the same template
    roots = [f'duckdb_extension_{name}_root' for name in names]
    if not roots:
        return (
            '// Generated by scripts/generate_static_extension_loader.py. Do not edit.\n'
            '// Registers no extensions.\n'
        )
    values = {
        'LINK_EXTENSION_LIST': ' '.join(names),
        'ROOT_DECLARATIONS': '\n'.join(f'int32_t {root}(duckdb_extension_descriptor *descriptor);' for root in roots),
        'ROOT_REGISTRATIONS': '\n'.join(f'\t\tduckdb_register_static_extension({root});' for root in roots),
    }
    with open(TEMPLATE) as f:
        content = f.read()
    for key, value in values.items():
        content = content.replace(f'@{key}@', value)
    return content


def main():
    parser = argparse.ArgumentParser(
        description='Generate a C++ source that registers the named static DuckDB extensions.'
    )
    parser.add_argument('extensions', nargs='*', help='extension names, separated by spaces or semicolons')
    parser.add_argument('--output', '-o', default='-', help='file to write, or - for stdout (default)')
    args = parser.parse_args()
    content = generate(parse_names(args.extensions))
    if args.output == '-':
        sys.stdout.write(content)
    else:
        with open(args.output, 'w') as f:
            f.write(content)


if __name__ == '__main__':
    main()
