version: '3.3'
services:
  minio:
    image: minio/minio:RELEASE.2021-11-03T03-36-36Z
    hostname: duckdb-minio.com
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /tmp/minio_test_data:/data
      - /tmp/minio_root_data:/root/.minio
    environment:
      - MINIO_ROOT_USER=duckdb_minio_admin
      - MINIO_ROOT_PASSWORD=duckdb_minio_admin_password
      - MINIO_REGION_NAME=eu-west-1
      - MINIO_DOMAIN=duckdb-minio.com
      - MINIO_ACCESS_KEY=duckdb_minio_admin
      - MINIO_SECRET_KEY=duckdb_minio_admin_password
    command: server /data --console-address ":9001"

  minio_setup:
    image: minio/mc:RELEASE.2021-11-05T10-05-06Z
    depends_on:
      - minio
    links:
      - minio
    volumes:
      - ${PWD}/data:/duckdb/data

    entrypoint: >
      /bin/sh -c "
        until (
          /usr/bin/mc config host add myminio http://duckdb-minio.com:9000 duckdb_minio_admin duckdb_minio_admin_password
        ) do
          echo '...waiting...' && sleep 1;
        done;

        /usr/bin/mc admin user add myminio minio_duckdb_user minio_duckdb_user_password
        /usr/bin/mc admin user list myminio
        /usr/bin/mc admin user info myminio minio_duckdb_user
        /usr/bin/mc admin policy set myminio readwrite user=minio_duckdb_user

        /usr/bin/mc admin user add myminio minio_duckdb_user_2 minio_duckdb_user_2_password
        /usr/bin/mc admin user list myminio
        /usr/bin/mc admin user info myminio minio_duckdb_user_2
        /usr/bin/mc admin policy set myminio readwrite user=minio_duckdb_user_2

        /usr/bin/mc rb --force myminio/test-bucket
        /usr/bin/mc mb myminio/test-bucket
        /usr/bin/mc policy get myminio/test-bucket

        /usr/bin/mc rb --force myminio/test-bucket-2
        /usr/bin/mc mb myminio/test-bucket-2
        /usr/bin/mc policy get myminio/test-bucket-2

        /usr/bin/mc rb --force myminio/test-bucket-public
        /usr/bin/mc mb myminio/test-bucket-public
        /usr/bin/mc policy set download myminio/test-bucket-public
        /usr/bin/mc policy get myminio/test-bucket-public

        # This is for the test of presigned URLs
        # !!! When missing, be sure that you have ran 'scripts/generate_presigned_url.sh' !!!

        # small file upload
        /usr/bin/mc cp /duckdb/data/csv/phonenumbers.csv myminio/test-bucket/presigned/phonenumbers.csv
        /usr/bin/mc cp /duckdb/data/parquet-testing/glob/t1.parquet myminio/test-bucket/presigned/t1.parquet

        # large file upload
        /usr/bin/mc cp /duckdb/data/parquet-testing/presigned/presigned-url-lineitem.parquet myminio/test-bucket/presigned/lineitem_large.parquet

        # Upload the db for the attach 
        /usr/bin/mc cp /duckdb/data/attach_test/attach.db myminio/test-bucket/presigned/attach.db
        /usr/bin/mc cp /duckdb/data/attach_test/lineitem_sf1.db myminio/test-bucket/presigned/lineitem_sf1.db
    
        /usr/bin/mc share download myminio/test-bucket/presigned/phonenumbers.csv
        /usr/bin/mc share download myminio/test-bucket/presigned/t1.parquet
        /usr/bin/mc share download myminio/test-bucket/presigned/lineitem_large.parquet
        /usr/bin/mc share download myminio/test-bucket/presigned/attach.db

        exit 0;
      "