package org.duckdb;

public enum DuckDBColumnType {
	BOOLEAN, TINYINT, SMALLINT, INTEGER, BIGINT, UTINYINT, USMALLINT, UINTEGER, UBIGINT, HUGEINT, FLOAT, DOUBLE,
	DECIMAL, VARCHAR, BLOB, TIME, DATE, TIMESTAMP, TIMESTAMP_WITH_TIMEZONE, INTERVAL, LIST, STRUCT
}
