import argparse
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path

parser = argparse.ArgumentParser(description='Inline the auto-complete PEG grammar files')
parser.add_argument(
    '--print', action='store_true', help='Print the grammar instead of writing to a file', default=False
)
parser.add_argument(
    '--grammar-file',
    action='store_true',
    help='Write the grammar to a .gram file instead of a C++ header',
    default=False,
)

args = parser.parse_args()

autocomplete_dir = Path(__file__).parent
statements_dir = autocomplete_dir / 'grammar' / 'statements'
keywords_dir = autocomplete_dir / 'grammar' / 'keywords'
target_file = autocomplete_dir / 'include' / 'inlined_grammar.hpp'

contents = ""

IMPLICIT_RULES = {'%whitespace'}

# Maps filenames to string categories
FILENAME_TO_CATEGORY = {
    "reserved_keyword.list": "RESERVED_KEYWORD",
    "unreserved_keyword.list": "UNRESERVED_KEYWORD",
    "column_name_keyword.list": "COL_NAME_KEYWORD",
    "func_name_keyword.list": "TYPE_FUNC_NAME_KEYWORD",
    "type_name_keyword.list": "TYPE_FUNC_NAME_KEYWORD",
}

# Maps category names to their C++ map variable names
CPP_MAP_NAMES = {
    "RESERVED_KEYWORD": "reserved_keyword_map",
    "UNRESERVED_KEYWORD": "unreserved_keyword_map",
    "COL_NAME_KEYWORD": "colname_keyword_map",
    "TYPE_FUNC_NAME_KEYWORD": "typefunc_keyword_map",
}

# Use a dictionary of sets to collect keywords for each category, preventing duplicates
keyword_sets = {category: set() for category in CPP_MAP_NAMES}

# --- Validation and Loading (largely unchanged) ---
# For validation during the loading phase
reserved_set = set()
unreserved_set = set()


def load_keywords(path):
    with open(path, "r") as f:
        return [line.strip().lower() for line in f if line.strip()]


for filepath in keywords_dir.iterdir():
    if filepath.name not in FILENAME_TO_CATEGORY:
        continue

    category = FILENAME_TO_CATEGORY[filepath.name]
    keywords = load_keywords(filepath)

    for kw in keywords:
        # Validation logic remains the same to enforce rules
        if category == "RESERVED_KEYWORD":
            if kw in reserved_set or kw in unreserved_set:
                print(f"Keyword '{kw}' has conflicting RESERVED/UNRESERVED categories")
                exit(1)
            reserved_set.add(kw)
        elif category == "UNRESERVED_KEYWORD":
            if kw in reserved_set or kw in unreserved_set:
                print(f"Keyword '{kw}' has conflicting RESERVED/UNRESERVED categories")
                exit(1)
            unreserved_set.add(kw)

        # Add the keyword to the appropriate set
        keyword_sets[category].add(kw)


def write_keyword_map():
    # --- C++ Code Generation ---
    output_path = autocomplete_dir / "keyword_map.cpp"
    with open(output_path, "w") as f:
        f.write("/* THIS FILE WAS AUTOMATICALLY GENERATED BY inline_grammar.py */\n")
        f.write("#include \"keyword_helper.hpp\"\n\n")
        f.write("namespace duckdb {\n")
        f.write("void PEGKeywordHelper::InitializeKeywordMaps() { // Renamed for clarity\n")
        f.write("\tif (initialized) {\n\t\treturn;\n\t};\n")
        f.write("\tinitialized = true;\n\n")

        # Get the total number of categories to handle the last item differently
        num_categories = len(keyword_sets)

        # Iterate through each category and generate code for each map
        for i, (category, keywords) in enumerate(keyword_sets.items()):
            cpp_map_name = CPP_MAP_NAMES[category]
            f.write(f"\t// Populating {cpp_map_name}\n")
            # Sort keywords for deterministic output
            for kw in sorted(keywords):
                # Populate the C++ set with insert
                f.write(f'\t{cpp_map_name}.insert("{kw}");\n')

            # Add a newline for all but the last block
            if i < num_categories - 1:
                f.write("\n")
        f.write("}\n")
        f.write("} // namespace duckdb\n")

    print(f"Successfully generated {output_path}")


def filename_to_upper_camel(path):
    parts = path.stem.split('_')
    return ''.join(p.capitalize() for p in parts)


class PEGTokenType(Enum):
    LITERAL = auto()
    REFERENCE = auto()
    FUNCTION_CALL = auto()
    REGEX = auto()
    OPERATOR = auto()


class PEGGrammarRule:
    def __init__(self):
        self.rule_name = None
        self.tokens = []
        self.parameters = {}

    def has_tokens(self):
        return bool(self.tokens)

    def clear(self):
        self.tokens = []
        self.parameters = {}

    def references(self):
        return [t.text for t in self.tokens if t.type in (PEGTokenType.REFERENCE, PEGTokenType.FUNCTION_CALL)]


class ParseState(Enum):
    RULE_NAME = auto()
    RULE_SEPARATOR = auto()
    RULE_DEFINITION = auto()


@dataclass
class PEGToken:
    text: str
    type: PEGTokenType


@dataclass
class ParseLocation:
    line: int
    col: int
    line_text: str

    def raise_error(self, message):
        pointer = ' ' * (self.col - 1) + '^'
        raise Exception(f"{self.line}:{self.col}: {message}\n  {self.line_text}\n  {pointer}")


def character_is_newline(c):
    return c in '\n\r'


def character_is_space(c):
    return c.isspace()


def get_parse_location(contents, pos):
    lines = contents[:pos].split('\n')
    line_num = len(lines)
    col = len(lines[-1]) + 1
    line_text = contents.split('\n')[line_num - 1]
    return ParseLocation(line=line_num, col=col, line_text=line_text)


def update_rules(rules, new_rules, filename):
    for rule_name, rule in new_rules.items():
        if rule_name in rules:
            raise Exception(f"duplicate rule '{rule_name}' (already defined in another file)")
        rules[rule_name] = rule


def parse_peg_grammar(contents):
    rules = {}

    current_rule = PEGGrammarRule()
    current_rule_name = None
    c = 0
    in_or_clause = False
    bracket_count = 0
    parse_state = ParseState.RULE_NAME

    while c < len(contents):
        if contents[c] == "#":
            while c < len(contents) and not character_is_newline(contents[c]):
                c += 1
            continue
        if (
            parse_state == ParseState.RULE_DEFINITION
            and character_is_newline(contents[c])
            and bracket_count == 0
            and not in_or_clause
            and current_rule.has_tokens()
        ):
            current_rule.rule_name = current_rule_name
            if current_rule_name in rules:
                get_parse_location(contents, c).raise_error(f"Duplicate rule name '{current_rule_name}'")
            rules[current_rule.rule_name] = current_rule
            current_rule = PEGGrammarRule()
            current_rule_name = None
            parse_state = ParseState.RULE_NAME
            c += 1
            continue
        if character_is_space(contents[c]):
            c += 1
            continue
        if parse_state == ParseState.RULE_NAME:
            start_pos = c
            if contents[c] == "%":
                c += 1
            while c < len(contents) and contents[c].isalnum():
                c += 1
            if c == start_pos:
                get_parse_location(contents, c).raise_error("Expected an alpha-numeric rule name")
            current_rule_name = contents[start_pos:c]
            current_rule.clear()
            parse_state = ParseState.RULE_SEPARATOR
            continue
        elif parse_state == ParseState.RULE_SEPARATOR:
            if contents[c] == "(":
                c += 1
                parameter_start = c
                while c < len(contents) and contents[c].isalnum():
                    c += 1
                if parameter_start == c:
                    get_parse_location(contents, c).raise_error("Expected a parameter")
                param_name = contents[parameter_start:c]
                current_rule.parameters[param_name] = len(current_rule.parameters)
                if contents[c] != ")":
                    get_parse_location(contents, c).raise_error("Expected a closing bracket")
                c += 1
            else:
                if contents[c] != "<" or contents[c + 1] != "-":
                    get_parse_location(contents, c).raise_error("Expected a rule definition (<-)")
                c += 2
                parse_state = ParseState.RULE_DEFINITION
        elif parse_state == ParseState.RULE_DEFINITION:
            in_or_clause = False
            if contents[c] == "'":
                # literal
                c += 1
                literal_start = c
                while c < len(contents) and contents[c] != "'":
                    if contents[c] == '\\':
                        c += 1
                    c += 1
                if c >= len(contents):
                    get_parse_location(contents, c).raise_error("Did not find closing '")
                current_rule.tokens.append(PEGToken(contents[literal_start:c], PEGTokenType.LITERAL))
                c += 1
                if c < len(contents) and contents[c] == 'i':
                    get_parse_location(contents, c).raise_error(
                        f"Unexpected \"i\" found in grammar near rule {current_rule_name}"
                    )
            elif c < len(contents) and contents[c].isalnum():
                # rule reference or function call
                rule_start = c
                while c < len(contents) and contents[c].isalnum():
                    c += 1
                text = contents[rule_start:c]
                if c < len(contents) and contents[c] == '(':
                    c += 1
                    bracket_count += 1
                    current_rule.tokens.append(PEGToken(text, PEGTokenType.FUNCTION_CALL))
                else:
                    current_rule.tokens.append(PEGToken(text, PEGTokenType.REFERENCE))
            elif contents[c] in ('[', '<'):
                # regex
                rule_start = c
                final_char = ']' if contents[c] == '[' else '>'
                while c < len(contents) and contents[c] != final_char:
                    if contents[c] == '\\':
                        c += 1
                    if c < len(contents):
                        c += 1
                c += 1
                current_rule.tokens.append(PEGToken(contents[rule_start:c], PEGTokenType.REGEX))
            elif contents[c] in ('/', '?', '(', ')', '*', '+', '!'):
                if contents[c] == '(':
                    bracket_count += 1
                elif contents[c] == ')':
                    if bracket_count == 0:
                        get_parse_location(contents, c).raise_error(f"Unclosed bracket in rule {current_rule_name}")
                    bracket_count -= 1
                elif contents[c] == '/':
                    in_or_clause = True
                current_rule.tokens.append(PEGToken(contents[c], PEGTokenType.OPERATOR))
                c += 1
            else:
                get_parse_location(contents, c).raise_error(f"Unrecognized rule contents in {current_rule_name}")

    if parse_state == ParseState.RULE_SEPARATOR:
        get_parse_location(contents, c).raise_error(f"Rule {current_rule_name} does not have a definition")
    if parse_state == ParseState.RULE_DEFINITION:
        if not current_rule.has_tokens():
            get_parse_location(contents, c).raise_error(f"Rule {current_rule_name} is empty")
        if current_rule_name in rules:
            get_parse_location(contents, c).raise_error(f"Duplicate rule name '{current_rule_name}'")
        current_rule.rule_name = current_rule_name
        rules[current_rule_name] = current_rule

    return rules


def check_unused_rules(all_rules):
    reachable = set()
    stack = ['Statement']

    while stack:
        rule_name = stack.pop()
        if rule_name in reachable or rule_name not in all_rules:
            continue
        reachable.add(rule_name)
        stack.extend(all_rules[rule_name].references())

    unused = sorted(set(all_rules.keys()) - reachable - IMPLICIT_RULES)
    for rule_name in unused:
        print(f"Warning: unused rule '{rule_name}'")


def check_undefined_rules(all_rules):
    found = False
    for rule_name, rule in all_rules.items():
        for ref in rule.references():
            if ref in rule.parameters:
                continue
            if ref not in all_rules:
                print(f"Error: rule '{rule_name}' references undefined rule '{ref}'")
                found = True
    if found:
        exit(1)


rules = {}

with open(statements_dir / "common.gram", 'r') as f:
    file_content = f.read()
    try:
        update_rules(rules, parse_peg_grammar(file_content), "common.gram")
    except Exception as e:
        raise Exception(f"common.gram: {e}") from None
    contents += file_content + "\n"


for filepath in keywords_dir.iterdir():
    if filepath.suffix != '.list':
        continue
    rule_name = filename_to_upper_camel(filepath)
    rule = f"{rule_name} <- "
    with open(filepath, 'r') as f:
        lines = [f"'{line.strip()}'" for line in f if line.strip()]
        rule += " /\n".join(lines) + "\n"
    contents += rule
    update_rules(rules, parse_peg_grammar(rule), filepath.name)

for filepath in statements_dir.iterdir():
    if filepath.suffix != '.gram':
        if not filepath.is_dir():
            raise Exception(f"File {filepath.name} does not end with .gram")
        continue
    if filepath.name != "common.gram":
        with open(filepath, 'r') as f:
            file_content = f.read()
            try:
                update_rules(rules, parse_peg_grammar(file_content), filepath.name)
            except Exception as e:
                raise Exception(f"{filepath.name}: {e}") from None
            contents += file_content + "\n"

check_unused_rules(rules)
check_undefined_rules(rules)

write_keyword_map()

if args.print:
    print(contents)
    exit(0)

if args.grammar_file:
    grammar_file = target_file.with_suffix('.gram')
    with open(grammar_file, 'w+') as f:
        f.write(contents)
    exit(0)


def get_grammar_bytes(contents):
    result_text = ""
    for line in contents.split('\n'):
        if len(line) == 0:
            continue
        result_text += "\t\"" + line.replace('\\', '\\\\').replace('"', '\\"') + "\\n\"\n"
    return result_text


with open(target_file, 'w+') as f:
    f.write(
        '''/* THIS FILE WAS AUTOMATICALLY GENERATED BY inline_grammar.py */
#pragma once

namespace duckdb {

const char INLINED_PEG_GRAMMAR[] = {
'''
        + get_grammar_bytes(contents)
        + '''
};

} // namespace duckdb
'''
    )
