# Parse the feature registry in smaller_binary.hpp, which is the single source of truth for both
# the feature names and their group membership.
set(SB_REGISTRY_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/src/include/duckdb/common/smaller_binary.hpp")
file(STRINGS "${SB_REGISTRY_HEADER}" SB_REGISTRY_LINES REGEX "^#define DUCKDB_SB_FEATURE_")
set(SB_ALL_FEATURES "")
set(SB_ALL_GROUPS "")
foreach(SB_LINE ${SB_REGISTRY_LINES})
  if(NOT SB_LINE MATCHES "^#define DUCKDB_SB_FEATURE_([A-Za-z0-9_]+) +DUCKDB_SB_DEFAULT.*// *group: *([A-Za-z0-9_]+)")
    message(FATAL_ERROR "Malformed entry in ${SB_REGISTRY_HEADER}: ${SB_LINE}")
  endif()
  list(APPEND SB_ALL_FEATURES "${CMAKE_MATCH_1}")
  list(APPEND SB_ALL_GROUPS "${CMAKE_MATCH_2}")
  list(APPEND SB_GROUP_${CMAKE_MATCH_2} "${CMAKE_MATCH_1}")
endforeach()
list(REMOVE_DUPLICATES SB_ALL_GROUPS)

# Expands feature names, group names and the 'all' alias into a flat list of feature names.
function(sb_resolve_names OUT_VAR OPTION_NAME)
  set(SB_RESULT "")
  string(REPLACE "," ";" SB_NAMES "${ARGN}")
  foreach(SB_NAME ${SB_NAMES})
    string(STRIP "${SB_NAME}" SB_NAME)
    if(SB_NAME STREQUAL "")
      continue()
    elseif(SB_NAME STREQUAL "all")
      list(APPEND SB_RESULT ${SB_ALL_FEATURES})
    elseif(SB_NAME IN_LIST SB_ALL_FEATURES)
      list(APPEND SB_RESULT "${SB_NAME}")
    elseif(SB_NAME IN_LIST SB_ALL_GROUPS)
      list(APPEND SB_RESULT ${SB_GROUP_${SB_NAME}})
    else()
      string(REPLACE ";" ", " SB_FEATURE_HELP "${SB_ALL_FEATURES}")
      string(REPLACE ";" ", " SB_GROUP_HELP "${SB_ALL_GROUPS}")
      message(FATAL_ERROR "Unknown ${OPTION_NAME} name '${SB_NAME}'.\n"
                          "  groups:   all, ${SB_GROUP_HELP}\n"
                          "  features: ${SB_FEATURE_HELP}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES SB_RESULT)
  set(${OUT_VAR} "${SB_RESULT}" PARENT_SCOPE)
endfunction()

if(SMALLER_BINARY STREQUAL "list")
  string(REPLACE ";" "\n    " SB_FEATURE_HELP "${SB_ALL_FEATURES}")
  string(REPLACE ";" "\n    " SB_GROUP_HELP "${SB_ALL_GROUPS}")
  message(FATAL_ERROR "SMALLER_BINARY groups:\n    all\n    ${SB_GROUP_HELP}\n"
                      "SMALLER_BINARY features:\n    ${SB_FEATURE_HELP}")
endif()

if(SMALLER_BINARY)
  if(SMALLER_BINARY MATCHES "^(1|ON|On|on|TRUE|True|true|YES|Yes|yes|Y|y)$")
    set(SB_ENABLED ${SB_ALL_FEATURES})
  else()
    sb_resolve_names(SB_ENABLED "SMALLER_BINARY" "${SMALLER_BINARY}")
  endif()
  if(SMALLER_BINARY_EXCEPT)
    sb_resolve_names(SB_EXCEPT "SMALLER_BINARY_EXCEPT" "${SMALLER_BINARY_EXCEPT}")
    list(REMOVE_ITEM SB_ENABLED ${SB_EXCEPT})
  endif()
elseif(SMALLER_BINARY_EXCEPT)
  message(FATAL_ERROR "SMALLER_BINARY_EXCEPT is set but SMALLER_BINARY is not")
else()
  set(SB_ENABLED "")
endif()

if(SB_ENABLED)
  # Emit the umbrella when everything is trimmed, otherwise flip on the requested features one by
  # one. The registry entries are #ifndef-guarded, so these -D flags win over the defaults.
  list(LENGTH SB_ENABLED SB_ENABLED_COUNT)
  list(LENGTH SB_ALL_FEATURES SB_TOTAL_COUNT)
  if(SB_ENABLED_COUNT EQUAL SB_TOTAL_COUNT)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DDUCKDB_SMALLER_BINARY_ALL")
  else()
    foreach(SB_FEATURE ${SB_ENABLED})
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DDUCKDB_SB_FEATURE_${SB_FEATURE}=DUCKDB_SB_ON")
    endforeach()
  endif()
  string(REPLACE ";" ", " SB_ENABLED_MSG "${SB_ENABLED}")
  message(STATUS "Smaller binary: trimming ${SB_ENABLED_COUNT}/${SB_TOTAL_COUNT} features (${SB_ENABLED_MSG})")
endif()
