#!/bin/sh

set -e
set -x

cd $(dirname $0)

R CMD build .
R CMD INSTALL --build duckdb_*.tar.gz
R -q -e 'tic::script()'
R -q -e 'tic::after_success()'

R -q -e "tools::write_PACKAGES(dir = '.', type = 'mac.binary')"
