#!/bin/sh

set -e
set -x

cd $(dirname $0)

R CMD build .
R CMD INSTALL --build duckdb_*.tar.gz
R -q -e 'tic::script()'
R -q -e 'tic::after_success()'

R -q -e "tools::write_PACKAGES(dir = '.', type = 'mac.binary')"

python3 ../upload-s3.py rstats/bin/macosx/contrib/4.0 duckdb_*.tgz PACKAGES*
python3 ../upload-s3.py rstats duckdb_*.tgz
python3 ../../scripts/asset-upload.py duckdb_r_osx.tgz=duckdb_*.tgz
