#!/bin/sh

set -e
set -x

cd $(dirname $0)

R -q -f dependencies.R
R CMD build .
R CMD INSTALL duckdb_*.tar.gz
R CMD check --as-cran duckdb_*.tar.gz

R -q -e "tools::write_PACKAGES(dir = '.', type = 'source')"
