//===----------------------------------------------------------------------===//
//
//                         DuckDB
//
// duckdb_extension_v2.h
//
//
//===----------------------------------------------------------------------===//
//
// !!!!!!!
// WARNING: this file is autogenerated, manual changes will be overwritten
// !!!!!!!

// WARNING: this API is not yet stable, meaning it is only guaranteed to work for this specific DuckDB version.

#pragma once

// An extension targets either the V1 or the V2 C API, never both.
#ifdef DUCKDB_EXTENSION_HEADER_VERSION
#error "duckdb_extension.h and duckdb_extension_v2.h cannot both be included: pick one C API version"
#endif
#define DUCKDB_EXTENSION_HEADER_VERSION 2

#include "duckdb_v2.h"

//===--------------------------------------------------------------------===//
// Util Macros
//===--------------------------------------------------------------------===//

#ifdef __cplusplus
#define DUCKDB_EXTENSION_EXTERN_C_GUARD_OPEN  extern "C" {
#define DUCKDB_EXTENSION_EXTERN_C_GUARD_CLOSE }
#else
#define DUCKDB_EXTENSION_EXTERN_C_GUARD_OPEN
#define DUCKDB_EXTENSION_EXTERN_C_GUARD_CLOSE
#endif

#define DUCKDB_EXTENSION_GLUE_HELPER(x, y) x##y
#define DUCKDB_EXTENSION_GLUE(x, y)        DUCKDB_EXTENSION_GLUE_HELPER(x, y)
#define DUCKDB_EXTENSION_STR_HELPER(x)     #x
#define DUCKDB_EXTENSION_STR(x)            DUCKDB_EXTENSION_STR_HELPER(x)
#define DUCKDB_EXTENSION_SEMVER_STRING(major, minor, patch)                                                            \
	"v" DUCKDB_EXTENSION_STR_HELPER(major) "." DUCKDB_EXTENSION_STR_HELPER(minor) "." DUCKDB_EXTENSION_STR_HELPER(patch)

//===--------------------------------------------------------------------===//
// Versioning
//===--------------------------------------------------------------------===//
//! Set version to latest if no explicit version is defined

#if !defined(DUCKDB_EXTENSION_API_VERSION_MAJOR) && !defined(DUCKDB_EXTENSION_API_VERSION_MINOR) &&                    \
    !defined(DUCKDB_EXTENSION_API_VERSION_PATCH)
#define DUCKDB_EXTENSION_API_VERSION_MAJOR 2
#define DUCKDB_EXTENSION_API_VERSION_MINOR 0
#define DUCKDB_EXTENSION_API_VERSION_PATCH 0
#elif !(defined(DUCKDB_EXTENSION_API_VERSION_MAJOR) && defined(DUCKDB_EXTENSION_API_VERSION_MINOR) &&                  \
        defined(DUCKDB_EXTENSION_API_VERSION_PATCH))
#error "either all or none of the  DUCKDB_EXTENSION_API_VERSION_ defines should be defined"
#endif

//! The version string passed to DuckDB on extension load. The major selects the V2 API family; for extensions pinned
//! to an exact DuckDB version (C_STRUCT_UNSTABLE) the loader reads only the major and ignores the rest.
#define DUCKDB_EXTENSION_API_VERSION_STRING                                                                            \
	DUCKDB_EXTENSION_SEMVER_STRING(DUCKDB_EXTENSION_API_VERSION_MAJOR, DUCKDB_EXTENSION_API_VERSION_MINOR,             \
	                               DUCKDB_EXTENSION_API_VERSION_PATCH)

#if DUCKDB_EXTENSION_API_VERSION_MAJOR != 2
#error "This version of the extension API header only supports API VERSION v2.x.x"
#endif

//===--------------------------------------------------------------------===//
// Function pointer struct
//===--------------------------------------------------------------------===//
typedef struct {
	// capigen:begin appended
	DUCKDB_V2_ERROR(*duckdb_v2_arena_allocate)
	(duckdb_v2_arena_handle arena, idx_t byte_len, uint8_t **out_ptr, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_bignum_decode)
	(const uint8_t *in_data, idx_t in_length, uint8_t *out_data, idx_t out_capacity, idx_t *out_length,
	 bool *out_is_negative, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_bignum_encode)
	(const uint8_t *in_data, idx_t in_length, bool is_negative, uint8_t *out_data, idx_t out_capacity,
	 idx_t *out_length, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_close)(duckdb_v2_database_handle *db);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_append)
	(duckdb_v2_column_data_collection_handle collection, duckdb_v2_column_data_collection_append_state_handle state,
	 duckdb_v2_data_chunk_handle chunk, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_append_state_create)
	(duckdb_v2_column_data_collection_handle collection,
	 duckdb_v2_column_data_collection_append_state_handle *out_state, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_append_state_destroy)
	(duckdb_v2_column_data_collection_append_state_handle *state);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_combine)
	(duckdb_v2_column_data_collection_handle target, duckdb_v2_column_data_collection_handle *source,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_create_with_connection)
	(duckdb_v2_connection_handle conn, const duckdb_v2_logical_type_handle *types_array, idx_t types_count,
	 duckdb_v2_column_data_collection_handle *out_collection, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_create_with_context)
	(duckdb_v2_context_handle context, const duckdb_v2_logical_type_handle *types_array, idx_t types_count,
	 duckdb_v2_column_data_collection_handle *out_collection, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_column_data_collection_destroy)(duckdb_v2_column_data_collection_handle *collection);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_reset)
	(duckdb_v2_column_data_collection_handle collection, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_row_count)
	(duckdb_v2_column_data_collection_handle collection, idx_t *out_row_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_scan)
	(duckdb_v2_column_data_collection_handle collection,
	 duckdb_v2_column_data_collection_shared_scan_state_handle shared_state,
	 duckdb_v2_column_data_collection_worker_scan_state_handle worker_state, duckdb_v2_data_chunk_handle out_chunk,
	 bool *did_produce_chunk, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_shared_scan_state_create)
	(duckdb_v2_column_data_collection_handle collection,
	 duckdb_v2_column_data_collection_shared_scan_state_handle *out_state, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_shared_scan_state_destroy)
	(duckdb_v2_column_data_collection_shared_scan_state_handle *state);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_worker_scan_state_create)
	(duckdb_v2_column_data_collection_handle collection,
	 duckdb_v2_column_data_collection_worker_scan_state_handle *out_state, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_column_data_collection_worker_scan_state_destroy)
	(duckdb_v2_column_data_collection_worker_scan_state_handle *state);
	DUCKDB_V2_ERROR(*duckdb_v2_connect)
	(duckdb_v2_database_handle db, duckdb_v2_connection_handle *out_conn, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_create_type_from_id)
	(duckdb_v2_connection_handle conn, DUCKDB_V2_LOGICAL_TYPE_ID type_id, const duckdb_v2_identifier_t *param_names,
	 const duckdb_v2_value_handle *param_values, idx_t param_count, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_create_type_from_name)
	(duckdb_v2_connection_handle conn, duckdb_v2_identifier_t name, const duckdb_v2_identifier_t *param_names,
	 const duckdb_v2_value_handle *param_values, idx_t param_count, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_create_type_from_text)
	(duckdb_v2_connection_handle conn, duckdb_v2_str text, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_create_type_with_alias)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle base_type, duckdb_v2_identifier_t alias_name,
	 duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_interrupt)
	(duckdb_v2_connection_handle conn, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_option_get)
	(duckdb_v2_connection_handle conn, duckdb_v2_identifier_t name, duckdb_v2_option_handle *out_option,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_option_get_by_index)
	(duckdb_v2_connection_handle conn, idx_t index, duckdb_v2_option_handle *out_option,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_option_get_count)
	(duckdb_v2_connection_handle conn, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_option_set)
	(duckdb_v2_connection_handle conn, duckdb_v2_option_handle option, DUCKDB_V2_SETTING_SCOPE scope,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_connection_query_progress)
	(duckdb_v2_connection_handle conn, duckdb_v2_query_progress_handle *out_progress, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_context_create_type_from_id)
	(duckdb_v2_context_handle ctx, DUCKDB_V2_LOGICAL_TYPE_ID type_id, const duckdb_v2_identifier_t *param_names,
	 const duckdb_v2_value_handle *param_values, idx_t param_count, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_context_create_type_from_name)
	(duckdb_v2_context_handle ctx, duckdb_v2_identifier_t name, const duckdb_v2_identifier_t *param_names,
	 const duckdb_v2_value_handle *param_values, idx_t param_count, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_context_create_type_from_text)
	(duckdb_v2_context_handle ctx, duckdb_v2_str text, duckdb_v2_logical_type_handle *out_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_context_create_type_with_alias)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle base_type, duckdb_v2_identifier_t alias_name,
	 duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_create_environment)
	(duckdb_v2_environment_handle *out_env, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_copy_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_data_chunk_handle chunk, duckdb_v2_data_chunk_handle *out_chunk,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_copy_with_context)
	(duckdb_v2_context_handle context, duckdb_v2_data_chunk_handle chunk, duckdb_v2_data_chunk_handle *out_chunk,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_create)
	(const duckdb_v2_logical_type_handle *types, idx_t column_count, duckdb_v2_data_chunk_handle *out_chunk,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_create_with_connection)
	(duckdb_v2_connection_handle conn, const duckdb_v2_logical_type_handle *types, idx_t column_count,
	 duckdb_v2_data_chunk_handle *out_chunk, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_create_with_context)
	(duckdb_v2_context_handle context, const duckdb_v2_logical_type_handle *types, idx_t column_count,
	 duckdb_v2_data_chunk_handle *out_chunk, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_data_chunk_destroy)(duckdb_v2_data_chunk_handle *chunk);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_get_size)
	(duckdb_v2_data_chunk_handle chunk, idx_t *out_size, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_get_vector)
	(duckdb_v2_data_chunk_handle chunk, idx_t index, duckdb_v2_vector_handle *out_vector,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_data_chunk_get_vector_count)
	(duckdb_v2_data_chunk_handle chunk, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_database_option_get)
	(duckdb_v2_database_handle db, duckdb_v2_identifier_t name, duckdb_v2_option_handle *out_option,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_database_option_get_by_index)
	(duckdb_v2_database_handle db, idx_t index, duckdb_v2_option_handle *out_option, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_database_option_get_count)
	(duckdb_v2_database_handle db, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_database_option_set)
	(duckdb_v2_database_handle db, duckdb_v2_option_handle option, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_destroy_environment)(duckdb_v2_environment_handle *env);
	DUCKDB_V2_ERROR (*duckdb_v2_disconnect)(duckdb_v2_connection_handle *conn);
	DUCKDB_V2_ERROR(*duckdb_v2_environment_database_count)
	(duckdb_v2_environment_handle env, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_error_info_destroy)(duckdb_v2_error_info_handle *info);
	DUCKDB_V2_ERROR (*duckdb_v2_error_info_get_code)(duckdb_v2_error_info_handle info, DUCKDB_V2_ERROR *out_code);
	DUCKDB_V2_ERROR(*duckdb_v2_error_info_get_raw_message)
	(duckdb_v2_error_info_handle info, duckdb_v2_str *out_raw_message);
	DUCKDB_V2_ERROR (*duckdb_v2_error_info_get_text)(duckdb_v2_error_info_handle info, duckdb_v2_str *out_text);
	DUCKDB_V2_ERROR (*duckdb_v2_error_info_set_code)(duckdb_v2_error_info_handle info, DUCKDB_V2_ERROR code);
	DUCKDB_V2_ERROR (*duckdb_v2_error_info_set_text)(duckdb_v2_error_info_handle info, duckdb_v2_str text);
	DUCKDB_V2_ERROR (*duckdb_v2_library_version)(duckdb_v2_str *out_version, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_copy)
	(duckdb_v2_logical_type_handle type, duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_logical_type_destroy)(duckdb_v2_logical_type_handle *type);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_get_id)
	(duckdb_v2_logical_type_handle type, DUCKDB_V2_LOGICAL_TYPE_ID *out_id, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_get_name)
	(duckdb_v2_logical_type_handle type, duckdb_v2_identifier_t *out_name, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_get_param)
	(duckdb_v2_logical_type_handle type, idx_t index, duckdb_v2_identifier_t *out_name,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_get_param_count)
	(duckdb_v2_logical_type_handle type, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_is_equal)
	(duckdb_v2_logical_type_handle left, duckdb_v2_logical_type_handle right, bool *result,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_logical_type_to_text)
	(duckdb_v2_logical_type_handle type, char *out_text, idx_t out_capacity, idx_t *out_length,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_open)
	(duckdb_v2_environment_handle env, duckdb_v2_str path, duckdb_v2_option_handle *options, idx_t option_count,
	 duckdb_v2_database_handle *out_db, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_create)
	(duckdb_v2_identifier_t name, duckdb_v2_str setting, duckdb_v2_option_handle *out_option,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_option_destroy)(duckdb_v2_option_handle *option);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_alias)
	(duckdb_v2_option_handle option, idx_t index, duckdb_v2_identifier_t *out_alias, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_alias_count)
	(duckdb_v2_option_handle option, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_default_setting)
	(duckdb_v2_option_handle option, duckdb_v2_str *out_default_setting, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_description)
	(duckdb_v2_option_handle option, duckdb_v2_str *out_description, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_name)
	(duckdb_v2_option_handle option, duckdb_v2_identifier_t *out_name, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_setting)
	(duckdb_v2_option_handle option, duckdb_v2_str *out_setting, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_option_get_target_scope)
	(duckdb_v2_option_handle option, DUCKDB_V2_OPTION_TARGET_SCOPE *out_target_scope, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_parse_sql)
	(duckdb_v2_connection_handle conn, const char *sql, duckdb_v2_statement_iterator_handle *out_iterator,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_query_progress_destroy)(duckdb_v2_query_progress_handle *progress);
	DUCKDB_V2_ERROR(*duckdb_v2_query_progress_get_percentage)
	(duckdb_v2_query_progress_handle progress, double *out_percentage, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_query_progress_get_rows_processed)
	(duckdb_v2_query_progress_handle progress, uint64_t *out_rows_processed, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_query_progress_get_total_rows_to_process)
	(duckdb_v2_query_progress_handle progress, uint64_t *out_total_rows_to_process, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_result_destroy)(duckdb_v2_result_handle *result);
	DUCKDB_V2_ERROR(*duckdb_v2_result_drain)
	(duckdb_v2_result_handle result, idx_t *out_rows_changed, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_fetch_chunk)
	(duckdb_v2_result_handle result, duckdb_v2_data_chunk_handle *out_chunk, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_get_result_type)
	(duckdb_v2_result_handle result, DUCKDB_V2_RESULT_TYPE *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_get_schema)
	(duckdb_v2_result_handle result, duckdb_v2_schema_handle *out_schema, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_get_statement_type)
	(duckdb_v2_result_handle result, DUCKDB_V2_STATEMENT_TYPE *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_render_box)
	(duckdb_v2_result_handle *result, idx_t max_rows, idx_t max_width, idx_t max_col_width, duckdb_v2_str null_value,
	 idx_t render_mode, idx_t limit, duckdb_v2_text_sink_fn sink, void *user_data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_result_step)
	(duckdb_v2_result_handle result, duckdb_v2_data_chunk_handle *out_chunk, DUCKDB_V2_RESULT_STEP_STATUS *out_status,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_result_wait)(duckdb_v2_result_handle result, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_schema_destroy)(duckdb_v2_schema_handle *schema);
	DUCKDB_V2_ERROR(*duckdb_v2_schema_get_count)
	(duckdb_v2_schema_handle schema, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_schema_get_field)
	(duckdb_v2_schema_handle schema, idx_t index, duckdb_v2_identifier_t *out_name,
	 duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_sql_statement_destroy)(duckdb_v2_sql_statement_handle *statement);
	DUCKDB_V2_ERROR(*duckdb_v2_statement_bind)
	(duckdb_v2_connection_handle conn, duckdb_v2_sql_statement_handle statement, duckdb_v2_schema_handle *out_schema,
	 duckdb_v2_schema_handle *out_parameters, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_statement_execute)
	(duckdb_v2_connection_handle conn, duckdb_v2_sql_statement_handle statement,
	 const duckdb_v2_identifier_t *parameter_names, const duckdb_v2_value_handle *parameter_values,
	 idx_t parameter_count, duckdb_v2_result_handle *out_result, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_statement_iterator_destroy)(duckdb_v2_statement_iterator_handle *iterator);
	DUCKDB_V2_ERROR(*duckdb_v2_statement_iterator_next)
	(duckdb_v2_statement_iterator_handle iterator, duckdb_v2_sql_statement_handle *out_statement,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_cast_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_value_handle value, duckdb_v2_logical_type_handle target_type,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_cast_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_value_handle value, duckdb_v2_logical_type_handle target_type,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_array_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle child_type, const duckdb_v2_value_handle *children,
	 idx_t child_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_array_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle child_type, const duckdb_v2_value_handle *children,
	 idx_t child_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bigint_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bigint_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bignum_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bignum_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bit_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bit_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_blob_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_blob_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bool_with_connection)
	(duckdb_v2_connection_handle conn, bool in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_bool_with_context)
	(duckdb_v2_context_handle ctx, bool in_value, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_date_with_connection)
	(duckdb_v2_connection_handle conn, int32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_date_with_context)
	(duckdb_v2_context_handle ctx, int32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_decimal_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_hugeint_t in_value, uint8_t width, uint8_t scale,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_decimal_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_hugeint_t in_value, uint8_t width, uint8_t scale,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_double_with_connection)
	(duckdb_v2_connection_handle conn, double in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_double_with_context)
	(duckdb_v2_context_handle ctx, double in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_float_with_connection)
	(duckdb_v2_connection_handle conn, float in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_float_with_context)
	(duckdb_v2_context_handle ctx, float in_value, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_hugeint_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_hugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_hugeint_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_hugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_int_with_connection)
	(duckdb_v2_connection_handle conn, int32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_int_with_context)
	(duckdb_v2_context_handle ctx, int32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_interval_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_interval_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_interval_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_interval_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_list_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle child_type, const duckdb_v2_value_handle *children,
	 idx_t child_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_list_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle child_type, const duckdb_v2_value_handle *children,
	 idx_t child_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_map_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle key_type, duckdb_v2_logical_type_handle value_type,
	 const duckdb_v2_value_handle *keys, const duckdb_v2_value_handle *values, idx_t entry_count,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_map_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle key_type, duckdb_v2_logical_type_handle value_type,
	 const duckdb_v2_value_handle *keys, const duckdb_v2_value_handle *values, idx_t entry_count,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_null)
	(duckdb_v2_logical_type_handle type, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_null_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle type, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_null_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle type, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_smallint_with_connection)
	(duckdb_v2_connection_handle conn, int16_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_smallint_with_context)
	(duckdb_v2_context_handle ctx, int16_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_struct_with_connection)
	(duckdb_v2_connection_handle conn, const duckdb_v2_identifier_t *names, const duckdb_v2_value_handle *children,
	 idx_t field_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_struct_with_context)
	(duckdb_v2_context_handle ctx, const duckdb_v2_identifier_t *names, const duckdb_v2_value_handle *children,
	 idx_t field_count, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_ns_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_ns_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_tz_with_connection)
	(duckdb_v2_connection_handle conn, uint64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_tz_with_context)
	(duckdb_v2_context_handle ctx, uint64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_time_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_ms_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_ms_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_ns_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_ns_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_sec_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_sec_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_tz_ns_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_tz_ns_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_tz_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_tz_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_with_connection)
	(duckdb_v2_connection_handle conn, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_timestamp_with_context)
	(duckdb_v2_context_handle ctx, int64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_tinyint_with_connection)
	(duckdb_v2_connection_handle conn, int8_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_tinyint_with_context)
	(duckdb_v2_context_handle ctx, int8_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_tuple_with_connection)
	(duckdb_v2_connection_handle conn, const duckdb_v2_value_handle *children, idx_t field_count,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_tuple_with_context)
	(duckdb_v2_context_handle ctx, const duckdb_v2_value_handle *children, idx_t field_count,
	 duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_type_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_logical_type_handle type, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_type_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_logical_type_handle in_type, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_ubigint_with_connection)
	(duckdb_v2_connection_handle conn, uint64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_ubigint_with_context)
	(duckdb_v2_context_handle ctx, uint64_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uhugeint_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_uhugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uhugeint_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_uhugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uint_with_connection)
	(duckdb_v2_connection_handle conn, uint32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uint_with_context)
	(duckdb_v2_context_handle ctx, uint32_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_usmallint_with_connection)
	(duckdb_v2_connection_handle conn, uint16_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_usmallint_with_context)
	(duckdb_v2_context_handle ctx, uint16_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_utinyint_with_connection)
	(duckdb_v2_connection_handle conn, uint8_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_utinyint_with_context)
	(duckdb_v2_context_handle ctx, uint8_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uuid_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_hugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_uuid_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_hugeint_t in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_varchar_with_connection)
	(duckdb_v2_connection_handle conn, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_create_varchar_with_context)
	(duckdb_v2_context_handle ctx, duckdb_v2_str in_value, duckdb_v2_value_handle *out_value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_value_destroy)(duckdb_v2_value_handle *value);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_bigint)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_blob)
	(duckdb_v2_value_handle value, duckdb_v2_str *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_bool)
	(duckdb_v2_value_handle value, bool *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_child)
	(duckdb_v2_value_handle value, idx_t index, duckdb_v2_value_handle *out_child, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_child_count)
	(duckdb_v2_value_handle value, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_date)
	(duckdb_v2_value_handle value, int32_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_decimal)
	(duckdb_v2_value_handle value, duckdb_v2_hugeint_t *out, uint8_t *out_width, uint8_t *out_scale,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_double)
	(duckdb_v2_value_handle value, double *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_float)
	(duckdb_v2_value_handle value, float *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_hugeint)
	(duckdb_v2_value_handle value, duckdb_v2_hugeint_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_int)
	(duckdb_v2_value_handle value, int32_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_interval)
	(duckdb_v2_value_handle value, duckdb_v2_interval_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_logical_type)
	(duckdb_v2_value_handle value, duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_smallint)
	(duckdb_v2_value_handle value, int16_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_time)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_time_ns)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_time_tz)
	(duckdb_v2_value_handle value, uint64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp_ms)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp_ns)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp_sec)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp_tz)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_timestamp_tz_ns)
	(duckdb_v2_value_handle value, int64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_tinyint)
	(duckdb_v2_value_handle value, int8_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_type)
	(duckdb_v2_value_handle value, duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_ubigint)
	(duckdb_v2_value_handle value, uint64_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_uhugeint)
	(duckdb_v2_value_handle value, duckdb_v2_uhugeint_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_uint)
	(duckdb_v2_value_handle value, uint32_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_usmallint)
	(duckdb_v2_value_handle value, uint16_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_utinyint)
	(duckdb_v2_value_handle value, uint8_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_uuid)
	(duckdb_v2_value_handle value, duckdb_v2_hugeint_t *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_get_varchar)
	(duckdb_v2_value_handle value, duckdb_v2_str *out, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_is_null)
	(duckdb_v2_value_handle value, bool *out_is_null, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_value_to_string)
	(duckdb_v2_value_handle value, char *out_string, idx_t out_capacity, idx_t *out_length,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_constant_set_valid)
	(duckdb_v2_vector_handle vector, bool validity, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_flat_get_validity_mutable)
	(duckdb_v2_vector_handle vector, uint64_t **out_validity, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_vector_flatten)(duckdb_v2_vector_handle vector, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_arena)
	(duckdb_v2_vector_handle vector, duckdb_v2_arena_handle *out_arena, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_child)
	(duckdb_v2_vector_handle vector, idx_t index, duckdb_v2_vector_handle *out_child, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_child_count)
	(duckdb_v2_vector_handle vector, idx_t *out_count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_data_mutable)
	(duckdb_v2_vector_handle vector, void **out_data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_logical_type)
	(duckdb_v2_vector_handle vector, duckdb_v2_logical_type_handle *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_size)
	(duckdb_v2_vector_handle vector, idx_t *out_size, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_value)
	(duckdb_v2_vector_handle vector, idx_t row, duckdb_v2_value_handle *out_value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_vector_type)
	(duckdb_v2_vector_handle vector, DUCKDB_V2_VECTOR_TYPE *out_type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_get_view)
	(duckdb_v2_vector_handle vector, duckdb_v2_vector_view *out_view, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_make_constant)
	(duckdb_v2_vector_handle vector, duckdb_v2_value_handle value, idx_t count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_make_sequence)
	(duckdb_v2_vector_handle vector, int64_t start, int64_t increment, idx_t count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_reference)
	(duckdb_v2_vector_handle vector, duckdb_v2_vector_handle source, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_set_null)
	(duckdb_v2_vector_handle vector, idx_t row, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_set_size)
	(duckdb_v2_vector_handle vector, idx_t size, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_vector_set_value)
	(duckdb_v2_vector_handle vector, idx_t row, duckdb_v2_value_handle value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_get_arg_count)
	(duckdb_v2_aggregate_function_bind_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_get_arg_type)
	(duckdb_v2_aggregate_function_bind_info_handle info, idx_t index, duckdb_v2_logical_type_handle *type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_get_arg_value)
	(duckdb_v2_aggregate_function_bind_info_handle info, idx_t index, duckdb_v2_value_handle *value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_context_log)
	(duckdb_v2_context_handle ctx, DUCKDB_V2_LOG_LEVEL level, duckdb_v2_str log_type, duckdb_v2_str message,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_function_signature_add_parameter)
	(duckdb_v2_function_signature_handle sig, duckdb_v2_identifier_t name, duckdb_v2_logical_type_handle type,
	 duckdb_v2_value_handle value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_function_signature_set_return_type)
	(duckdb_v2_function_signature_handle sig, duckdb_v2_logical_type_handle type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_function_signature_set_varargs)
	(duckdb_v2_function_signature_handle sig, duckdb_v2_logical_type_handle type, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_get_arg_count)
	(duckdb_v2_scalar_function_bind_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_get_arg_type)
	(duckdb_v2_scalar_function_bind_info_handle info, idx_t index, duckdb_v2_logical_type_handle *type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_get_arg_value)
	(duckdb_v2_scalar_function_bind_info_handle info, idx_t index, duckdb_v2_value_handle *value,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_get_user_data)
	(duckdb_v2_scalar_function_bind_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_set_bind_data)
	(duckdb_v2_scalar_function_bind_info_handle info, duckdb_v2_opaque *data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_bind_set_return_type)
	(duckdb_v2_scalar_function_bind_info_handle info, duckdb_v2_logical_type_handle return_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_create_with_connection)
	(duckdb_v2_connection_handle connection, duckdb_v2_scalar_function_handle *function,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_create_with_extension)
	(duckdb_v2_extension_handle extension, duckdb_v2_scalar_function_handle *function,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_scalar_function_destroy)(duckdb_v2_scalar_function_handle *function);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_arg)
	(duckdb_v2_scalar_function_exec_info_handle info, uint32_t index, duckdb_v2_vector_handle *vector,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_arg_count)
	(duckdb_v2_scalar_function_exec_info_handle info, uint32_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_bind_data)
	(duckdb_v2_scalar_function_exec_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_init_data)
	(duckdb_v2_scalar_function_exec_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_result)
	(duckdb_v2_scalar_function_exec_info_handle info, duckdb_v2_vector_handle *vector,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_row_count)
	(duckdb_v2_scalar_function_exec_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_exec_get_user_data)
	(duckdb_v2_scalar_function_exec_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_get_signature)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_function_signature_handle *sig,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_init_get_bind_data)
	(duckdb_v2_scalar_function_init_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_init_get_user_data)
	(duckdb_v2_scalar_function_init_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_init_set_init_data)
	(duckdb_v2_scalar_function_init_info_handle info, duckdb_v2_opaque *data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_register)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_bind_callback)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_scalar_function_bind_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_exec_callback)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_scalar_function_exec_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_init_callback)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_scalar_function_init_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_name)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_str *name, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_user_data)
	(duckdb_v2_scalar_function_handle function, duckdb_v2_opaque *data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_get_user_data)
	(duckdb_v2_aggregate_function_bind_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_set_bind_data)
	(duckdb_v2_aggregate_function_bind_info_handle info, duckdb_v2_opaque *data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_bind_set_return_type)
	(duckdb_v2_aggregate_function_bind_info_handle info, duckdb_v2_logical_type_handle return_type,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_combine_get_bind_data)
	(duckdb_v2_aggregate_function_combine_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_combine_get_sources)
	(duckdb_v2_aggregate_function_combine_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_combine_get_state_count)
	(duckdb_v2_aggregate_function_combine_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_combine_get_targets)
	(duckdb_v2_aggregate_function_combine_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_combine_get_user_data)
	(duckdb_v2_aggregate_function_combine_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_create_with_connection)
	(duckdb_v2_connection_handle connection, duckdb_v2_aggregate_function_handle *function,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_create_with_extension)
	(duckdb_v2_extension_handle extension, duckdb_v2_aggregate_function_handle *function,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR (*duckdb_v2_aggregate_function_destroy)(duckdb_v2_aggregate_function_handle *function);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_destroy_get_bind_data)
	(duckdb_v2_aggregate_function_destroy_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_destroy_get_state_count)
	(duckdb_v2_aggregate_function_destroy_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_destroy_get_states)
	(duckdb_v2_aggregate_function_destroy_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_destroy_get_user_data)
	(duckdb_v2_aggregate_function_destroy_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_bind_data)
	(duckdb_v2_aggregate_function_finalize_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_result)
	(duckdb_v2_aggregate_function_finalize_info_handle info, duckdb_v2_vector_handle *vector,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_result_offset)
	(duckdb_v2_aggregate_function_finalize_info_handle info, idx_t *offset, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_state_count)
	(duckdb_v2_aggregate_function_finalize_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_states)
	(duckdb_v2_aggregate_function_finalize_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_finalize_get_user_data)
	(duckdb_v2_aggregate_function_finalize_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_get_signature)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_function_signature_handle *sig,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_init_get_bind_data)
	(duckdb_v2_aggregate_function_init_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_init_get_state_count)
	(duckdb_v2_aggregate_function_init_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_init_get_states)
	(duckdb_v2_aggregate_function_init_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_init_get_user_data)
	(duckdb_v2_aggregate_function_init_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_register)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_bind_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_bind_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_combine_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_combine_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_destroy_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_destroy_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_finalize_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_finalize_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_init_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_init_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_name)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_str *name, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_size_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_size_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_update_callback)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_aggregate_function_update_callback_fn callback,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_user_data)
	(duckdb_v2_aggregate_function_handle function, duckdb_v2_opaque *data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_size_get_bind_data)
	(duckdb_v2_aggregate_function_size_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_size_get_user_data)
	(duckdb_v2_aggregate_function_size_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_size_set_state_size)
	(duckdb_v2_aggregate_function_size_info_handle info, idx_t size, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_arg)
	(duckdb_v2_aggregate_function_update_info_handle info, uint32_t index, duckdb_v2_vector_handle *vector,
	 duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_arg_count)
	(duckdb_v2_aggregate_function_update_info_handle info, uint32_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_bind_data)
	(duckdb_v2_aggregate_function_update_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_row_count)
	(duckdb_v2_aggregate_function_update_info_handle info, idx_t *count, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_states)
	(duckdb_v2_aggregate_function_update_info_handle info, void ***states, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_update_get_user_data)
	(duckdb_v2_aggregate_function_update_info_handle info, void **data, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_aggregate_function_set_property)
	(duckdb_v2_aggregate_function_handle function, DUCKDB_V2_FUNCTION_PROPERTY_KEY key,
	 DUCKDB_V2_FUNCTION_PROPERTY_VALUE value, duckdb_v2_error_info_handle *err);
	DUCKDB_V2_ERROR(*duckdb_v2_scalar_function_set_property)
	(duckdb_v2_scalar_function_handle function, DUCKDB_V2_FUNCTION_PROPERTY_KEY key,
	 DUCKDB_V2_FUNCTION_PROPERTY_VALUE value, duckdb_v2_error_info_handle *err);
	// capigen:end appended
} duckdb_ext_api_v2;

//===--------------------------------------------------------------------===//
// Typedefs mapping functions to struct entries
//===--------------------------------------------------------------------===//
// When building as a static extension, DuckDB symbols are resolved directly at link time.
// The vtable (duckdb_ext_api) is not used - skip these macro redirections.
#ifndef DUCKDB_BUILD_STATIC_EXTENSION
// capigen:begin appended
#define duckdb_v2_arena_allocate                duckdb_ext_api.duckdb_v2_arena_allocate
#define duckdb_v2_bignum_decode                 duckdb_ext_api.duckdb_v2_bignum_decode
#define duckdb_v2_bignum_encode                 duckdb_ext_api.duckdb_v2_bignum_encode
#define duckdb_v2_close                         duckdb_ext_api.duckdb_v2_close
#define duckdb_v2_column_data_collection_append duckdb_ext_api.duckdb_v2_column_data_collection_append
#define duckdb_v2_column_data_collection_append_state_create                                                           \
	duckdb_ext_api.duckdb_v2_column_data_collection_append_state_create
#define duckdb_v2_column_data_collection_append_state_destroy                                                          \
	duckdb_ext_api.duckdb_v2_column_data_collection_append_state_destroy
#define duckdb_v2_column_data_collection_combine duckdb_ext_api.duckdb_v2_column_data_collection_combine
#define duckdb_v2_column_data_collection_create_with_connection                                                        \
	duckdb_ext_api.duckdb_v2_column_data_collection_create_with_connection
#define duckdb_v2_column_data_collection_create_with_context                                                           \
	duckdb_ext_api.duckdb_v2_column_data_collection_create_with_context
#define duckdb_v2_column_data_collection_destroy   duckdb_ext_api.duckdb_v2_column_data_collection_destroy
#define duckdb_v2_column_data_collection_reset     duckdb_ext_api.duckdb_v2_column_data_collection_reset
#define duckdb_v2_column_data_collection_row_count duckdb_ext_api.duckdb_v2_column_data_collection_row_count
#define duckdb_v2_column_data_collection_scan      duckdb_ext_api.duckdb_v2_column_data_collection_scan
#define duckdb_v2_column_data_collection_shared_scan_state_create                                                      \
	duckdb_ext_api.duckdb_v2_column_data_collection_shared_scan_state_create
#define duckdb_v2_column_data_collection_shared_scan_state_destroy                                                     \
	duckdb_ext_api.duckdb_v2_column_data_collection_shared_scan_state_destroy
#define duckdb_v2_column_data_collection_worker_scan_state_create                                                      \
	duckdb_ext_api.duckdb_v2_column_data_collection_worker_scan_state_create
#define duckdb_v2_column_data_collection_worker_scan_state_destroy                                                     \
	duckdb_ext_api.duckdb_v2_column_data_collection_worker_scan_state_destroy
#define duckdb_v2_connect                           duckdb_ext_api.duckdb_v2_connect
#define duckdb_v2_connection_create_type_from_id    duckdb_ext_api.duckdb_v2_connection_create_type_from_id
#define duckdb_v2_connection_create_type_from_name  duckdb_ext_api.duckdb_v2_connection_create_type_from_name
#define duckdb_v2_connection_create_type_from_text  duckdb_ext_api.duckdb_v2_connection_create_type_from_text
#define duckdb_v2_connection_create_type_with_alias duckdb_ext_api.duckdb_v2_connection_create_type_with_alias
#define duckdb_v2_connection_interrupt              duckdb_ext_api.duckdb_v2_connection_interrupt
#define duckdb_v2_connection_option_get             duckdb_ext_api.duckdb_v2_connection_option_get
#define duckdb_v2_connection_option_get_by_index    duckdb_ext_api.duckdb_v2_connection_option_get_by_index
#define duckdb_v2_connection_option_get_count       duckdb_ext_api.duckdb_v2_connection_option_get_count
#define duckdb_v2_connection_option_set             duckdb_ext_api.duckdb_v2_connection_option_set
#define duckdb_v2_connection_query_progress         duckdb_ext_api.duckdb_v2_connection_query_progress
#define duckdb_v2_context_create_type_from_id       duckdb_ext_api.duckdb_v2_context_create_type_from_id
#define duckdb_v2_context_create_type_from_name     duckdb_ext_api.duckdb_v2_context_create_type_from_name
#define duckdb_v2_context_create_type_from_text     duckdb_ext_api.duckdb_v2_context_create_type_from_text
#define duckdb_v2_context_create_type_with_alias    duckdb_ext_api.duckdb_v2_context_create_type_with_alias
#define duckdb_v2_create_environment                duckdb_ext_api.duckdb_v2_create_environment
#define duckdb_v2_data_chunk_copy_with_connection   duckdb_ext_api.duckdb_v2_data_chunk_copy_with_connection
#define duckdb_v2_data_chunk_copy_with_context      duckdb_ext_api.duckdb_v2_data_chunk_copy_with_context
#define duckdb_v2_data_chunk_create                 duckdb_ext_api.duckdb_v2_data_chunk_create
#define duckdb_v2_data_chunk_create_with_connection duckdb_ext_api.duckdb_v2_data_chunk_create_with_connection
#define duckdb_v2_data_chunk_create_with_context    duckdb_ext_api.duckdb_v2_data_chunk_create_with_context
#define duckdb_v2_data_chunk_destroy                duckdb_ext_api.duckdb_v2_data_chunk_destroy
#define duckdb_v2_data_chunk_get_size               duckdb_ext_api.duckdb_v2_data_chunk_get_size
#define duckdb_v2_data_chunk_get_vector             duckdb_ext_api.duckdb_v2_data_chunk_get_vector
#define duckdb_v2_data_chunk_get_vector_count       duckdb_ext_api.duckdb_v2_data_chunk_get_vector_count
#define duckdb_v2_database_option_get               duckdb_ext_api.duckdb_v2_database_option_get
#define duckdb_v2_database_option_get_by_index      duckdb_ext_api.duckdb_v2_database_option_get_by_index
#define duckdb_v2_database_option_get_count         duckdb_ext_api.duckdb_v2_database_option_get_count
#define duckdb_v2_database_option_set               duckdb_ext_api.duckdb_v2_database_option_set
#define duckdb_v2_destroy_environment               duckdb_ext_api.duckdb_v2_destroy_environment
#define duckdb_v2_disconnect                        duckdb_ext_api.duckdb_v2_disconnect
#define duckdb_v2_environment_database_count        duckdb_ext_api.duckdb_v2_environment_database_count
#define duckdb_v2_error_info_destroy                duckdb_ext_api.duckdb_v2_error_info_destroy
#define duckdb_v2_error_info_get_code               duckdb_ext_api.duckdb_v2_error_info_get_code
#define duckdb_v2_error_info_get_raw_message        duckdb_ext_api.duckdb_v2_error_info_get_raw_message
#define duckdb_v2_error_info_get_text               duckdb_ext_api.duckdb_v2_error_info_get_text
#define duckdb_v2_error_info_set_code               duckdb_ext_api.duckdb_v2_error_info_set_code
#define duckdb_v2_error_info_set_text               duckdb_ext_api.duckdb_v2_error_info_set_text
#define duckdb_v2_library_version                   duckdb_ext_api.duckdb_v2_library_version
#define duckdb_v2_logical_type_copy                 duckdb_ext_api.duckdb_v2_logical_type_copy
#define duckdb_v2_logical_type_destroy              duckdb_ext_api.duckdb_v2_logical_type_destroy
#define duckdb_v2_logical_type_get_id               duckdb_ext_api.duckdb_v2_logical_type_get_id
#define duckdb_v2_logical_type_get_name             duckdb_ext_api.duckdb_v2_logical_type_get_name
#define duckdb_v2_logical_type_get_param            duckdb_ext_api.duckdb_v2_logical_type_get_param
#define duckdb_v2_logical_type_get_param_count      duckdb_ext_api.duckdb_v2_logical_type_get_param_count
#define duckdb_v2_logical_type_is_equal             duckdb_ext_api.duckdb_v2_logical_type_is_equal
#define duckdb_v2_logical_type_to_text              duckdb_ext_api.duckdb_v2_logical_type_to_text
#define duckdb_v2_open                              duckdb_ext_api.duckdb_v2_open
#define duckdb_v2_option_create                     duckdb_ext_api.duckdb_v2_option_create
#define duckdb_v2_option_destroy                    duckdb_ext_api.duckdb_v2_option_destroy
#define duckdb_v2_option_get_alias                  duckdb_ext_api.duckdb_v2_option_get_alias
#define duckdb_v2_option_get_alias_count            duckdb_ext_api.duckdb_v2_option_get_alias_count
#define duckdb_v2_option_get_default_setting        duckdb_ext_api.duckdb_v2_option_get_default_setting
#define duckdb_v2_option_get_description            duckdb_ext_api.duckdb_v2_option_get_description
#define duckdb_v2_option_get_name                   duckdb_ext_api.duckdb_v2_option_get_name
#define duckdb_v2_option_get_setting                duckdb_ext_api.duckdb_v2_option_get_setting
#define duckdb_v2_option_get_target_scope           duckdb_ext_api.duckdb_v2_option_get_target_scope
#define duckdb_v2_parse_sql                         duckdb_ext_api.duckdb_v2_parse_sql
#define duckdb_v2_query_progress_destroy            duckdb_ext_api.duckdb_v2_query_progress_destroy
#define duckdb_v2_query_progress_get_percentage     duckdb_ext_api.duckdb_v2_query_progress_get_percentage
#define duckdb_v2_query_progress_get_rows_processed duckdb_ext_api.duckdb_v2_query_progress_get_rows_processed
#define duckdb_v2_query_progress_get_total_rows_to_process                                                             \
	duckdb_ext_api.duckdb_v2_query_progress_get_total_rows_to_process
#define duckdb_v2_result_destroy                        duckdb_ext_api.duckdb_v2_result_destroy
#define duckdb_v2_result_drain                          duckdb_ext_api.duckdb_v2_result_drain
#define duckdb_v2_result_fetch_chunk                    duckdb_ext_api.duckdb_v2_result_fetch_chunk
#define duckdb_v2_result_get_result_type                duckdb_ext_api.duckdb_v2_result_get_result_type
#define duckdb_v2_result_get_schema                     duckdb_ext_api.duckdb_v2_result_get_schema
#define duckdb_v2_result_get_statement_type             duckdb_ext_api.duckdb_v2_result_get_statement_type
#define duckdb_v2_result_render_box                     duckdb_ext_api.duckdb_v2_result_render_box
#define duckdb_v2_result_step                           duckdb_ext_api.duckdb_v2_result_step
#define duckdb_v2_result_wait                           duckdb_ext_api.duckdb_v2_result_wait
#define duckdb_v2_schema_destroy                        duckdb_ext_api.duckdb_v2_schema_destroy
#define duckdb_v2_schema_get_count                      duckdb_ext_api.duckdb_v2_schema_get_count
#define duckdb_v2_schema_get_field                      duckdb_ext_api.duckdb_v2_schema_get_field
#define duckdb_v2_sql_statement_destroy                 duckdb_ext_api.duckdb_v2_sql_statement_destroy
#define duckdb_v2_statement_bind                        duckdb_ext_api.duckdb_v2_statement_bind
#define duckdb_v2_statement_execute                     duckdb_ext_api.duckdb_v2_statement_execute
#define duckdb_v2_statement_iterator_destroy            duckdb_ext_api.duckdb_v2_statement_iterator_destroy
#define duckdb_v2_statement_iterator_next               duckdb_ext_api.duckdb_v2_statement_iterator_next
#define duckdb_v2_value_cast_with_connection            duckdb_ext_api.duckdb_v2_value_cast_with_connection
#define duckdb_v2_value_cast_with_context               duckdb_ext_api.duckdb_v2_value_cast_with_context
#define duckdb_v2_value_create_array_with_connection    duckdb_ext_api.duckdb_v2_value_create_array_with_connection
#define duckdb_v2_value_create_array_with_context       duckdb_ext_api.duckdb_v2_value_create_array_with_context
#define duckdb_v2_value_create_bigint_with_connection   duckdb_ext_api.duckdb_v2_value_create_bigint_with_connection
#define duckdb_v2_value_create_bigint_with_context      duckdb_ext_api.duckdb_v2_value_create_bigint_with_context
#define duckdb_v2_value_create_bignum_with_connection   duckdb_ext_api.duckdb_v2_value_create_bignum_with_connection
#define duckdb_v2_value_create_bignum_with_context      duckdb_ext_api.duckdb_v2_value_create_bignum_with_context
#define duckdb_v2_value_create_bit_with_connection      duckdb_ext_api.duckdb_v2_value_create_bit_with_connection
#define duckdb_v2_value_create_bit_with_context         duckdb_ext_api.duckdb_v2_value_create_bit_with_context
#define duckdb_v2_value_create_blob_with_connection     duckdb_ext_api.duckdb_v2_value_create_blob_with_connection
#define duckdb_v2_value_create_blob_with_context        duckdb_ext_api.duckdb_v2_value_create_blob_with_context
#define duckdb_v2_value_create_bool_with_connection     duckdb_ext_api.duckdb_v2_value_create_bool_with_connection
#define duckdb_v2_value_create_bool_with_context        duckdb_ext_api.duckdb_v2_value_create_bool_with_context
#define duckdb_v2_value_create_date_with_connection     duckdb_ext_api.duckdb_v2_value_create_date_with_connection
#define duckdb_v2_value_create_date_with_context        duckdb_ext_api.duckdb_v2_value_create_date_with_context
#define duckdb_v2_value_create_decimal_with_connection  duckdb_ext_api.duckdb_v2_value_create_decimal_with_connection
#define duckdb_v2_value_create_decimal_with_context     duckdb_ext_api.duckdb_v2_value_create_decimal_with_context
#define duckdb_v2_value_create_double_with_connection   duckdb_ext_api.duckdb_v2_value_create_double_with_connection
#define duckdb_v2_value_create_double_with_context      duckdb_ext_api.duckdb_v2_value_create_double_with_context
#define duckdb_v2_value_create_float_with_connection    duckdb_ext_api.duckdb_v2_value_create_float_with_connection
#define duckdb_v2_value_create_float_with_context       duckdb_ext_api.duckdb_v2_value_create_float_with_context
#define duckdb_v2_value_create_hugeint_with_connection  duckdb_ext_api.duckdb_v2_value_create_hugeint_with_connection
#define duckdb_v2_value_create_hugeint_with_context     duckdb_ext_api.duckdb_v2_value_create_hugeint_with_context
#define duckdb_v2_value_create_int_with_connection      duckdb_ext_api.duckdb_v2_value_create_int_with_connection
#define duckdb_v2_value_create_int_with_context         duckdb_ext_api.duckdb_v2_value_create_int_with_context
#define duckdb_v2_value_create_interval_with_connection duckdb_ext_api.duckdb_v2_value_create_interval_with_connection
#define duckdb_v2_value_create_interval_with_context    duckdb_ext_api.duckdb_v2_value_create_interval_with_context
#define duckdb_v2_value_create_list_with_connection     duckdb_ext_api.duckdb_v2_value_create_list_with_connection
#define duckdb_v2_value_create_list_with_context        duckdb_ext_api.duckdb_v2_value_create_list_with_context
#define duckdb_v2_value_create_map_with_connection      duckdb_ext_api.duckdb_v2_value_create_map_with_connection
#define duckdb_v2_value_create_map_with_context         duckdb_ext_api.duckdb_v2_value_create_map_with_context
#define duckdb_v2_value_create_null                     duckdb_ext_api.duckdb_v2_value_create_null
#define duckdb_v2_value_create_null_with_connection     duckdb_ext_api.duckdb_v2_value_create_null_with_connection
#define duckdb_v2_value_create_null_with_context        duckdb_ext_api.duckdb_v2_value_create_null_with_context
#define duckdb_v2_value_create_smallint_with_connection duckdb_ext_api.duckdb_v2_value_create_smallint_with_connection
#define duckdb_v2_value_create_smallint_with_context    duckdb_ext_api.duckdb_v2_value_create_smallint_with_context
#define duckdb_v2_value_create_struct_with_connection   duckdb_ext_api.duckdb_v2_value_create_struct_with_connection
#define duckdb_v2_value_create_struct_with_context      duckdb_ext_api.duckdb_v2_value_create_struct_with_context
#define duckdb_v2_value_create_time_ns_with_connection  duckdb_ext_api.duckdb_v2_value_create_time_ns_with_connection
#define duckdb_v2_value_create_time_ns_with_context     duckdb_ext_api.duckdb_v2_value_create_time_ns_with_context
#define duckdb_v2_value_create_time_tz_with_connection  duckdb_ext_api.duckdb_v2_value_create_time_tz_with_connection
#define duckdb_v2_value_create_time_tz_with_context     duckdb_ext_api.duckdb_v2_value_create_time_tz_with_context
#define duckdb_v2_value_create_time_with_connection     duckdb_ext_api.duckdb_v2_value_create_time_with_connection
#define duckdb_v2_value_create_time_with_context        duckdb_ext_api.duckdb_v2_value_create_time_with_context
#define duckdb_v2_value_create_timestamp_ms_with_connection                                                            \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_ms_with_connection
#define duckdb_v2_value_create_timestamp_ms_with_context duckdb_ext_api.duckdb_v2_value_create_timestamp_ms_with_context
#define duckdb_v2_value_create_timestamp_ns_with_connection                                                            \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_ns_with_connection
#define duckdb_v2_value_create_timestamp_ns_with_context duckdb_ext_api.duckdb_v2_value_create_timestamp_ns_with_context
#define duckdb_v2_value_create_timestamp_sec_with_connection                                                           \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_sec_with_connection
#define duckdb_v2_value_create_timestamp_sec_with_context                                                              \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_sec_with_context
#define duckdb_v2_value_create_timestamp_tz_ns_with_connection                                                         \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_tz_ns_with_connection
#define duckdb_v2_value_create_timestamp_tz_ns_with_context                                                            \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_tz_ns_with_context
#define duckdb_v2_value_create_timestamp_tz_with_connection                                                            \
	duckdb_ext_api.duckdb_v2_value_create_timestamp_tz_with_connection
#define duckdb_v2_value_create_timestamp_tz_with_context duckdb_ext_api.duckdb_v2_value_create_timestamp_tz_with_context
#define duckdb_v2_value_create_timestamp_with_connection duckdb_ext_api.duckdb_v2_value_create_timestamp_with_connection
#define duckdb_v2_value_create_timestamp_with_context    duckdb_ext_api.duckdb_v2_value_create_timestamp_with_context
#define duckdb_v2_value_create_tinyint_with_connection   duckdb_ext_api.duckdb_v2_value_create_tinyint_with_connection
#define duckdb_v2_value_create_tinyint_with_context      duckdb_ext_api.duckdb_v2_value_create_tinyint_with_context
#define duckdb_v2_value_create_tuple_with_connection     duckdb_ext_api.duckdb_v2_value_create_tuple_with_connection
#define duckdb_v2_value_create_tuple_with_context        duckdb_ext_api.duckdb_v2_value_create_tuple_with_context
#define duckdb_v2_value_create_type_with_connection      duckdb_ext_api.duckdb_v2_value_create_type_with_connection
#define duckdb_v2_value_create_type_with_context         duckdb_ext_api.duckdb_v2_value_create_type_with_context
#define duckdb_v2_value_create_ubigint_with_connection   duckdb_ext_api.duckdb_v2_value_create_ubigint_with_connection
#define duckdb_v2_value_create_ubigint_with_context      duckdb_ext_api.duckdb_v2_value_create_ubigint_with_context
#define duckdb_v2_value_create_uhugeint_with_connection  duckdb_ext_api.duckdb_v2_value_create_uhugeint_with_connection
#define duckdb_v2_value_create_uhugeint_with_context     duckdb_ext_api.duckdb_v2_value_create_uhugeint_with_context
#define duckdb_v2_value_create_uint_with_connection      duckdb_ext_api.duckdb_v2_value_create_uint_with_connection
#define duckdb_v2_value_create_uint_with_context         duckdb_ext_api.duckdb_v2_value_create_uint_with_context
#define duckdb_v2_value_create_usmallint_with_connection duckdb_ext_api.duckdb_v2_value_create_usmallint_with_connection
#define duckdb_v2_value_create_usmallint_with_context    duckdb_ext_api.duckdb_v2_value_create_usmallint_with_context
#define duckdb_v2_value_create_utinyint_with_connection  duckdb_ext_api.duckdb_v2_value_create_utinyint_with_connection
#define duckdb_v2_value_create_utinyint_with_context     duckdb_ext_api.duckdb_v2_value_create_utinyint_with_context
#define duckdb_v2_value_create_uuid_with_connection      duckdb_ext_api.duckdb_v2_value_create_uuid_with_connection
#define duckdb_v2_value_create_uuid_with_context         duckdb_ext_api.duckdb_v2_value_create_uuid_with_context
#define duckdb_v2_value_create_varchar_with_connection   duckdb_ext_api.duckdb_v2_value_create_varchar_with_connection
#define duckdb_v2_value_create_varchar_with_context      duckdb_ext_api.duckdb_v2_value_create_varchar_with_context
#define duckdb_v2_value_destroy                          duckdb_ext_api.duckdb_v2_value_destroy
#define duckdb_v2_value_get_bigint                       duckdb_ext_api.duckdb_v2_value_get_bigint
#define duckdb_v2_value_get_blob                         duckdb_ext_api.duckdb_v2_value_get_blob
#define duckdb_v2_value_get_bool                         duckdb_ext_api.duckdb_v2_value_get_bool
#define duckdb_v2_value_get_child                        duckdb_ext_api.duckdb_v2_value_get_child
#define duckdb_v2_value_get_child_count                  duckdb_ext_api.duckdb_v2_value_get_child_count
#define duckdb_v2_value_get_date                         duckdb_ext_api.duckdb_v2_value_get_date
#define duckdb_v2_value_get_decimal                      duckdb_ext_api.duckdb_v2_value_get_decimal
#define duckdb_v2_value_get_double                       duckdb_ext_api.duckdb_v2_value_get_double
#define duckdb_v2_value_get_float                        duckdb_ext_api.duckdb_v2_value_get_float
#define duckdb_v2_value_get_hugeint                      duckdb_ext_api.duckdb_v2_value_get_hugeint
#define duckdb_v2_value_get_int                          duckdb_ext_api.duckdb_v2_value_get_int
#define duckdb_v2_value_get_interval                     duckdb_ext_api.duckdb_v2_value_get_interval
#define duckdb_v2_value_get_logical_type                 duckdb_ext_api.duckdb_v2_value_get_logical_type
#define duckdb_v2_value_get_smallint                     duckdb_ext_api.duckdb_v2_value_get_smallint
#define duckdb_v2_value_get_time                         duckdb_ext_api.duckdb_v2_value_get_time
#define duckdb_v2_value_get_time_ns                      duckdb_ext_api.duckdb_v2_value_get_time_ns
#define duckdb_v2_value_get_time_tz                      duckdb_ext_api.duckdb_v2_value_get_time_tz
#define duckdb_v2_value_get_timestamp                    duckdb_ext_api.duckdb_v2_value_get_timestamp
#define duckdb_v2_value_get_timestamp_ms                 duckdb_ext_api.duckdb_v2_value_get_timestamp_ms
#define duckdb_v2_value_get_timestamp_ns                 duckdb_ext_api.duckdb_v2_value_get_timestamp_ns
#define duckdb_v2_value_get_timestamp_sec                duckdb_ext_api.duckdb_v2_value_get_timestamp_sec
#define duckdb_v2_value_get_timestamp_tz                 duckdb_ext_api.duckdb_v2_value_get_timestamp_tz
#define duckdb_v2_value_get_timestamp_tz_ns              duckdb_ext_api.duckdb_v2_value_get_timestamp_tz_ns
#define duckdb_v2_value_get_tinyint                      duckdb_ext_api.duckdb_v2_value_get_tinyint
#define duckdb_v2_value_get_type                         duckdb_ext_api.duckdb_v2_value_get_type
#define duckdb_v2_value_get_ubigint                      duckdb_ext_api.duckdb_v2_value_get_ubigint
#define duckdb_v2_value_get_uhugeint                     duckdb_ext_api.duckdb_v2_value_get_uhugeint
#define duckdb_v2_value_get_uint                         duckdb_ext_api.duckdb_v2_value_get_uint
#define duckdb_v2_value_get_usmallint                    duckdb_ext_api.duckdb_v2_value_get_usmallint
#define duckdb_v2_value_get_utinyint                     duckdb_ext_api.duckdb_v2_value_get_utinyint
#define duckdb_v2_value_get_uuid                         duckdb_ext_api.duckdb_v2_value_get_uuid
#define duckdb_v2_value_get_varchar                      duckdb_ext_api.duckdb_v2_value_get_varchar
#define duckdb_v2_value_is_null                          duckdb_ext_api.duckdb_v2_value_is_null
#define duckdb_v2_value_to_string                        duckdb_ext_api.duckdb_v2_value_to_string
#define duckdb_v2_vector_constant_set_valid              duckdb_ext_api.duckdb_v2_vector_constant_set_valid
#define duckdb_v2_vector_flat_get_validity_mutable       duckdb_ext_api.duckdb_v2_vector_flat_get_validity_mutable
#define duckdb_v2_vector_flatten                         duckdb_ext_api.duckdb_v2_vector_flatten
#define duckdb_v2_vector_get_arena                       duckdb_ext_api.duckdb_v2_vector_get_arena
#define duckdb_v2_vector_get_child                       duckdb_ext_api.duckdb_v2_vector_get_child
#define duckdb_v2_vector_get_child_count                 duckdb_ext_api.duckdb_v2_vector_get_child_count
#define duckdb_v2_vector_get_data_mutable                duckdb_ext_api.duckdb_v2_vector_get_data_mutable
#define duckdb_v2_vector_get_logical_type                duckdb_ext_api.duckdb_v2_vector_get_logical_type
#define duckdb_v2_vector_get_size                        duckdb_ext_api.duckdb_v2_vector_get_size
#define duckdb_v2_vector_get_value                       duckdb_ext_api.duckdb_v2_vector_get_value
#define duckdb_v2_vector_get_vector_type                 duckdb_ext_api.duckdb_v2_vector_get_vector_type
#define duckdb_v2_vector_get_view                        duckdb_ext_api.duckdb_v2_vector_get_view
#define duckdb_v2_vector_make_constant                   duckdb_ext_api.duckdb_v2_vector_make_constant
#define duckdb_v2_vector_make_sequence                   duckdb_ext_api.duckdb_v2_vector_make_sequence
#define duckdb_v2_vector_reference                       duckdb_ext_api.duckdb_v2_vector_reference
#define duckdb_v2_vector_set_null                        duckdb_ext_api.duckdb_v2_vector_set_null
#define duckdb_v2_vector_set_size                        duckdb_ext_api.duckdb_v2_vector_set_size
#define duckdb_v2_vector_set_value                       duckdb_ext_api.duckdb_v2_vector_set_value
#define duckdb_v2_aggregate_function_bind_get_arg_count  duckdb_ext_api.duckdb_v2_aggregate_function_bind_get_arg_count
#define duckdb_v2_aggregate_function_bind_get_arg_type   duckdb_ext_api.duckdb_v2_aggregate_function_bind_get_arg_type
#define duckdb_v2_aggregate_function_bind_get_arg_value  duckdb_ext_api.duckdb_v2_aggregate_function_bind_get_arg_value
#define duckdb_v2_context_log                            duckdb_ext_api.duckdb_v2_context_log
#define duckdb_v2_function_signature_add_parameter       duckdb_ext_api.duckdb_v2_function_signature_add_parameter
#define duckdb_v2_function_signature_set_return_type     duckdb_ext_api.duckdb_v2_function_signature_set_return_type
#define duckdb_v2_function_signature_set_varargs         duckdb_ext_api.duckdb_v2_function_signature_set_varargs
#define duckdb_v2_scalar_function_bind_get_arg_count     duckdb_ext_api.duckdb_v2_scalar_function_bind_get_arg_count
#define duckdb_v2_scalar_function_bind_get_arg_type      duckdb_ext_api.duckdb_v2_scalar_function_bind_get_arg_type
#define duckdb_v2_scalar_function_bind_get_arg_value     duckdb_ext_api.duckdb_v2_scalar_function_bind_get_arg_value
#define duckdb_v2_scalar_function_bind_get_user_data     duckdb_ext_api.duckdb_v2_scalar_function_bind_get_user_data
#define duckdb_v2_scalar_function_bind_set_bind_data     duckdb_ext_api.duckdb_v2_scalar_function_bind_set_bind_data
#define duckdb_v2_scalar_function_bind_set_return_type   duckdb_ext_api.duckdb_v2_scalar_function_bind_set_return_type
#define duckdb_v2_scalar_function_create_with_connection duckdb_ext_api.duckdb_v2_scalar_function_create_with_connection
#define duckdb_v2_scalar_function_create_with_extension  duckdb_ext_api.duckdb_v2_scalar_function_create_with_extension
#define duckdb_v2_scalar_function_destroy                duckdb_ext_api.duckdb_v2_scalar_function_destroy
#define duckdb_v2_scalar_function_exec_get_arg           duckdb_ext_api.duckdb_v2_scalar_function_exec_get_arg
#define duckdb_v2_scalar_function_exec_get_arg_count     duckdb_ext_api.duckdb_v2_scalar_function_exec_get_arg_count
#define duckdb_v2_scalar_function_exec_get_bind_data     duckdb_ext_api.duckdb_v2_scalar_function_exec_get_bind_data
#define duckdb_v2_scalar_function_exec_get_init_data     duckdb_ext_api.duckdb_v2_scalar_function_exec_get_init_data
#define duckdb_v2_scalar_function_exec_get_result        duckdb_ext_api.duckdb_v2_scalar_function_exec_get_result
#define duckdb_v2_scalar_function_exec_get_row_count     duckdb_ext_api.duckdb_v2_scalar_function_exec_get_row_count
#define duckdb_v2_scalar_function_exec_get_user_data     duckdb_ext_api.duckdb_v2_scalar_function_exec_get_user_data
#define duckdb_v2_scalar_function_get_signature          duckdb_ext_api.duckdb_v2_scalar_function_get_signature
#define duckdb_v2_scalar_function_init_get_bind_data     duckdb_ext_api.duckdb_v2_scalar_function_init_get_bind_data
#define duckdb_v2_scalar_function_init_get_user_data     duckdb_ext_api.duckdb_v2_scalar_function_init_get_user_data
#define duckdb_v2_scalar_function_init_set_init_data     duckdb_ext_api.duckdb_v2_scalar_function_init_set_init_data
#define duckdb_v2_scalar_function_register               duckdb_ext_api.duckdb_v2_scalar_function_register
#define duckdb_v2_scalar_function_set_bind_callback      duckdb_ext_api.duckdb_v2_scalar_function_set_bind_callback
#define duckdb_v2_scalar_function_set_exec_callback      duckdb_ext_api.duckdb_v2_scalar_function_set_exec_callback
#define duckdb_v2_scalar_function_set_init_callback      duckdb_ext_api.duckdb_v2_scalar_function_set_init_callback
#define duckdb_v2_scalar_function_set_name               duckdb_ext_api.duckdb_v2_scalar_function_set_name
#define duckdb_v2_scalar_function_set_user_data          duckdb_ext_api.duckdb_v2_scalar_function_set_user_data
#define duckdb_v2_aggregate_function_bind_get_user_data  duckdb_ext_api.duckdb_v2_aggregate_function_bind_get_user_data
#define duckdb_v2_aggregate_function_bind_set_bind_data  duckdb_ext_api.duckdb_v2_aggregate_function_bind_set_bind_data
#define duckdb_v2_aggregate_function_bind_set_return_type                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_bind_set_return_type
#define duckdb_v2_aggregate_function_combine_get_bind_data                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_combine_get_bind_data
#define duckdb_v2_aggregate_function_combine_get_sources duckdb_ext_api.duckdb_v2_aggregate_function_combine_get_sources
#define duckdb_v2_aggregate_function_combine_get_state_count                                                           \
	duckdb_ext_api.duckdb_v2_aggregate_function_combine_get_state_count
#define duckdb_v2_aggregate_function_combine_get_targets duckdb_ext_api.duckdb_v2_aggregate_function_combine_get_targets
#define duckdb_v2_aggregate_function_combine_get_user_data                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_combine_get_user_data
#define duckdb_v2_aggregate_function_create_with_connection                                                            \
	duckdb_ext_api.duckdb_v2_aggregate_function_create_with_connection
#define duckdb_v2_aggregate_function_create_with_extension                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_create_with_extension
#define duckdb_v2_aggregate_function_destroy duckdb_ext_api.duckdb_v2_aggregate_function_destroy
#define duckdb_v2_aggregate_function_destroy_get_bind_data                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_destroy_get_bind_data
#define duckdb_v2_aggregate_function_destroy_get_state_count                                                           \
	duckdb_ext_api.duckdb_v2_aggregate_function_destroy_get_state_count
#define duckdb_v2_aggregate_function_destroy_get_states duckdb_ext_api.duckdb_v2_aggregate_function_destroy_get_states
#define duckdb_v2_aggregate_function_destroy_get_user_data                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_destroy_get_user_data
#define duckdb_v2_aggregate_function_finalize_get_bind_data                                                            \
	duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_bind_data
#define duckdb_v2_aggregate_function_finalize_get_result duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_result
#define duckdb_v2_aggregate_function_finalize_get_result_offset                                                        \
	duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_result_offset
#define duckdb_v2_aggregate_function_finalize_get_state_count                                                          \
	duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_state_count
#define duckdb_v2_aggregate_function_finalize_get_states duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_states
#define duckdb_v2_aggregate_function_finalize_get_user_data                                                            \
	duckdb_ext_api.duckdb_v2_aggregate_function_finalize_get_user_data
#define duckdb_v2_aggregate_function_get_signature      duckdb_ext_api.duckdb_v2_aggregate_function_get_signature
#define duckdb_v2_aggregate_function_init_get_bind_data duckdb_ext_api.duckdb_v2_aggregate_function_init_get_bind_data
#define duckdb_v2_aggregate_function_init_get_state_count                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_init_get_state_count
#define duckdb_v2_aggregate_function_init_get_states    duckdb_ext_api.duckdb_v2_aggregate_function_init_get_states
#define duckdb_v2_aggregate_function_init_get_user_data duckdb_ext_api.duckdb_v2_aggregate_function_init_get_user_data
#define duckdb_v2_aggregate_function_register           duckdb_ext_api.duckdb_v2_aggregate_function_register
#define duckdb_v2_aggregate_function_set_bind_callback  duckdb_ext_api.duckdb_v2_aggregate_function_set_bind_callback
#define duckdb_v2_aggregate_function_set_combine_callback                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_set_combine_callback
#define duckdb_v2_aggregate_function_set_destroy_callback                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_set_destroy_callback
#define duckdb_v2_aggregate_function_set_finalize_callback                                                             \
	duckdb_ext_api.duckdb_v2_aggregate_function_set_finalize_callback
#define duckdb_v2_aggregate_function_set_init_callback   duckdb_ext_api.duckdb_v2_aggregate_function_set_init_callback
#define duckdb_v2_aggregate_function_set_name            duckdb_ext_api.duckdb_v2_aggregate_function_set_name
#define duckdb_v2_aggregate_function_set_size_callback   duckdb_ext_api.duckdb_v2_aggregate_function_set_size_callback
#define duckdb_v2_aggregate_function_set_update_callback duckdb_ext_api.duckdb_v2_aggregate_function_set_update_callback
#define duckdb_v2_aggregate_function_set_user_data       duckdb_ext_api.duckdb_v2_aggregate_function_set_user_data
#define duckdb_v2_aggregate_function_size_get_bind_data  duckdb_ext_api.duckdb_v2_aggregate_function_size_get_bind_data
#define duckdb_v2_aggregate_function_size_get_user_data  duckdb_ext_api.duckdb_v2_aggregate_function_size_get_user_data
#define duckdb_v2_aggregate_function_size_set_state_size duckdb_ext_api.duckdb_v2_aggregate_function_size_set_state_size
#define duckdb_v2_aggregate_function_update_get_arg      duckdb_ext_api.duckdb_v2_aggregate_function_update_get_arg
#define duckdb_v2_aggregate_function_update_get_arg_count                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_update_get_arg_count
#define duckdb_v2_aggregate_function_update_get_bind_data                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_update_get_bind_data
#define duckdb_v2_aggregate_function_update_get_row_count                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_update_get_row_count
#define duckdb_v2_aggregate_function_update_get_states duckdb_ext_api.duckdb_v2_aggregate_function_update_get_states
#define duckdb_v2_aggregate_function_update_get_user_data                                                              \
	duckdb_ext_api.duckdb_v2_aggregate_function_update_get_user_data
#define duckdb_v2_aggregate_function_set_property duckdb_ext_api.duckdb_v2_aggregate_function_set_property
#define duckdb_v2_scalar_function_set_property    duckdb_ext_api.duckdb_v2_scalar_function_set_property
// capigen:end appended
#endif // DUCKDB_BUILD_STATIC_EXTENSION

//===--------------------------------------------------------------------===//
// Struct Global Macros
//===--------------------------------------------------------------------===//
#ifdef DUCKDB_BUILD_STATIC_EXTENSION
// No vtable global needed for static builds - DuckDB symbols are resolved directly at link time
#define DUCKDB_EXTENSION_GLOBAL
#define DUCKDB_EXTENSION_API_INIT(input, minimum_api_version)
#else
// This goes in the c/c++ file containing the entrypoint
#define DUCKDB_EXTENSION_GLOBAL duckdb_ext_api_v2 duckdb_ext_api = {0};
// Initializes the C Extension API: First thing to call in the extension entrypoint. Nothing else in the API may be
// called before it succeeds, so a failure returns without touching the error slot: the library has already recorded
// why get_api refused, and reports that.
#define DUCKDB_EXTENSION_API_INIT(input, minimum_api_version)                                                          \
	duckdb_ext_api_v2 *res = (duckdb_ext_api_v2 *)(input)->get_api((input)->extension, minimum_api_version);           \
	if (!res) {                                                                                                        \
		return;                                                                                                        \
	};                                                                                                                 \
	duckdb_ext_api = *res;
#endif // DUCKDB_BUILD_STATIC_EXTENSION

// Place in global scope of any C/C++ file that needs to access the extension API
#define DUCKDB_EXTENSION_EXTERN extern duckdb_ext_api_v2 duckdb_ext_api;

#ifdef _WIN32
#define DUCKDB_CAPI_ENTRY_VISIBILITY __declspec(dllexport)
#else
#define DUCKDB_CAPI_ENTRY_VISIBILITY __attribute__((visibility("default")))
#endif

//===--------------------------------------------------------------------===//
// Entrypoint Macros
//===--------------------------------------------------------------------===//

// Note: the DUCKDB_EXTENSION_ENTRYPOINT macro requires DUCKDB_EXTENSION_NAME to be set.

#ifdef DUCKDB_EXTENSION_NAME

// Main entrypoint: receives the extension being loaded to register functionality through, a context to read and run
// queries through, and the error slot to report failure on. Write the body as
//
//		DUCKDB_EXTENSION_ENTRYPOINT(duckdb_v2_extension_handle extension, duckdb_v2_context_handle context,
//		                            duckdb_v2_error_info_handle *err) {
//			...
//		}
#define DUCKDB_EXTENSION_ENTRYPOINT                                                                                    \
	DUCKDB_EXTENSION_GLOBAL static void DUCKDB_EXTENSION_GLUE(DUCKDB_EXTENSION_NAME, _init_c_api_v2_internal)(         \
	    duckdb_v2_extension_handle extension, duckdb_v2_context_handle context, duckdb_v2_error_info_handle * err);    \
	DUCKDB_EXTENSION_EXTERN_C_GUARD_OPEN DUCKDB_CAPI_ENTRY_VISIBILITY DUCKDB_EXTENSION_API void DUCKDB_EXTENSION_GLUE( \
	    DUCKDB_EXTENSION_NAME, _init_c_api_v2)(struct duckdb_v2_extension_input * input) {                             \
		DUCKDB_EXTENSION_API_INIT(input, DUCKDB_EXTENSION_API_VERSION_STRING);                                         \
		DUCKDB_EXTENSION_GLUE(DUCKDB_EXTENSION_NAME, _init_c_api_v2_internal)                                          \
		(input->extension, input->context, input->err);                                                                \
	}                                                                                                                  \
	DUCKDB_EXTENSION_EXTERN_C_GUARD_CLOSE static void DUCKDB_EXTENSION_GLUE(DUCKDB_EXTENSION_NAME,                     \
	                                                                        _init_c_api_v2_internal)

// Custom entrypoint: identical to the main entrypoint
#define DUCKDB_EXTENSION_ENTRYPOINT_CUSTOM DUCKDB_EXTENSION_ENTRYPOINT
#endif
