name: Cancel
on:
  workflow_run:
    workflows: ["Main", "LinuxRelease", "NodeJS", "OSX", "Python", "R", "Windows", "Regression", "cifuzz"]
    branches-ignore:
      - master
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
