name: CodeQuality
on:
  workflow_call:
    inputs:
      explicit_checks:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      explicit_checks:
        description: 'Pass which checks to run or remain empty for default checks'
        type: string
  repository_dispatch:
  merge_group:

concurrency:
  group: codequality-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  enum-check:
    name: C Enum Integrity Check
    runs-on: ubuntu-22.04

    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install python dependencies
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      shell: bash
      run: python -m pip install cxxheaderparser pcpp

    - name: Verify C enum integrity
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      shell: bash
      run: python scripts/verify_enum_integrity.py src/include/duckdb.h

  tidy-check:
    name: Tidy Check
    runs-on: ubuntu-24.04

    env:
      CC: gcc
      CXX: g++
      GEN: ninja
      TIDY_THREADS: 4
      TIDY_CHECKS: ${{ inputs.explicit_checks && inputs.explicit_checks || '' }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install
        shell: bash
        run: |
          python3 scripts/ci/retry.py -- make toolsci
          python3 scripts/ci/retry.py -- sudo apt-get install -y -qq clang-tidy
          python3 scripts/ci/retry.py -- sudo pip3 install pybind11[global] --break-system-packages

      - uses: ./.github/actions/ccache-action

      - name: Download clang-tidy-cache
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature' }}
        shell: bash
        run: |
          set -e
          curl -Lo /tmp/clang-tidy-cache https://github.com/ejfitzgerald/clang-tidy-cache/releases/download/v0.4.0/clang-tidy-cache-linux-amd64
          md5sum /tmp/clang-tidy-cache | grep 880b290d7bbe7c1fb2a4f591f9a86cc1
          chmod +x /tmp/clang-tidy-cache

      - name: Tidy Check
        shell: bash
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature' }}
        run: make tidy-check TIDY_BINARY=/tmp/clang-tidy-cache

      - name: Tidy Check Diff
        shell: bash
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/feature' }}
        run: DUCKDB_GIT_BASE_BRANCH=${{ github.base_ref }} make tidy-check-diff

  # checks that cmake-generated project is consistent on re-configure
  cmake-reconfigure-check:
    name: CMake Reconfigure Check
    runs-on: ${{ matrix.os }}
    needs: format-draft
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Create Dir
        run: |
          mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake .. -G Ninja

      - name: Reconfigure
        working-directory: build
        run: |
          cp build.ninja clean_build.ninja
          cmake .. -G Ninja

      - name: Cleanup Build Files
        working-directory: build
        run: |
          perl -i -ne 'print unless /TARGET_COMPILE_PDB/' clean_build.ninja
          perl -i -ne 'print unless /TARGET_COMPILE_PDB/' build.ninja
          perl -i -ne 'print unless /TARGET_PDB/' clean_build.ninja
          perl -i -ne 'print unless /TARGET_PDB/' build.ninja
          perl -i -ne 'print unless /DuckDBConfig.cmake.in/' clean_build.ninja
          perl -i -ne 'print unless /DuckDBConfig.cmake.in/' build.ninja

      - name: Compare Build Files
        working-directory: build
        run: |
          diff -u clean_build.ninja build.ninja
