#
# This workflow is responsible for building all DuckDB extensions
#

name: Extensions (all platforms)
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      extra_exclude_archs:
        type: string
        required: false
        default: ''
      skip_tests:
        type: boolean
      run_all:
        type: boolean
      # disabling this can result in faster builds, but may run out of space on some runners
      run_disk_clean_step:
        type: boolean
        required: false
        default: true
      opt_in_archs:
        type: string
        required: false
        default: ''
      runners:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      override_git_describe:
        description: 'Version tag to override git describe. Use to produce binaries'
        type: string
      git_ref:
        description: 'Set to override the DuckDB version, leave empty for current commit'
        type: string
        required: false
        default: ''
      extra_exclude_archs:
        description: 'Inject more architectures to skip'
        type: string
        required: false
        default: ''
      opt_in_archs:
        description: 'Semicolon-separated list of architectures to opt into'
        type: string
        required: false
        default: 'windows_arm64;'
      skip_tests:
        description: 'Set to true to skip all testing'
        type: boolean
        required: false
        default: false
      run_all:
        type: boolean
        required: false
        default: true
      run_disk_clean_step:
        description: 'Disabling this can result in faster builds, but may run out of space on some runners'
        type: boolean
        required: false
        default: true
      runners:
        description: 'JSON object with runner labels, e.g. {"linux_x64":"ubuntu-latest","linux_22_x64":"ubuntu-22.04","linux_arm64":"ubuntu-24.04-arm"}'
        type: string
        required: false
        default: '{}'

concurrency:
  group: extensions-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BRANCHES_TO_BE_CACHED: ${{ github.repository == 'duckdb/duckdb' && '["refs/heads/main", "refs/heads/v1.4-andium", "refs/heads/v1.5-variegata"]' || ''}}

jobs:
  # This first step loads the various extension configs from the ~/.github/config directory storing them to drive the build jobs
  load-extension-configs:
    name: Load Extension Configs
    runs-on: ubuntu-slim
    outputs:
      # NOTE: on PRs we exclude some archs to speed things up
      reduced_ci_mode: ${{ (github.event_name == 'pull_request' || !inputs.run_all) && 'enabled' || 'disabled' }}
      main_extensions_config: ${{ steps.set-main-extensions.outputs.extension_config }}
      main_extensions_exclude_archs: ${{ steps.set-main-extensions.outputs.exclude_archs }}
      main_extensions_opt_in_archs: ${{ steps.set-main-extensions.outputs.opt_in_archs }}
      rust_based_extensions_config: ${{ steps.set-rust-based-extensions.outputs.extension_config }}
      rust_based_extensions_exclude_archs: ${{ steps.set-rust-based-extensions.outputs.exclude_archs }}
      external_extensions_config: ${{ steps.set-external-extensions.outputs.extension_config }}
      external_extensions_exclude_archs: ${{ steps.set-external-extensions.outputs.exclude_archs }}

    env:
      EXTRA_EXCLUDE_ARCHS: ${{ inputs.extra_exclude_archs }}
      OPT_IN_ARCHS: ${{ inputs.opt_in_archs }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_ref }}

      - id: set-main-extensions
        name: Configure main extensions
        env:
          IN_TREE_CONFIG_FILE: .github/config/in_tree_extensions.cmake
          OUT_OF_TREE_CONFIG_FILE: .github/config/out_of_tree_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: ''
        run: |
          # Set config
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          echo "opt_in_archs=$OPT_IN_ARCHS" >> "$GITHUB_OUTPUT"
          in_tree_extensions="$(<"$IN_TREE_CONFIG_FILE")"
          out_of_tree_extensions="$(<"$OUT_OF_TREE_CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$in_tree_extensions"
            echo
            echo "$out_of_tree_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - id: set-rust-based-extensions
        name: Configure Rust-based extensions
        env:
          CONFIG_FILE: .github/config/rust_based_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;linux_amd64_musl'
        run: |
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          rust_based_extensions="$(<"$CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$rust_based_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - id: set-external-extensions
        name: Configure External extensions
        env:
          CONFIG_FILE: .github/config/external_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;windows_amd64;linux_amd64_musl'
        run: |
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          external_extensions="$(<"$CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$external_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  # Build the extensions from .github/config/{in_tree,rust_based,external}_extensions.cmake
  extensions-build:
    name: ${{ matrix.name }}
    needs:
      - load-extension-configs
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Main Extensions
            artifact_prefix: main-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.main_extensions_exclude_archs }}
            opt_in_archs: ${{ needs.load-extension-configs.outputs.main_extensions_opt_in_archs }}
            extension_config: ${{ needs.load-extension-configs.outputs.main_extensions_config }}
            extra_toolchains: unixodbc
          - name: Rust-based Extensions
            artifact_prefix: rust-based-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.rust_based_extensions_exclude_archs }}
            opt_in_archs: ''
            extension_config: ${{ needs.load-extension-configs.outputs.rust_based_extensions_config }}
            extra_toolchains: rust
          - name: External Extensions
            artifact_prefix: external-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.external_extensions_exclude_archs }}
            opt_in_archs: ''
            extension_config: ${{ needs.load-extension-configs.outputs.external_extensions_config }}
            extra_toolchains: rust
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      # We piggy-back extension-template to build the extensions in extension_config
      override_repository: duckdb/extension-template
      override_ref: main
      upload_all_extensions: true
      extension_name: ${{ matrix.artifact_prefix }}
      # NOTE: on PRs we exclude some archs to speed things up
      reduced_ci_mode: ${{ needs.load-extension-configs.outputs.reduced_ci_mode }}
      set_caller_as_duckdb: true
      duckdb_version: ${{ inputs.git_ref }}
      override_ci_tools_repository: duckdb/extension-ci-tools
      ci_tools_version: main
      exclude_archs: ${{ matrix.exclude_archs }}
      opt_in_archs: ${{ matrix.opt_in_archs }}
      extra_toolchains: ${{ matrix.extra_toolchains }}
      use_merged_vcpkg_manifest: '1'
      duckdb_tag: ${{ inputs.override_git_describe }}
      skip_tests: ${{ inputs.skip_tests }}
      save_cache: ${{ github.repository != 'duckdb/duckdb' || contains('["main", "v1.5-variegata"]', github.ref_name) }}
      extensions_test_selection: 'complete'
      extra_extension_config: ${{ matrix.extension_config }}
      runners: ${{ inputs.runners }}

  # Merge all extensions into a single, versioned repository
  create-extension-repository:
    name: Create Extension Repository
    runs-on: ubuntu-slim
    needs:
      - extensions-build
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v5
        name: Download main extensions
        with:
          pattern: main-extensions*
          path: /tmp/repository_generation/main-extensions

      - uses: actions/download-artifact@v5
        name: Download rust-based extensions
        with:
          pattern: rust-based-extensions*
          path: /tmp/repository_generation/rust-based-extensions

      - uses: actions/download-artifact@v5
        name: Download external extensions
        with:
          pattern: external-extensions*
          path: /tmp/repository_generation/external-extensions

      - name: Print all extensions
        run: |
          tree /tmp/repository_generation

      - name: Merge into single repository
        shell: bash
        run: |
          mkdir -p /tmp/merged_repository/${{ inputs.git_ref }}
          shopt -s nullglob
          for platform_dir in /tmp/repository_generation/*/*/*; do
            platform="$(basename "$platform_dir")"
            mkdir -p /tmp/merged_repository/${{ inputs.git_ref }}/"$platform"
            cp -r "$platform_dir"/. /tmp/merged_repository/${{ inputs.git_ref }}/"$platform"
          done
          tree /tmp/merged_repository

      - uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: extension-repository
          path: |
            /tmp/merged_repository/**/*.duckdb_extension*

  upload-extensions:
    name: Upload Extensions
    runs-on: ${{ fromJSON(inputs.runners).linux_x64 || 'ubuntu-latest' }}
    needs:
        - create-extension-repository

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v5
        with:
          name: extension-repository
          path: /tmp/extension-repository

      - name: List extensions to deploy
        run: tree /tmp/extension-repository

      - name: Deploy extensions
        shell: bash
        env:
          AWS_ENDPOINT_URL: ${{ secrets.DUCKDB_CORE_EXTENSION_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{secrets.DUCKDB_CORE_EXTENSION_S3_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DUCKDB_CORE_EXTENSION_S3_SECRET}}
          DUCKDB_DEPLOY_SCRIPT_MODE: for_real
          DUCKDB_EXTENSION_SIGNING_PK: ${{ secrets.DUCKDB_EXTENSION_SIGNING_PK }}
        run: |
          python3 scripts/ci/retry.py -- pip install --break-system-packages awscli
          make upload-extensions EXTENSION_REPOSITORY_PATH=/tmp/extension-repository

  autoload-tests:
    name: Extension Autoloading Tests
    if: ${{ !inputs.skip_tests }}
    runs-on: ${{ fromJSON(inputs.runners).linux_x64 || 'ubuntu-latest' }}
    needs:
      - create-extension-repository

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - name: Setup Build Environment
        run: |
          python3 scripts/ci/retry.py -- make toolsci

      - uses: ./.github/actions/ccache-action

      - uses: actions/download-artifact@v5
        with:
          name: extension-repository
          path: /tmp/extension-repository

      - name: List extensions to test with
        run: tree /tmp/extension-repository

      - name: Build DuckDB
        env:
          GEN: ninja
          CC: gcc
          CXX: g++
          EXTENSION_CONFIGS: './.github/config/rust_based_extensions.cmake;./.github/config/out_of_tree_extensions.cmake;./.github/config/in_tree_extensions.cmake'
          EXTENSION_TESTS_ONLY: 1
          ENABLE_EXTENSION_AUTOLOADING: 1
          ENABLE_EXTENSION_AUTOINSTALL: 1
        run: |
          python3 scripts/ci/retry.py -- make release

      - name: Run Tests
        env:
          LOCAL_EXTENSION_REPO: /tmp/extension-repository
          DUCKDB_TEST_DESCRIPTION: 'Running with autoloading of extensions. Run unittest --autoloading available to reproduce locally. Add require no_extension_autoloading to skip the test'
        run: |
          python3 scripts/ci/run_tests.py --test-flags="--autoloading available --skip-compiled" ./build/release/test/unittest

  check-load-install-extensions:
    name: Checks extension entries
    if: ${{ !inputs.skip_tests }}
    runs-on: ${{ fromJSON(inputs.runners).linux_22_x64 || 'ubuntu-22.04' }}
    needs:
      - create-extension-repository
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install
        shell: bash
        run: python3 scripts/ci/retry.py -- make toolsci

      - uses: ./.github/actions/ccache-action

      - name: Build
        shell: bash
        env:
          GENERATE_EXTENSION_ENTRIES: 1
          LOCAL_EXTENSION_REPO: build/release/repository_other
        run: |
          python3 scripts/ci/retry.py -- make

      - uses: actions/download-artifact@v5
        name: Download extension repository artifact
        with:
          name: extension-repository
          path: /tmp/extension-repository

      - name: Copy over local extension repository
        shell: bash
        run: |
          cp -r /tmp/extension-repository build/release/repository
          tree build/release/repository
          find build/release/repository -type f ! -path "build/release/repository/*/linux_amd64/*" -delete
          tree build/release/repository

      - name: Check if extension_entries.hpp is up to date
        shell: bash
        env:
          EXTENSION_CONFIGS: '.github/config/in_tree_extensions.cmake;.github/config/out_of_tree_extensions.cmake'
        run: |
          make extension_configuration
          python scripts/generate_extensions_function.py
          python3 scripts/ci/retry.py -- pip install "black>=24" cmake-format "clang_format==11.0.1"
          make format-fix

      - uses: actions/upload-artifact@v7
        with:
          name: extension_entries.hpp
          path: |
            src/include/duckdb/main/extension_entries.hpp

      - name: Check for any difference
        run: |
          git diff --exit-code src/include/duckdb/main/extension_entries.hpp && echo "No differences found"

      - name: Explainer
        if: failure()
        run: |
          echo "There are differences in src/include/duckdb/main/extension_entries.hpp"
          echo "Check the uploaded extension_entries.hpp (in the workflow Summary), and check that in instead of src/include/duckdb/main/extension_entries.hpp"
