#
# This workflow is responsible for building all DuckDB extensions
#

name: Extensions (all platforms)
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      extra_exclude_archs:
        type: string
        required: false
        default: ''
      skip_tests:
        type: boolean
      run_all:
        type: boolean
      # disabling this can result in faster builds, but may run out of space on some runners
      run_disk_clean_step:
        type: boolean
        required: false
        default: true
      opt_in_archs:
        type: string
        required: false
        default: ''
      runners:
        type: string
        required: true
      save_cache:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      override_git_describe:
        description: 'Version tag to override git describe. Use to produce binaries'
        type: string
      git_ref:
        description: 'Set to override the DuckDB version, leave empty for current commit'
        type: string
        required: false
        default: ''
      extra_exclude_archs:
        description: 'Inject more architectures to skip'
        type: string
        required: false
        default: ''
      opt_in_archs:
        description: 'Semicolon-separated list of architectures to opt into'
        type: string
        required: false
        default: 'windows_arm64;'
      skip_tests:
        description: 'Set to true to skip all testing'
        type: boolean
        required: false
        default: false
      run_all:
        type: boolean
        required: false
        default: true
      run_disk_clean_step:
        description: 'Disabling this can result in faster builds, but may run out of space on some runners'
        type: boolean
        required: false
        default: true
      runners:
        description: 'JSON object with runner labels, e.g. {"linux_x64":"ubuntu-latest","linux_22_x64":"ubuntu-22.04","linux_arm64":"ubuntu-24.04-arm"}'
        type: string
        required: false
        default: '{}'
      save_cache:
        description: 'Override whether extension build caches should be saved'
        type: boolean
        required: false
        default: false

concurrency:
  group: extensions-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  BRANCHES_TO_BE_CACHED: ${{ github.repository == 'duckdb/duckdb' && '["refs/heads/main", "refs/heads/v1.4-andium", "refs/heads/v1.5-variegata"]' || ''}}

jobs:
  # This first step loads the various extension configs from the ~/.github/config directory storing them to drive the build jobs
  load-extension-configs:
    name: Load Extension Configs
    runs-on: ubuntu-slim
    outputs:
      # NOTE: on PRs we exclude some archs to speed things up
      reduced_ci_mode: ${{ (github.event_name == 'pull_request' || !inputs.run_all) && 'enabled' || 'disabled' }}
      main_extensions_config: ${{ steps.set-main-extensions.outputs.extension_config }}
      main_extensions_exclude_archs: ${{ steps.set-main-extensions.outputs.exclude_archs }}
      main_extensions_opt_in_archs: ${{ steps.set-main-extensions.outputs.opt_in_archs }}
      rust_based_extensions_config: ${{ steps.set-rust-based-extensions.outputs.extension_config }}
      rust_based_extensions_exclude_archs: ${{ steps.set-rust-based-extensions.outputs.exclude_archs }}
      external_extensions_config: ${{ steps.set-external-extensions.outputs.extension_config }}
      external_extensions_exclude_archs: ${{ steps.set-external-extensions.outputs.exclude_archs }}

    env:
      EXTRA_EXCLUDE_ARCHS: ${{ inputs.extra_exclude_archs }}
      OPT_IN_ARCHS: ${{ inputs.opt_in_archs }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_ref }}

      - id: set-main-extensions
        name: Configure main extensions
        env:
          IN_TREE_CONFIG_FILE: .github/config/in_tree_extensions.cmake
          OUT_OF_TREE_CONFIG_FILE: .github/config/out_of_tree_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: ''
        run: |
          # Set config
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          echo "opt_in_archs=$OPT_IN_ARCHS" >> "$GITHUB_OUTPUT"
          in_tree_extensions="$(<"$IN_TREE_CONFIG_FILE")"
          out_of_tree_extensions="$(<"$OUT_OF_TREE_CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$in_tree_extensions"
            echo
            echo "$out_of_tree_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - id: set-rust-based-extensions
        name: Configure Rust-based extensions
        env:
          CONFIG_FILE: .github/config/rust_based_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;linux_amd64_musl'
        run: |
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          rust_based_extensions="$(<"$CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$rust_based_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - id: set-external-extensions
        name: Configure External extensions
        env:
          CONFIG_FILE: .github/config/external_extensions.cmake
          DEFAULT_EXCLUDE_ARCHS: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_mingw;windows_amd64;linux_amd64_musl'
        run: |
          echo "exclude_archs=$DEFAULT_EXCLUDE_ARCHS;$EXTRA_EXCLUDE_ARCHS" >> "$GITHUB_OUTPUT"
          external_extensions="$(<"$CONFIG_FILE")"
          {
            echo "extension_config<<EOF"
            echo "$external_extensions"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  # Build the extensions from .github/config/{in_tree,rust_based,external}_extensions.cmake
  extensions-build:
    name: ${{ matrix.name }}
    needs:
      - load-extension-configs
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Main Extensions
            artifact_prefix: main-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.main_extensions_exclude_archs }}
            opt_in_archs: ${{ needs.load-extension-configs.outputs.main_extensions_opt_in_archs }}
            extension_config: ${{ needs.load-extension-configs.outputs.main_extensions_config }}
            extra_toolchains: unixodbc
          - name: Rust-based Extensions
            artifact_prefix: rust-based-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.rust_based_extensions_exclude_archs }}
            opt_in_archs: ''
            extension_config: ${{ needs.load-extension-configs.outputs.rust_based_extensions_config }}
            extra_toolchains: rust
          - name: External Extensions
            artifact_prefix: external-extensions
            exclude_archs: ${{ needs.load-extension-configs.outputs.external_extensions_exclude_archs }}
            opt_in_archs: ''
            extension_config: ${{ needs.load-extension-configs.outputs.external_extensions_config }}
            extra_toolchains: rust
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      # We piggy-back extension-template to build the extensions in extension_config
      override_repository: duckdb/extension-template
      override_ref: main
      upload_all_extensions: true
      extension_name: ${{ matrix.artifact_prefix }}
      # NOTE: on PRs we exclude some archs to speed things up
      reduced_ci_mode: ${{ needs.load-extension-configs.outputs.reduced_ci_mode }}
      set_caller_as_duckdb: true
      duckdb_version: ${{ inputs.git_ref }}
      override_ci_tools_repository: duckdb/extension-ci-tools
      ci_tools_version: main
      exclude_archs: ${{ matrix.exclude_archs }}
      opt_in_archs: ${{ matrix.opt_in_archs }}
      extra_toolchains: ${{ matrix.extra_toolchains }}
      use_merged_vcpkg_manifest: '1'
      duckdb_tag: ${{ inputs.override_git_describe }}
      skip_tests: ${{ inputs.skip_tests }}
      save_cache: ${{ (github.event_name == 'workflow_call' && inputs.save_cache) || (github.event_name != 'workflow_call' && (github.repository != 'duckdb/duckdb' || contains('["main", "v1.5-variegata"]', github.ref_name))) }}
      extensions_test_selection: 'complete'
      extra_extension_config: ${{ matrix.extension_config }}
      runners: ${{ inputs.runners }}

  deploy-repository:
    name: Deploy extensions
    runs-on: ${{ fromJSON(inputs.runners).linux_x64 || 'ubuntu-latest' }}
    needs:
      - extensions-build
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}

      - uses: ./.github/actions/ccache-action

      - uses: actions/download-artifact@v8
        name: Download all extensions
        with:
          pattern: '{main-extensions*,rust-based-extensions*,external-extensions*}'
          path: /tmp/repository_generation
          # When multiple artifacts are matched:
          # - if true: the downloaded artifacts will be in the same directory
          #   specified by path.
          # - if false: the downloaded artifacts will be extracted into
          #   individual named directories within the specified path.
          #
          # Note: When downloading a single artifact (by name or ID), it will
          # always be extracted directly to the specified path.
          merge-multiple: true

      - name: Print all extensions
        run: |
          tree /tmp/repository_generation

          ls /tmp/repository_generation/*/*/*.duckdb_extension*

      - name: Deploy extensions
        shell: bash
        env:
          AWS_ENDPOINT_URL: ${{ secrets.DUCKDB_CORE_EXTENSION_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{secrets.DUCKDB_CORE_EXTENSION_S3_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DUCKDB_CORE_EXTENSION_S3_SECRET}}
          DUCKDB_DEPLOY_SCRIPT_MODE: for_real
          DUCKDB_EXTENSION_SIGNING_PK: ${{ secrets.DUCKDB_EXTENSION_SIGNING_PK }}
        run: |
          curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 https://rclone.org/install.sh | sudo bash
          make upload-extensions EXTENSION_REPOSITORY_PATH=/tmp/repository_generation

      - name: Setup Build Environment
        if: ${{ !inputs.skip_tests }}
        run: python3 scripts/ci/retry.py -- make toolsci

      - name: Build DuckDB
        if: ${{ !inputs.skip_tests }}
        env:
          GEN: ninja
          CC: gcc
          CXX: g++
          EXTENSION_CONFIGS: './.github/config/rust_based_extensions.cmake;./.github/config/out_of_tree_extensions.cmake;./.github/config/in_tree_extensions.cmake'
          EXTENSION_TESTS_ONLY: 1
          ENABLE_EXTENSION_AUTOLOADING: 1
          ENABLE_EXTENSION_AUTOINSTALL: 1
        run: python3 scripts/ci/retry.py -- make release

      - name: Run Tests
        if: ${{ !inputs.skip_tests }}
        env:
          LOCAL_EXTENSION_REPO: /tmp/repository_generation
          DUCKDB_TEST_DESCRIPTION: 'Running with autoloading of extensions. Run unittest --autoloading available to reproduce locally. Add require no_extension_autoloading to skip the test'
        run: make unittest_release SKIP_BUILD=1 T="--test-flags='--autoloading available --skip-compiled'"

      - name: Build other repository
        if: ${{ !inputs.skip_tests }}
        env:
          GENERATE_EXTENSION_ENTRIES: 1
          LOCAL_EXTENSION_REPO: build/release/repository_other
        run: |
          python3 scripts/ci/retry.py -- make release

      - name: Copy over local extension repository
        if: ${{ !inputs.skip_tests }}
        run: |
          cp -r /tmp/repository_generation build/release/repository
          tree build/release/repository
          find build/release/repository -type f ! -path "build/release/repository/*/linux_amd64/*" -delete
          tree build/release/repository

      # Disable downloading release because extension_entries.hpp check fails
      # in CI because some extensions are not available.
      - name: Download linux release artifact
        if: ${{ false && !inputs.skip_tests }}
        id: linux_release_artifact
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: linux-release-build
          path: build

      - name: Extract linux release artifact
        if: ${{ steps.linux_release_artifact.outcome == 'success' }}
        run: |
          rm -rf build/release
          tar -xzf build/release-artifact.tar.gz -C build

      - name: Install format tools
        if: ${{ !inputs.skip_tests }}
        run: python3 scripts/ci/retry.py -- make -j4 format_tools

      - name: Check if extension_entries.hpp is up to date
        if: ${{ !inputs.skip_tests }}
        id: check_extension_entries
        env:
          EXTENSION_CONFIGS: '.github/config/in_tree_extensions.cmake;.github/config/out_of_tree_extensions.cmake'
        run: |
          make check-extension-entries

      - name: Upload extension entries diff
        if: ${{ always() && steps.check_extension_entries.outcome == 'failure' }}
        uses: actions/upload-artifact@v7
        with:
          name: extension-entries-diff
          path: extension_entries.hpp.diff
          if-no-files-found: error
