name: Create or Label Mirror Issue
on:
  issues:
    types:
      - labeled

env:
  GH_TOKEN: ${{ secrets.DUCKDBLABS_BOT_TOKEN }}

jobs:
  handle_pr_submitted_or_fix_on_nightly_label:
    if: github.event.label.name == 'PR submitted' || github.event.label.name == 'fixed on nightly'
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'needs triage' label
        run: |
          gh issue edit --repo duckdb/duckdb ${{ github.event.issue.number }} --remove-label "needs triage"

  add_needs_reproducible_example_comment:
    if: github.event.label.name == 'needs reproducible example'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        run: |
          cat > needs-reproducible-example-comment.md << EOF
          Thanks for opening this issue in the DuckDB issue tracker! To resolve this issue, our team needs a reproducible example. This includes:

          * A source code snippet which reproduces the issue.
          * The snippet should be self-contained, i.e., it should contain all imports and should use relative paths instead of hard coded paths (please avoid \`/Users/JohnDoe/...\`).
          * A lot of issues can be reproduced with plain SQL code executed in the [DuckDB command line client](https://duckdb.org/docs/api/cli/overview). If you can provide such an example, it greatly simplifies the reproduction process and likely results in a faster fix.
          * If the script needs additional data, please share the data as a CSV, JSON, or Parquet file. Unfortunately, we cannot fix issues that can only be reproduced with a confidential data set. [Support contracts](https://duckdblabs.com/#support) allow sharing confidential data with the core DuckDB team under NDA.

          For more detailed guidelines on how to create reproducible examples, please visit Stack Overflow's ["Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example) page.
          EOF
          gh issue comment --repo duckdb/duckdb ${{ github.event.issue.number }} --body-file needs-reproducible-example-comment.md
