name: Main
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '!tools/juliapkg/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '!.github/workflows/Swift.yml'
      - '!.github/workflows/Windows.yml'
      - '!.github/workflows/Regression.yml'
      - '!.github/workflows/Extensions.yml'
      - '!.github/workflows/LinuxRelease.yml'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft, synchronize]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/shell/**'
      - '!tools/juliapkg/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '!.github/workflows/Swift.yml'
      - '!.github/workflows/Windows.yml'
      - '!.github/workflows/Regression.yml'
      - '!.github/workflows/Extensions.yml'
      - '!.github/workflows/LinuxRelease.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
 prepare:
    # We run all other jobs on PRs only if they are not draft PR
    if: |
      (github.event_name != 'pull_request' || github.event.pull_request.draft == false) &&
      (github.event.action != 'synchronize' || github.event.pull_request.user.login == 'smvv')
    runs-on: ${{ github.repository == 'duckdb/duckdb' && 'namespace-profile-linux-small' || 'ubuntu-latest' }}
    outputs:
      runner_linux_small: ${{ steps.select_runner.outputs.runner_linux_small }}
      runner_linux_x64: ${{ steps.select_runner.outputs.runner_linux_x64 }}
      runner_linux_22_x64: ${{ steps.select_runner.outputs.runner_linux_22_x64 }}
      runner_linux_arm64: ${{ steps.select_runner.outputs.runner_linux_arm64 }}
      runner_macos_arm64: ${{ steps.select_runner.outputs.runner_macos_arm64 }}
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
    steps:
      - uses: actions/checkout@v4

      - name: Preliminary checks on CI
        run: echo "Event name is ${{ github.event_name }}"

      - name: Select CI runner
        id: select_runner
        run: |
          # Fall back to GitHub-native runners for forks.
          if [[ "${{ github.repository }}" == "duckdb/duckdb" ]]; then
            {
              echo "runner_linux_small=namespace-profile-linux-small"
              echo "runner_linux_x64=namespace-profile-linux-x64"
              echo "runner_linux_22_x64=namespace-profile-linux-22-x64"
              echo "runner_linux_arm64=namespace-profile-linux-arm64"
              echo "runner_macos_arm64=namespace-profile-macos-arm64"
            } >> "$GITHUB_OUTPUT"
          else
            {
              echo "runner_linux_small=ubuntu-latest"
              echo "runner_linux_x64=ubuntu-latest"
              echo "runner_linux_22_x64=ubuntu-22.04"
              echo "runner_linux_arm64=ubuntu-24.04-arm"
              echo "runner_macos_arm64=macos-14"
            } >> "$GITHUB_OUTPUT"
          fi

          grep runner_ "$GITHUB_OUTPUT"

      - name: Install tools
        run: make format_tools

      - name: List Installed Packages
        run: pip3 freeze

      - name: Check format
        run: |
          clang-format --version
          clang-format --dump-config
          black --version
          make format-check-silent

      - name: Check generated files
        run: |
          make generate-files
          git diff --exit-code

 linux-debug:
    name: Linux Debug
    # This tests release build while enabling slow verifiers (masked by #ifdef DEBUG) and sanitizers
    needs: prepare
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}
    env:
      CC: gcc
      CXX: g++
      TREAT_WARNINGS_AS_ERRORS: 1
      GEN: ninja
      CRASH_ON_ASSERT: 1
      FORCE_DEBUG: 1
      FORCE_ASSERT: 1
      REDUCE_SYMBOLS: 1
      EXTENSIONS_STATIC_BUILD: 0

    steps:
    - uses: actions/checkout@v4

    - id: describe_step
      run: echo "git_describe=$(git describe --tags --long)" >> "$GITHUB_OUTPUT"

    - name: Install tools
      run: make toolsci

    - uses: ./.github/actions/ccache-action

    - name: Build
      run: make relassert

    - name: Smoke tests
      run: make smoke

    - name: Output version info
      run: ./build/relassert/duckdb -c "PRAGMA version;"

    - name: Prepare relassert artifact
      run: make relassert-artifact

    - name: Upload relassert build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-debug-relassert-build
        path: build/relassert-artifact.tar.gz
        if-no-files-found: error

 linux-debug-tests:
    name: Linux Debug Tests
    needs:
      - prepare
      - linux-debug
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}

    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: make toolsci

    - name: Download relassert build artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-debug-relassert-build
        path: build

    - name: Extract relassert build artifact
      run: |
        rm -rf build/relassert
        tar -xzf build/relassert-artifact.tar.gz -C build
        ls -lh build/relassert/test/unittest

    - name: Set DUCKDB_INSTALL_LIB for ADBC tests
      run: echo "DUCKDB_INSTALL_LIB=$(find `pwd` -name "libduck*.so" | head -n 1)" >> $GITHUB_ENV

    - name: Test DUCKDB_INSTALL_LIB variable
      run: echo $DUCKDB_INSTALL_LIB

    - name: Test
      run: make unittest_relassert

 regression:
    uses: ./.github/workflows/Regression.yml
    secrets: inherit
    needs:
      - prepare
      - linux-debug
      - linux-release
    with:
      runner_linux_x64: ${{ needs.prepare.outputs.runner_linux_x64 }}
      runner_linux_small: ${{ needs.prepare.outputs.runner_linux_small }}

 code-quality:
    uses: ./.github/workflows/CodeQuality.yml
    secrets: inherit
    needs: prepare

 extensions:
    uses: ./.github/workflows/Extensions.yml
    secrets: inherit
    needs: linux-debug
    with:
      git_ref: ${{ github.sha }}
      skip_tests: 'false'
      run_all: 'true'

 linux-release:
    name: Linux Release
    needs: prepare
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}
    env:
      GEN: ninja

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: make toolsci

    - uses: ./.github/actions/ccache-action

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: 84bab45d415d22042bd0b9081aea57f362da3f35

    - uses: ./.github/actions/linux_release_build
      with:
        artifact_name: linux-release-build

    - name: Build linux default release
      run: make clean release

    - name: Prepare linux default release artifact
      run: |
        make release-artifact
        mv build/release-artifact.tar.gz build/linux-default-release.tar.gz

    - name: Upload linux default release artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-default-release-build
        path: build/linux-default-release.tar.gz
        if-no-files-found: error

 linux-release-tests:
    name: Linux Release Tests
    needs:
      - prepare
      - linux-release
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}

    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: make toolsci

    - name: Download release build artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-release-build
        path: build

    - name: Extract release build artifact
      shell: bash
      run: |
        rm -rf build/release
        tar -xzf build/release-artifact.tar.gz -C build

    - name: Test
      run: make allunit

 symbol-leakage:
    name: Symbol Leakage
    runs-on: ubuntu-24.04
    needs:
      - prepare
      - linux-release

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Download linux default release artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-default-release-build
        path: build

    - name: Extract linux default release artifact
      run: |
        rm -rf build/release
        tar -xzf build/linux-default-release.tar.gz -C build

    - name: Symbol Leakage Test
      run: python3 scripts/exported_symbols_check.py build/release/src/libduckdb*.so

    - name: Banned Symbol Check
      run: python3 scripts/banned_symbols_check.py --directory build/release/src

 linux-cli:
    uses: ./.github/workflows/LinuxRelease.yml
    secrets: inherit
    needs: linux-debug
    with:
      git_ref: ${{ github.sha }}
      skip_tests: 'false'

 swift:
    uses: ./.github/workflows/Swift.yml
    secrets: inherit
    needs: linux-debug

 windows:
    uses: ./.github/workflows/Windows.yml
    secrets: inherit
    needs: linux-debug
    with:
      git_ref: ${{ github.sha }}
      skip_tests: 'false'
      run_all: 'true'

 no-string-inline:
    name: No String Inline / Destroy Unpinned Blocks
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}
    needs:
      - prepare
      - linux-debug
    env:
      GEN: ninja
      CORE_EXTENSIONS: "icu;parquet;tpch;tpcds;fts;json;inet"
      DISABLE_STRING_INLINE: 1
      DESTROY_UNPINNED_BLOCKS: 1
      ALTERNATIVE_VERIFY: 1
      DISABLE_POINTER_SALT: 1
      LSAN_OPTIONS: suppressions=${{ github.workspace }}/.sanitizer-leak-suppressions.txt
      DUCKDB_TEST_DESCRIPTION: 'Compiled with ALTERNATIVE_VERIFY=1 DISABLE_STRING_INLINE=1 DESTROY_UNPINNED_BLOCKS=1 DISABLE_POINTER_SALT=1. Use require no_alternative_verify to skip.'

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: make toolsci

      - uses: ./.github/actions/ccache-action

      - name: Build
        run: make relassert

      - name: Test
        run: make unittest_relassert

 vector-sizes:
    name: Vector Sizes
    runs-on: ${{ needs.prepare.outputs.runner_linux_22_x64 }}
    needs:
      - prepare
      - linux-debug
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      DUCKDB_TEST_DESCRIPTION: 'Compiled with STANDARD_VECTOR_SIZE=2. Use require vector_size 2048 to skip tests.'

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: make toolsci

      - uses: ./.github/actions/ccache-action

      - name: Build
        run: STANDARD_VECTOR_SIZE=2 make reldebug

      - name: Test
        run: make unittest_reldebug

 valgrind:
    name: Valgrind
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-24.04
    needs: linux-debug
    env:
      CC: clang
      CXX: clang++
      DISABLE_SANITIZER: 1
      BUILD_JEMALLOC: 1
      CORE_EXTENSIONS: 'icu;json;parquet;tpch'
      GEN: ninja

    steps:
    - uses: actions/checkout@v4

    - name: Install
      shell: bash
      run: make toolsci && sudo apt-get install -y -qq valgrind clang

    - uses: ./.github/actions/ccache-action

    - name: Build
      shell: bash
      run: make relassert

    - name: Output version info
      shell: bash
      run: ./build/relassert/duckdb -c "PRAGMA version;"

    - name: Test
      shell: bash
      run: valgrind ./build/relassert/test/unittest test/sql/tpch/tpch_sf001.test_slow

 threadsan:
    name: Thread Sanitizer
    needs:
      - prepare
      - linux-debug
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}
    env:
      CC: clang
      CXX: clang++
      GEN: ninja
      BUILD_JEMALLOC: 1
      CORE_EXTENSIONS: "icu;tpch;tpcds;fts;json;inet"
      TSAN_OPTIONS: suppressions=${{ github.workspace }}/.sanitizer-thread-suppressions.txt
      DUCKDB_TEST_DESCRIPTION: 'Tests run with thread sanitizer.'

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: make toolsci

    - uses: ./.github/actions/ccache-action

    - name: Build
      run: THREADSAN=1 make reldebug

    - name: Test
      run: make unittest_threadsan

 amalgamation-tests:
    name: Amalgamation Tests
    runs-on: ${{ needs.prepare.outputs.runner_linux_small }}
    needs:
      - prepare
      - linux-debug
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Generate Amalgamation
      shell: bash
      run:  |
          python scripts/amalgamation.py --extended
          clang++ -std=c++17 -Isrc/amalgamation src/amalgamation/duckdb.cpp -emit-llvm -S -O0

 # TODO: Consider bringing back fts
 # TODO: DEBUG_STACKTRACE: 1 + reldebug ?
 linux-configs:
    name: Tests a release build with different configurations
    runs-on: ${{ needs.prepare.outputs.runner_linux_x64 }}
    needs:
      - prepare
      - linux-release

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install
      shell: bash
      run: make toolsci

    - name: Download linux release artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-release-build
        path: build

    - name: Extract linux release artifact
      shell: bash
      run: |
        rm -rf build/release
        tar -xzf build/release-artifact.tar.gz -C build

    - name: test/configs/force_storage.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/force_storage.json ./build/release/test/unittest

    - name: test/configs/force_storage_restart.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/force_storage_restart.json ./build/release/test/unittest

    - name: test/configs/latest_storage.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/latest_storage.json ./build/release/test/unittest

    - name: test/configs/block_verification.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/block_verification.json ./build/release/test/unittest

    - name: test/configs/verify_fetch_row.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/verify_fetch_row.json ./build/release/test/unittest

    - name: test/configs/wal_verification.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/wal_verification.json ./build/release/test/unittest

    - name: test/configs/prefetch_all_parquet_files.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/prefetch_all_parquet_files.json ./build/release/test/unittest

    - name: test/configs/no_local_filesystem.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/no_local_filesystem.json ./build/release/test/unittest

    - name: test/configs/block_size_16kB.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/block_size_16kB.json ./build/release/test/unittest

    - name: test/configs/latest_storage_block_size_16kB.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/latest_storage_block_size_16kB.json ./build/release/test/unittest

    - name: test/configs/enable_verification.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/enable_verification.json ./build/release/test/unittest

    - name: test/configs/block_allocator_100mib.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/block_allocator_100mib.json ./build/release/test/unittest

    - name: Test dictionary_expression
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags="--verify-vector dictionary_expression --skip-compiled" ./build/release/test/unittest

    - name: Test dictionary_operator
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags="--verify-vector dictionary_operator --skip-compiled" ./build/release/test/unittest

    - name: Test constant_operator
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags="--verify-vector constant_operator --skip-compiled" ./build/release/test/unittest

    - name: Test sequence_operator
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags="--verify-vector sequence_operator --skip-compiled" ./build/release/test/unittest

    - name: Test nested_shuffle
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags="--verify-vector nested_shuffle --skip-compiled" ./build/release/test/unittest

    - name: Test variant_vector
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/variant_vector.json ./build/release/test/unittest

    - name: Test compressed in memory
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/compressed_in_memory.json ./build/release/test/unittest

    - name: Test sycnronous table scan implementation
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-flags='--on-init "SET debug_physical_table_scan_execution_strategy=SYNCHRONOUS;"' ./build/release/test/unittest

    - name: Test block prefetching
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/prefetch_all_storage.json ./build/release/test/unittest

    - name: Forwards compatibility tests
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/test_storage_compatibility.py --versions "1.2.1|1.3.2|1.4.3" --new-unittest build/release/test/unittest

    - name: test/configs/encryption.json
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/encryption.json ./build/release/test/unittest

    - name: Test PEG parser on fallback mode
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/peg_parser.json ./build/release/test/unittest

    - name: Test PEG parser on strict when supported mode
      if: success() || failure()
      shell: bash
      run: |
        python3 scripts/ci/run_tests.py --test-config=test/configs/peg_parser_strict.json ./build/release/test/unittest
