name: Create Mirror for Discussions
on:
  discussion:
    types:
      - labeled

env:
  GH_TOKEN: ${{ secrets.DUCKDBLABS_BOT_TOKEN }}
  TITLE_PREFIX: "[duckdb/#${{ github.event.discussion.number }}]"
  PUBLIC_DISCUSSION_TITLE: ${{ github.event.discussion.title }}

jobs:
  create_mirror_issue:
    if: github.event.label.name == 'under review'
    runs-on: ubuntu-latest
    steps:
      - name: Create mirror issue for discussion
        run: |
          gh issue create --repo duckdblabs/duckdb-internal --label "discussion" --title "$TITLE_PREFIX - $PUBLIC_DISCUSSION_TITLE" --body "See https://github.com/duckdb/duckdb/discussions/${{ github.event.discussion.number }}"
