name: Swift
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
      runner_macos_arm64:
        type: string
  workflow_dispatch:
    inputs:
      git_ref:
        type: string
  repository_dispatch:

concurrency:
  group: swift-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  test-apple-platforms:
    name: Test Apple Platforms
    strategy:
      matrix:
        # destinations need to match selected version of Xcode
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-simulators
        destination:
          - 'macOS'
          - 'iOS Simulator,name=iPhone 16'
          - 'tvOS Simulator,name=Apple TV 4K (at 1080p) (3nd generation)'
        isRelease:
          - ${{ github.ref == 'refs/heads/main' }}
        exclude:
          - isRelease: false
            destination: 'iOS Simulator,name=iPhone 16'
          - isRelease: false
            destination: 'tvOS Simulator,name=Apple TV 4K (at 1080p) (3nd generation)'
    runs-on: ${{ inputs.runner_macos_arm64 || 'macos-14' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we need tags for the ubiquity build script to run without errors
          fetch-depth: '0'
          ref: ${{ inputs.git_ref != '' && inputs.git_ref || github.sha }}

      - name: Configure Xcode Caching
        if: ${{ startsWith(inputs.runner_macos_arm64 || 'macos-14', 'namespace-profile-') }}
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            xcode
            swiftpm
            cocoapods

      - name: Prepare Package
        run: python3 tools/swift/create_package.py tools/swift

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app && /usr/bin/xcodebuild -version

      - name: Run Tests
        run: |
          python3 scripts/ci/retry.py -- xcrun xcodebuild test \
            -workspace tools/swift/duckdb-swift/DuckDB.xcworkspace \
            -scheme DuckDB \
            -destination platform='${{ matrix.destination }}'
