name: WebAssembly
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!master'
      - '!feature'
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'script/**'
      - 'test/**'
      - 'tools/**'
      - '!tools/wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/WebAssembly.yml'
      - '.github/config/uncovered_files.csv'
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'script/**'
      - 'test/**'
      - 'tools/**'
      - '!tools/wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/WebAssembly.yml'
      - '.github/config/uncovered_files.csv'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  DUCKDB_WASM_VERSION: 7bf2a73

jobs:
 linux-wasm-experimental:
    name: WebAssembly duckdb-wasm builds
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: mymindstorm/setup-emsdk@v12

    - name: Setup
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/duckdb/duckdb-wasm
        cd duckdb-wasm
        git checkout ${{ env.DUCKDB_WASM_VERSION }}
        shopt -s nullglob
        for filename in ../.github/patches/duckdb-wasm/*.patch; do
          git apply $filename
        done

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}

    - name: Build WebAssembly
      shell: bash
      run: |
        cd duckdb-wasm
        bash scripts/wasm_build_lib.sh relsize mvp $(pwd)/..
        bash scripts/wasm_build_lib.sh relsize eh $(pwd)/..
        bash scripts/wasm_build_lib.sh relsize coi $(pwd)/..

    - name: Package
      shell: bash
      run: |
        zip -r duckdb-wasm32.zip duckdb-wasm/packages/duckdb-wasm/src/bindings

    - uses: actions/upload-artifact@v3
      with:
        name: duckdb-wasm32
        path: |
          duckdb-wasm32.zip
