// This file is automatically generated by scripts/generate_metric_enums.py
// Do not edit this file manually, your changes will be overwritten

#include "duckdb/common/enums/metric_type.hpp"
#include "duckdb/common/enum_util.hpp"

namespace duckdb {

profiler_settings_t MetricsUtils::GetAllMetrics() {
	return {
		"ALL_OPTIMIZERS",
		"ATTACH_LOAD_STORAGE_LATENCY",
		"ATTACH_REPLAY_WAL_LATENCY",
		"BLOCKED_THREAD_TIME",
		"CHECKPOINT_LATENCY",
		"COMMIT_LOCAL_STORAGE_LATENCY",
		"CPU_TIME",
		"CUMULATIVE_CARDINALITY",
		"CUMULATIVE_OPTIMIZER_TIMING",
		"CUMULATIVE_ROWS_SCANNED",
		"EXTRA_INFO",
		"LATENCY",
		"OPERATOR_CARDINALITY",
		"OPERATOR_NAME",
		"OPERATOR_ROWS_SCANNED",
		"OPERATOR_TIMING",
		"OPERATOR_TYPE",
		"OPTIMIZER_AGGREGATE_FUNCTION_REWRITER",
		"OPTIMIZER_BUILD_SIDE_PROBE_SIDE",
		"OPTIMIZER_COLUMN_LIFETIME",
		"OPTIMIZER_COMMON_AGGREGATE",
		"OPTIMIZER_COMMON_SUBEXPRESSIONS",
		"OPTIMIZER_COMMON_SUBPLAN",
		"OPTIMIZER_COMPRESSED_MATERIALIZATION",
		"OPTIMIZER_CTE_FILTER_PUSHER",
		"OPTIMIZER_CTE_INLINING",
		"OPTIMIZER_DELIMINATOR",
		"OPTIMIZER_DUPLICATE_GROUPS",
		"OPTIMIZER_EMPTY_RESULT_PULLUP",
		"OPTIMIZER_EXPRESSION_REWRITER",
		"OPTIMIZER_EXTENSION",
		"OPTIMIZER_FILTER_PULLUP",
		"OPTIMIZER_FILTER_PUSHDOWN",
		"OPTIMIZER_IN_CLAUSE",
		"OPTIMIZER_JOIN_ELIMINATION",
		"OPTIMIZER_JOIN_FILTER_PUSHDOWN",
		"OPTIMIZER_JOIN_ORDER",
		"OPTIMIZER_LATE_MATERIALIZATION",
		"OPTIMIZER_LIMIT_PUSHDOWN",
		"OPTIMIZER_MATERIALIZED_CTE",
		"OPTIMIZER_OUTER_JOIN_SIMPLIFICATION",
		"OPTIMIZER_PARTIAL_AGGREGATE_PUSHDOWN",
		"OPTIMIZER_PARTITIONED_EXECUTION",
		"OPTIMIZER_PROJECTION_PULLUP",
		"OPTIMIZER_REGEX_RANGE",
		"OPTIMIZER_REORDER_FILTER",
		"OPTIMIZER_ROW_GROUP_PRUNER",
		"OPTIMIZER_ROW_NUMBER_REWRITER",
		"OPTIMIZER_SAMPLING_PUSHDOWN",
		"OPTIMIZER_STATISTICS_PROPAGATION",
		"OPTIMIZER_TOP_N",
		"OPTIMIZER_TOP_N_WINDOW_ELIMINATION",
		"OPTIMIZER_UNNEST_REWRITER",
		"OPTIMIZER_UNUSED_COLUMNS",
		"OPTIMIZER_WINDOW_SELF_JOIN",
		"PARSER",
		"PHYSICAL_PLANNER",
		"PHYSICAL_PLANNER_COLUMN_BINDING",
		"PHYSICAL_PLANNER_CREATE_PLAN",
		"PHYSICAL_PLANNER_RESOLVE_TYPES",
		"PLANNER",
		"PLANNER_BINDING",
		"QUERY_NAME",
		"RESULT_SET_SIZE",
		"ROWS_RETURNED",
		"SYSTEM_PEAK_BUFFER_MEMORY",
		"SYSTEM_PEAK_TEMP_DIR_SIZE",
		"TOTAL_BYTES_READ",
		"TOTAL_BYTES_WRITTEN",
		"TOTAL_MEMORY_ALLOCATED",
		"WAITING_TO_ATTACH_LATENCY",
		"WAL_REPLAY_ENTRY_COUNT",
		"WRITE_TO_WAL_LATENCY",
	};
}

profiler_settings_t MetricsUtils::GetMetricsByGroupType(MetricGroup type) {
	switch(type) {
	case MetricGroup::ALL:
		return GetAllMetrics();
	case MetricGroup::CORE:
		return GetCoreMetrics();
	case MetricGroup::DEFAULT:
		return GetDefaultMetrics();
	case MetricGroup::EXECUTION:
		return GetExecutionMetrics();
	case MetricGroup::FILE:
		return GetFileMetrics();
	case MetricGroup::OPERATOR:
		return GetOperatorMetrics();
	case MetricGroup::OPTIMIZER:
		return GetOptimizerMetrics();
	case MetricGroup::PHASE_TIMING:
		return GetPhaseTimingMetrics();
	default:
		throw InternalException("The MetricGroup passed is invalid");
	}
}

profiler_settings_t MetricsUtils::GetCoreMetrics() {
	return {
		"CPU_TIME",
		"CUMULATIVE_CARDINALITY",
		"CUMULATIVE_ROWS_SCANNED",
		"EXTRA_INFO",
		"LATENCY",
		"QUERY_NAME",
		"RESULT_SET_SIZE",
		"ROWS_RETURNED",
	};
}

bool MetricsUtils::IsCoreMetric(MetricType type) {
	switch(type) {
	case MetricType::CPU_TIME:
	case MetricType::CUMULATIVE_CARDINALITY:
	case MetricType::CUMULATIVE_ROWS_SCANNED:
	case MetricType::EXTRA_INFO:
	case MetricType::LATENCY:
	case MetricType::QUERY_NAME:
	case MetricType::RESULT_SET_SIZE:
	case MetricType::ROWS_RETURNED:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetDefaultMetrics() {
	return {
		"ATTACH_LOAD_STORAGE_LATENCY",
		"ATTACH_REPLAY_WAL_LATENCY",
		"BLOCKED_THREAD_TIME",
		"CHECKPOINT_LATENCY",
		"COMMIT_LOCAL_STORAGE_LATENCY",
		"CPU_TIME",
		"CUMULATIVE_CARDINALITY",
		"CUMULATIVE_ROWS_SCANNED",
		"EXTRA_INFO",
		"LATENCY",
		"OPERATOR_CARDINALITY",
		"OPERATOR_NAME",
		"OPERATOR_ROWS_SCANNED",
		"OPERATOR_TIMING",
		"OPERATOR_TYPE",
		"QUERY_NAME",
		"RESULT_SET_SIZE",
		"ROWS_RETURNED",
		"SYSTEM_PEAK_BUFFER_MEMORY",
		"SYSTEM_PEAK_TEMP_DIR_SIZE",
		"TOTAL_BYTES_READ",
		"TOTAL_BYTES_WRITTEN",
		"TOTAL_MEMORY_ALLOCATED",
		"WAITING_TO_ATTACH_LATENCY",
		"WAL_REPLAY_ENTRY_COUNT",
		"WRITE_TO_WAL_LATENCY",
	};
}

bool MetricsUtils::IsDefaultMetric(MetricType type) {
	switch(type) {
	case MetricType::ATTACH_LOAD_STORAGE_LATENCY:
	case MetricType::ATTACH_REPLAY_WAL_LATENCY:
	case MetricType::BLOCKED_THREAD_TIME:
	case MetricType::CHECKPOINT_LATENCY:
	case MetricType::COMMIT_LOCAL_STORAGE_LATENCY:
	case MetricType::CPU_TIME:
	case MetricType::CUMULATIVE_CARDINALITY:
	case MetricType::CUMULATIVE_ROWS_SCANNED:
	case MetricType::EXTRA_INFO:
	case MetricType::LATENCY:
	case MetricType::OPERATOR_CARDINALITY:
	case MetricType::OPERATOR_NAME:
	case MetricType::OPERATOR_ROWS_SCANNED:
	case MetricType::OPERATOR_TIMING:
	case MetricType::OPERATOR_TYPE:
	case MetricType::QUERY_NAME:
	case MetricType::RESULT_SET_SIZE:
	case MetricType::ROWS_RETURNED:
	case MetricType::SYSTEM_PEAK_BUFFER_MEMORY:
	case MetricType::SYSTEM_PEAK_TEMP_DIR_SIZE:
	case MetricType::TOTAL_BYTES_READ:
	case MetricType::TOTAL_BYTES_WRITTEN:
	case MetricType::TOTAL_MEMORY_ALLOCATED:
	case MetricType::WAITING_TO_ATTACH_LATENCY:
	case MetricType::WAL_REPLAY_ENTRY_COUNT:
	case MetricType::WRITE_TO_WAL_LATENCY:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetExecutionMetrics() {
	return {
		"BLOCKED_THREAD_TIME",
		"SYSTEM_PEAK_BUFFER_MEMORY",
		"SYSTEM_PEAK_TEMP_DIR_SIZE",
		"TOTAL_MEMORY_ALLOCATED",
	};
}

bool MetricsUtils::IsExecutionMetric(MetricType type) {
	switch(type) {
	case MetricType::BLOCKED_THREAD_TIME:
	case MetricType::SYSTEM_PEAK_BUFFER_MEMORY:
	case MetricType::SYSTEM_PEAK_TEMP_DIR_SIZE:
	case MetricType::TOTAL_MEMORY_ALLOCATED:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetFileMetrics() {
	return {
		"ATTACH_LOAD_STORAGE_LATENCY",
		"ATTACH_REPLAY_WAL_LATENCY",
		"CHECKPOINT_LATENCY",
		"COMMIT_LOCAL_STORAGE_LATENCY",
		"TOTAL_BYTES_READ",
		"TOTAL_BYTES_WRITTEN",
		"WAITING_TO_ATTACH_LATENCY",
		"WAL_REPLAY_ENTRY_COUNT",
		"WRITE_TO_WAL_LATENCY",
	};
}

bool MetricsUtils::IsFileMetric(MetricType type) {
	switch(type) {
	case MetricType::ATTACH_LOAD_STORAGE_LATENCY:
	case MetricType::ATTACH_REPLAY_WAL_LATENCY:
	case MetricType::CHECKPOINT_LATENCY:
	case MetricType::COMMIT_LOCAL_STORAGE_LATENCY:
	case MetricType::TOTAL_BYTES_READ:
	case MetricType::TOTAL_BYTES_WRITTEN:
	case MetricType::WAITING_TO_ATTACH_LATENCY:
	case MetricType::WAL_REPLAY_ENTRY_COUNT:
	case MetricType::WRITE_TO_WAL_LATENCY:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetOperatorMetrics() {
	return {
		"OPERATOR_CARDINALITY",
		"OPERATOR_NAME",
		"OPERATOR_ROWS_SCANNED",
		"OPERATOR_TIMING",
		"OPERATOR_TYPE",
	};
}

bool MetricsUtils::IsOperatorMetric(MetricType type) {
	switch(type) {
	case MetricType::OPERATOR_CARDINALITY:
	case MetricType::OPERATOR_NAME:
	case MetricType::OPERATOR_ROWS_SCANNED:
	case MetricType::OPERATOR_TIMING:
	case MetricType::OPERATOR_TYPE:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetOptimizerMetrics() {
	profiler_settings_t result;
	for (auto metric = START_OPTIMIZER; metric <= END_OPTIMIZER; metric++) {
		result.insert(EnumUtil::ToString(static_cast<MetricType>(metric)));
	}
	return result;
}

bool MetricsUtils::IsOptimizerMetric(MetricType type) {
	return static_cast<uint8_t>(type) >= START_OPTIMIZER && static_cast<uint8_t>(type) <= END_OPTIMIZER;
}


MetricType MetricsUtils::GetOptimizerMetricByType(OptimizerType type) {
	if (type == OptimizerType::INVALID) {
		throw InternalException("Invalid OptimizerType: INVALID");
	}

	const auto base_opt = static_cast<uint8_t>(OptimizerType::EXPRESSION_REWRITER);
	const auto idx = static_cast<uint8_t>(type) - base_opt;

	const auto metric_u8 = static_cast<uint8_t>(START_OPTIMIZER + idx);
	if (metric_u8 < START_OPTIMIZER || metric_u8 > END_OPTIMIZER) {
		throw InternalException("OptimizerType out of MetricType optimizer range");
	}
	return static_cast<MetricType>(metric_u8);
}

OptimizerType MetricsUtils::GetOptimizerTypeByMetric(MetricType type) {
	const auto metric_u8 = static_cast<uint8_t>(type);
	if (!IsOptimizerMetric(type)) {
		throw InternalException("MetricType is not an optimizer metric");
	}

	const auto idx = static_cast<uint8_t>(metric_u8 - START_OPTIMIZER);
	const auto result = static_cast<uint8_t>(OptimizerType::EXPRESSION_REWRITER) + idx;
	return static_cast<OptimizerType>(result);
}

profiler_settings_t MetricsUtils::GetPhaseTimingMetrics() {
	return {
		"ALL_OPTIMIZERS",
		"CUMULATIVE_OPTIMIZER_TIMING",
		"PARSER",
		"PHYSICAL_PLANNER",
		"PHYSICAL_PLANNER_COLUMN_BINDING",
		"PHYSICAL_PLANNER_CREATE_PLAN",
		"PHYSICAL_PLANNER_RESOLVE_TYPES",
		"PLANNER",
		"PLANNER_BINDING",
	};
}

bool MetricsUtils::IsPhaseTimingMetric(MetricType type) {
	switch(type) {
	case MetricType::ALL_OPTIMIZERS:
	case MetricType::CUMULATIVE_OPTIMIZER_TIMING:
	case MetricType::PARSER:
	case MetricType::PHYSICAL_PLANNER:
	case MetricType::PHYSICAL_PLANNER_COLUMN_BINDING:
	case MetricType::PHYSICAL_PLANNER_CREATE_PLAN:
	case MetricType::PHYSICAL_PLANNER_RESOLVE_TYPES:
	case MetricType::PLANNER:
	case MetricType::PLANNER_BINDING:
		return true;
	default:
		return false;
	}
}

profiler_settings_t MetricsUtils::GetRootScopeMetrics() {
	return {
		"ALL_OPTIMIZERS",
		"ATTACH_LOAD_STORAGE_LATENCY",
		"ATTACH_REPLAY_WAL_LATENCY",
		"BLOCKED_THREAD_TIME",
		"CHECKPOINT_LATENCY",
		"COMMIT_LOCAL_STORAGE_LATENCY",
		"CUMULATIVE_OPTIMIZER_TIMING",
		"LATENCY",
		"OPTIMIZER_AGGREGATE_FUNCTION_REWRITER",
		"OPTIMIZER_BUILD_SIDE_PROBE_SIDE",
		"OPTIMIZER_COLUMN_LIFETIME",
		"OPTIMIZER_COMMON_AGGREGATE",
		"OPTIMIZER_COMMON_SUBEXPRESSIONS",
		"OPTIMIZER_COMMON_SUBPLAN",
		"OPTIMIZER_COMPRESSED_MATERIALIZATION",
		"OPTIMIZER_CTE_FILTER_PUSHER",
		"OPTIMIZER_CTE_INLINING",
		"OPTIMIZER_DELIMINATOR",
		"OPTIMIZER_DUPLICATE_GROUPS",
		"OPTIMIZER_EMPTY_RESULT_PULLUP",
		"OPTIMIZER_EXPRESSION_REWRITER",
		"OPTIMIZER_EXTENSION",
		"OPTIMIZER_FILTER_PULLUP",
		"OPTIMIZER_FILTER_PUSHDOWN",
		"OPTIMIZER_IN_CLAUSE",
		"OPTIMIZER_JOIN_ELIMINATION",
		"OPTIMIZER_JOIN_FILTER_PUSHDOWN",
		"OPTIMIZER_JOIN_ORDER",
		"OPTIMIZER_LATE_MATERIALIZATION",
		"OPTIMIZER_LIMIT_PUSHDOWN",
		"OPTIMIZER_MATERIALIZED_CTE",
		"OPTIMIZER_OUTER_JOIN_SIMPLIFICATION",
		"OPTIMIZER_PARTIAL_AGGREGATE_PUSHDOWN",
		"OPTIMIZER_PARTITIONED_EXECUTION",
		"OPTIMIZER_PROJECTION_PULLUP",
		"OPTIMIZER_REGEX_RANGE",
		"OPTIMIZER_REORDER_FILTER",
		"OPTIMIZER_ROW_GROUP_PRUNER",
		"OPTIMIZER_ROW_NUMBER_REWRITER",
		"OPTIMIZER_SAMPLING_PUSHDOWN",
		"OPTIMIZER_STATISTICS_PROPAGATION",
		"OPTIMIZER_TOP_N",
		"OPTIMIZER_TOP_N_WINDOW_ELIMINATION",
		"OPTIMIZER_UNNEST_REWRITER",
		"OPTIMIZER_UNUSED_COLUMNS",
		"OPTIMIZER_WINDOW_SELF_JOIN",
		"PHYSICAL_PLANNER",
		"PHYSICAL_PLANNER_COLUMN_BINDING",
		"PHYSICAL_PLANNER_CREATE_PLAN",
		"PHYSICAL_PLANNER_RESOLVE_TYPES",
		"PLANNER",
		"PLANNER_BINDING",
		"QUERY_NAME",
		"ROWS_RETURNED",
		"TOTAL_BYTES_READ",
		"TOTAL_BYTES_WRITTEN",
		"TOTAL_MEMORY_ALLOCATED",
		"WAITING_TO_ATTACH_LATENCY",
		"WAL_REPLAY_ENTRY_COUNT",
		"WRITE_TO_WAL_LATENCY",
	};
}

bool MetricsUtils::IsRootScopeMetric(MetricType type) {
	switch(type) {
	case MetricType::ALL_OPTIMIZERS:
	case MetricType::ATTACH_LOAD_STORAGE_LATENCY:
	case MetricType::ATTACH_REPLAY_WAL_LATENCY:
	case MetricType::BLOCKED_THREAD_TIME:
	case MetricType::CHECKPOINT_LATENCY:
	case MetricType::COMMIT_LOCAL_STORAGE_LATENCY:
	case MetricType::CUMULATIVE_OPTIMIZER_TIMING:
	case MetricType::LATENCY:
	case MetricType::OPTIMIZER_AGGREGATE_FUNCTION_REWRITER:
	case MetricType::OPTIMIZER_BUILD_SIDE_PROBE_SIDE:
	case MetricType::OPTIMIZER_COLUMN_LIFETIME:
	case MetricType::OPTIMIZER_COMMON_AGGREGATE:
	case MetricType::OPTIMIZER_COMMON_SUBEXPRESSIONS:
	case MetricType::OPTIMIZER_COMMON_SUBPLAN:
	case MetricType::OPTIMIZER_COMPRESSED_MATERIALIZATION:
	case MetricType::OPTIMIZER_CTE_FILTER_PUSHER:
	case MetricType::OPTIMIZER_CTE_INLINING:
	case MetricType::OPTIMIZER_DELIMINATOR:
	case MetricType::OPTIMIZER_DUPLICATE_GROUPS:
	case MetricType::OPTIMIZER_EMPTY_RESULT_PULLUP:
	case MetricType::OPTIMIZER_EXPRESSION_REWRITER:
	case MetricType::OPTIMIZER_EXTENSION:
	case MetricType::OPTIMIZER_FILTER_PULLUP:
	case MetricType::OPTIMIZER_FILTER_PUSHDOWN:
	case MetricType::OPTIMIZER_IN_CLAUSE:
	case MetricType::OPTIMIZER_JOIN_ELIMINATION:
	case MetricType::OPTIMIZER_JOIN_FILTER_PUSHDOWN:
	case MetricType::OPTIMIZER_JOIN_ORDER:
	case MetricType::OPTIMIZER_LATE_MATERIALIZATION:
	case MetricType::OPTIMIZER_LIMIT_PUSHDOWN:
	case MetricType::OPTIMIZER_MATERIALIZED_CTE:
	case MetricType::OPTIMIZER_OUTER_JOIN_SIMPLIFICATION:
	case MetricType::OPTIMIZER_PARTIAL_AGGREGATE_PUSHDOWN:
	case MetricType::OPTIMIZER_PARTITIONED_EXECUTION:
	case MetricType::OPTIMIZER_PROJECTION_PULLUP:
	case MetricType::OPTIMIZER_REGEX_RANGE:
	case MetricType::OPTIMIZER_REORDER_FILTER:
	case MetricType::OPTIMIZER_ROW_GROUP_PRUNER:
	case MetricType::OPTIMIZER_ROW_NUMBER_REWRITER:
	case MetricType::OPTIMIZER_SAMPLING_PUSHDOWN:
	case MetricType::OPTIMIZER_STATISTICS_PROPAGATION:
	case MetricType::OPTIMIZER_TOP_N:
	case MetricType::OPTIMIZER_TOP_N_WINDOW_ELIMINATION:
	case MetricType::OPTIMIZER_UNNEST_REWRITER:
	case MetricType::OPTIMIZER_UNUSED_COLUMNS:
	case MetricType::OPTIMIZER_WINDOW_SELF_JOIN:
	case MetricType::PHYSICAL_PLANNER:
	case MetricType::PHYSICAL_PLANNER_COLUMN_BINDING:
	case MetricType::PHYSICAL_PLANNER_CREATE_PLAN:
	case MetricType::PHYSICAL_PLANNER_RESOLVE_TYPES:
	case MetricType::PLANNER:
	case MetricType::PLANNER_BINDING:
	case MetricType::QUERY_NAME:
	case MetricType::ROWS_RETURNED:
	case MetricType::TOTAL_BYTES_READ:
	case MetricType::TOTAL_BYTES_WRITTEN:
	case MetricType::TOTAL_MEMORY_ALLOCATED:
	case MetricType::WAITING_TO_ATTACH_LATENCY:
	case MetricType::WAL_REPLAY_ENTRY_COUNT:
	case MetricType::WRITE_TO_WAL_LATENCY:
		return true;
	default:
		return false;
	}
}

}
